In [1]:
!pip install pandas --quiet

In [2]:
import pandas as pd

In [3]:
web_dev_df=pd.read_csv("~\Desktop\RPOOPS\Mini Project\Part_B\Raw_Data_Generated\Raw_web_dev_data.csv")
web_dev_df

,Unnamed: 0,Name of company,Address of company,Phone Number,Email Address,Previous Visited COEP,Work Mode,Min CGPA,Seats for Boys,Seats for Girls,...,Preffered month of visiting campus,Domain to Hire,Frontent Languages,Frontend Frameworks,Backend Languages,Backend Frameworks,Databases for Websites,Website Servers,Website Deployment,Website Testing Tools
0,0,LOANTAP,AHMEDABAD,9813683657,loantap@internship.com,No,Work from Home,7.3,2,1,...,Novermber,üåêWeb Development,NaN,"Bulma,React.js,Bootstrap,Angular","JavaScript (Node.js),Java,Ruby","Flask (Python),Express.js (Node.js),Laravel (P...","Couchbase,PostgreSQL","Nginx,Apache,IIS",Kubernetes,Selenium
1,1,VISTEON,PUNE,9282225766,visteon@internship.com,No,Work from office,9.5,1,10,...,July,üåêWeb Development,"Javascript,HTML","Vue.js,Bulma,Bootstrap","PHP,Go,Java,Ruby,Python","ASP.NET (C#),Express.js (Node.js)","MySQL,Redis","IIS,Apache","Docker,Kubernetes","Selenium,Jest"
2,2,GODREJ & BOYCE,KOLKATA,9277026585,godrej&boyce@internship.com,No,Work from office,6.3,6,0,...,September,üåêWeb Development,"Javascript,CSS","Foundation,Backbone.js,React.js,Bulma",NaN,Gin (Go),"Cassandra,Microsoft SQL Server,Oracle,PostgreS...",NaN,Docker,NaN
3,3,ARCESIUM,KOLKATA,9224663882,arcesium@internship.com,No,Work from office,9.0,3,3,...,Novermber,üåêWeb Development,"Javascript,CSS,HTML","Backbone.js,Vue.js,Foundation,Bulma,Materializ...","Ruby,Go,PHP,JavaScript (Node.js)","ASP.NET (C#),Spring (Java)","Microsoft SQL Server,PostgreSQL,MongoDB,Oracle",Apache,Kubernetes,Selenium
4,4,MASTERCARD,NAVI MUMBAI,9457386875,mastercard@internship.com,Yes,Work from Home,8.5,2,6,...,December,üåêWeb Development,"Javascript,CSS","Backbone.js,Bootstrap,Materialize,Ember.js,Bul...",Ruby,"Ruby on Rails (Ruby),Laravel (PHP),ASP.NET (C#...","Cassandra,MongoDB,PostgreSQL,Redis,Microsoft S...","Apache,Nginx,IIS",NaN,"Mocha,Jasmine,Selenium,Cypress"
5,5,ROCKWELL AUTOMATION,KOLKATA,9353093093,rockwellautomation@internship.com,No,Work from office,8.9,0,0,...,December,üåêWeb Development,"HTML,Javascript",NaN,"C#,JavaScript (Node.js)","Flask (Python),Laravel (PHP),Ruby on Rails (Ru...",Redis,NaN,Kubernetes,"Mocha,Jasmine"
6,6,TCS R&I,HARYANA,9051492041,tcsr&i@internship.com,No,Work from office,8.1,7,2,...,Novermber,üåêWeb Development,"Javascript,HTML,CSS","Backbone.js,Bulma,React.js,Vue.js,Foundation","PHP,Java",ASP.NET (C#),Cassandra,NaN,Docker,"Jest,Jasmine,Cypress,Mocha"
7,7,V CONSTRUCT,LATUR,9895805831,vconstruct@internship.com,Yes,Work from Home,6.3,4,3,...,Novermber,üåêWeb Development,"Javascript,HTML,CSS","Backbone.js,Materialize,Ember.js",Python,Flask (Python),"MySQL,Oracle","Nginx,IIS",NaN,"Mocha,Jasmine,Selenium"
8,8,DANA INDIA,MUMBAI,9599155479,danaindia@internship.com,No,Work from Home,7.0,3,0,...,October,üåêWeb Development,NaN,"Bootstrap,Materialize,Ember.js,Foundation,Vue....","C#,Python,Java,JavaScript (Node.js)",NaN,NaN,IIS,NaN,"Mocha,Selenium,Cypress,Jest,Jasmine"
9,9,ZS ASSOCIATES,NOIDA,9099493307,zsassociates@internship.com,Yes,Work from office,7.2,3,1,...,September,üåêWeb Development,CSS,"Ember.js,Materialize","Java,Ruby,PHP,C#,JavaScript (Node.js)","Express.js (Node.js),Ruby on Rails (Ruby),Flas...",MySQL,"IIS,Nginx,Apache",NaN,"Selenium,Jest,Cypress,Mocha"
10,10,ATOMBERG,HYDERABAD,9341449901,atomberg@internship.com,Yes,Work from office,7.4,1,0,...,December,üåêWeb Development,"HTML,Javascript","Foundation,Bulma","Ruby,JavaScript (Node.js),Python,PHP,Go,C#",NaN,"MongoDB,Oracle,Microsoft SQL Server,MySQL",IIS,NaN,"Cypress,Jasmine,Jest,Selenium"
11,11,ZS ASSOCIATES,KOLKATA,9628290024,zsassociates@internship.com,Yes,Work from Home,9.2,2,7,...,September,üåêWeb Development,"HTML,Javascript","Materialize,Ember.js","PHP,Python","Django (Python),Spring (Java)","Oracle,Couchbase,Microsoft SQL Server,Cassandr...","Apache,Nginx","Docker,Kubernetes",NaN
12,12,AMURA MARKETING TECHNOLOGIES,KOLKATA,9131616904,amuramarketingtechnologies@internship.com,Yes,Work from office,8.4,10,3,...,December,üåêWeb Development,"Javascript,HTML","Backbone.js,Ember.js",PHP,"Laravel (PHP),Django (Python),ASP.NET (C#),Fla...","Redis,MySQL,Microsoft SQL Server,MongoDB,Postg...","Apache,IIS,Nginx",Kubernetes,"Jasmine,Jest,Selenium,Mocha"
13,13,OLA ELECTRIC,AHMEDABAD,9984625314,olaelectric@internship.com,Yes,Work from office,8.2,3,4,...,September,üåêWeb Development,"Javascript,CSS,HTML","Foundation,Angular,Vue.js,Backbone.js","JavaScript (Node.js),PHP,Java,C#,Python,Ruby",Django (Python),Redis,NaN,"Kubernetes,Docker",Jest
14,14,TCS R&I,HARYANA,9445688003,tcsr&i@internship.com,No,Work from office,6.1,7,10,...,August,üåêWeb Development,HTML,"Materialize,React.js,Vue.js,Foundation,Bulma,B...",PHP,"Flask (Python),Express.js (Node.js),Gin (Go),S...","Microsoft SQL Server,MySQL,Oracle,PostgreSQL","Nginx,Apache,IIS",Docker,Mocha
15,15,INFOGEN LABS,NOIDA,9810697851,infogenlabs@internship.com,Yes,Work from Home,7.2,7,6,...,December,üåêWeb Development,"HTML,Javascript","Materialize,Foundation,Angular","C#,Python,Ruby","ASP.NET (C#),Express.js (Node.js),Flask (Pytho...","Redis,Couchbase,MySQL,Oracle,Microsoft SQL Ser...","Nginx,Apache","Kubernetes,Docker",NaN
16,16,ATOMBERG,GURGAON,9258090268,atomberg@internship.com,Yes,Work from Home,9.1,9,4,...,December,üåêWeb Development,"Javascript,HTML,CSS","Backbone.js,Ember.js,Bootstrap",NaN,NaN,Oracle,NaN,Kubernetes,"Cypress,Selenium,Mocha,Jasmine,Jest"
17,17,PRECON SERVICES,NAVI MUMBAI,9806409214,preconservices@internship.com,No,Work from office,9.4,5,9,...,December,üåêWeb Development,"HTML,Javascript","React.js,Vue.js","Ruby,C#,Java,Python,Go,PHP",Django (Python),"Cassandra,PostgreSQL","Apache,Nginx",NaN,NaN
18,18,TCS NINJA,MUMBAI,9645128703,tcsninja@internship.com,No,Work from Home,7.4,7,6,...,July,üåêWeb Development,NaN,NaN,"Python,Ruby,Java,Go,JavaScript (Node.js),C#,PHP","Spring (Java),Ruby on Rails (Ruby)","Oracle,Redis,Couchbase,Microsoft SQL Server,Ca...",Apache,NaN,"Jest,Mocha"
19,19,STERLITE TECHNOLOGIES,MUMBAI,9705077936,sterlitetechnologies@internship.com,No,Work from office,6.9,9,4,...,June,üåêWeb Development,HTML,"Bootstrap,Foundation,React.js,Bulma,Angular,Vu...","PHP,C#,Go,Python","Flask (Python),Ruby on Rails (Ruby),Laravel (P...",MySQL,"Apache,Nginx,IIS",NaN,"Jasmine,Mocha"
20,20,GOOGLE,JAPAN,9320948149,google@internship.com,No,Work from office,6.5,9,5,...,December,üåêWeb Development,HTML,"React.js,Materialize,Angular,Foundation,Bootst...","PHP,Python,JavaScript (Node.js),Ruby,Java,Go","Laravel (PHP),ASP.NET (C#),Django (Python),Gin...",NaN,"Apache,IIS,Nginx",Kubernetes,"Cypress,Jest,Mocha,Selenium,Jasmine"
21,21,ADANI GROUP,MUMBAI,9620112133,adanigroup@internship.com,Yes,Work from Home,9.5,6,2,...,Novermber,üåêWeb Development,Javascript,Materialize,"Python,Go,C#,Ruby,Java","Laravel (PHP),Gin (Go),Flask (Python),Express....","MongoDB,Cassandra,Oracle,Redis,Couchbase","IIS,Apache,Nginx",NaN,"Jest,Selenium,Jasmine,Mocha"
22,22,DAIMLER TRUCK INNOVATION,HARYANA,9833667501,daimlertruckinnovation@internship.com,No,Work from Home,9.1,5,4,...,Novermber,üåêWeb Development,HTML,Backbone.js,"Go,PHP,Python,C#,JavaScript (Node.js)","Ruby on Rails (Ruby),Express.js (Node.js),Gin ...",Couchbase,NaN,"Kubernetes,Docker","Jasmine,Jest,Selenium,Cypress"
23,23,SEDEMAC,JAPAN,9964421532,sedemac@internship.com,No,Work from office,7.9,0,1,...,October,üåêWeb Development,"CSS,HTML",Bulma,"Java,Go,C#","Flask (Python),ASP.NET (C#),Express.js (Node.j...","Oracle,Redis,Couchbase,MongoDB,MySQL,Microsoft...","Apache,IIS",NaN,Jest
24,24,BAJAJ AUTO,MUMBAI,9373865128,bajajauto@internship.com,Yes,Work from Home,8.9,3,10,...,Novermber,üåêWeb Development,NaN,"Bootstrap,Foundation,Ember.js",NaN,ASP.NET (C#),NaN,IIS,"Kubernetes,Docker",Selenium
25,25,ELECTROMECH,GURGAON,9321232917,electromech@internship.com,No,Work from Home,9.1,7,8,...,Novermber,üåêWeb Development,NaN,NaN,"Python,PHP,Java,Ruby,JavaScript (Node.js),C#",Laravel (PHP),NaN,Apache,"Docker,Kubernetes",Selenium
26,26,KPIT TECHNOLOGIES,CHENNAI,9580737764,kpittechnologies@internship.com,Yes,Work from Home,8.0,3,5,...,October,üåêWeb Development,Javascript,"Ember.js,Foundation","Java,Python,PHP,JavaScript (Node.js),Ruby","Spring (Java),ASP.NET (C#),Laravel (PHP),Djang...","Oracle,MongoDB,PostgreSQL,Couchbase,Redis,Cass...","IIS,Nginx",Docker,"Cypress,Jest,Jasmine,Mocha"
27,27,HDFC BANK,AURANGABAD,9773426724,hdfcbank@internship.com,Yes,Work from Home,6.6,9,0,...,July,üåêWeb Development,HTML,Foundation,PHP,"Spring (Java),ASP.NET (C#),Flask (Python),Lara...","MongoDB,Microsoft SQL Server,Couchbase,Postgre...",NaN,"Docker,Kubernetes",Jasmine
28,28,ARCESIUM,PUNE,9921692501,arcesium@internship.com,Yes,Work from Home,6.5,3,5,...,December,üåêWeb Development,"CSS,HTML","Bootstrap,Materialize,Ember.js,Bulma","Java,C#,Ruby,JavaScript (Node.js),Python","Spring (Java),Gin (Go),Django (Python),Ruby on...","Microsoft SQL Server,Oracle,Redis,MySQL,MongoD...","Nginx,IIS",Kubernetes,NaN
29,29,ADM,JAPAN,9657266923,adm@internship.com,Yes,Work from office,6.4,1,1,...,June,üåêWeb Development,"HTML,CSS","Ember.js,Vue.js,Bulma,Foundation,React.js,Back...","PHP,Go","Ruby on Rails (Ruby),Flask (Python),Django (Py...","Microsoft SQL Server,PostgreSQL","Nginx,Apache,IIS","Kubernetes,Docker","Jasmine,Selenium,Jest,Mocha"
30,30,ROCKWELL AUTOMATION,JAPAN,9807451834,rockwellautomation@internship.com,No,Work from office,7.4,0,6,...,July,üåêWeb Development,NaN,NaN,Python,"Django (Python),ASP.NET (C#)","PostgreSQL,Redis,MySQL,Cassandra,Oracle,Micros...",NaN,Docker,"Cypress,Jest,Jasmine,Mocha,Selenium"
31,31,MICHELIN,KOLKATA,9306040323,michelin@internship.com,No,Work from Home,9.3,2,6,...,Novermber,üåêWeb Development,"HTML,CSS",Materialize,"C#,Java,Ruby,JavaScript (Node.js)",Laravel (PHP),"Microsoft SQL Server,Cassandra,MongoDB,Couchba...",NaN,Docker,Mocha
32,32,AMURA MARKETING TECHNOLOGIES,NAVI MUMBAI,9228432484,amuramarketingtechnologies@internship.com,Yes,Work from Home,8.4,0,9,...,September,üåêWeb Development,NaN,"Vue.js,React.js",NaN,"Ruby on Rails (Ruby),ASP.NET (C#),Express.js (...","MySQL,Redis,Microsoft SQL Server,MongoDB,Couch...","Nginx,Apache",NaN,Jasmine
33,33,ION GROUP,NOIDA,9203727557,iongroup@internship.com,No,Work from office,7.8,0,3,...,July,üåêWeb Development,"Javascript,HTML",NaN,"Python,Ruby,Go,PHP","Laravel (PHP),ASP.NET (C#)","MySQL,Cassandra,PostgreSQL,Couchbase","Nginx,IIS,Apache","Docker,Kubernetes","Jest,Selenium,Cypress"
34,34,MOTT MACDONALD,CHENNAI,9342693234,mottmacdonald@internship.com,Yes,Work from Home,9.8,7,10,...,July,üåêWeb Development,"CSS,HTML,Javascript",Bootstrap,"PHP,Python,C#,JavaScript (Node.js),Go,Ruby","Ruby on Rails (Ruby),Gin (Go),Laravel (PHP),Sp...","MongoDB,Couchbase,Cassandra,Microsoft SQL Serv...",NaN,"Docker,Kubernetes","Mocha,Jasmine,Selenium"
35,35,GOLDMAN SACHS,NAVI MUMBAI,9690224739,goldmansachs@internship.com,Yes,Work from Home,7.4,0,10,...,August,üåêWeb Development,"CSS,HTML,Javascript","Bootstrap,Foundation,Bulma,Ember.js",JavaScript (Node.js),"ASP.NET (C#),Express.js (Node.js)","Couchbase,Cassandra,Redis","IIS,Nginx","Docker,Kubernetes","Jasmine,Selenium"
36,36,ARCESIUM,JAPAN,9958008202,arcesium@internship.com,No,Work from Home,9.4,5,5,...,October,üåêWeb Development,"CSS,Javascript","Backbone.js,Angular,Materialize,Vue.js,React.j...","C#,Go,JavaScript (Node.js),PHP","Spring (Java),Ruby on Rails (Ruby)",NaN,NaN,Kubernetes,"Cypress,Mocha,Selenium,Jasmine,Jest"
37,37,COGNIZANT GENC,LATUR,9349444206,cognizantgenc@internship.com,No,Work from Home,8.0,3,4,...,September,üåêWeb Development,"CSS,HTML",NaN,"C#,Ruby,PHP","Django (Python),ASP.NET (C#)","Couchbase,Cassandra,MySQL,MongoDB","Nginx,Apache",NaN,"Selenium,Mocha,Jasmine,Cypress"
38,38,CION DIGITAL,JAPAN,9716899788,ciondigital@internship.com,No,Work from Home,9.0,7,5,...,October,üåêWeb Development,NaN,"React.js,Bulma,Backbone.js,Materialize,Foundat...","Python,Go,Java,PHP,C#,JavaScript (Node.js)","Django (Python),Gin (Go),Ruby on Rails (Ruby),...",NaN,IIS,Kubernetes,"Mocha,Selenium,Jasmine,Cypress"
39,39,BAJAJ FINSERV,PUNE,9477711110,bajajfinserv@internship.com,Yes,Work from Home,7.9,6,7,...,December,üåêWeb Development,"CSS,HTML,Javascript","Materialize,Foundation,Ember.js,Bulma,React.js...","PHP,Java,JavaScript (Node.js)","Laravel (PHP),Spring (Java),Flask (Python),ASP...","Cassandra,MongoDB,Redis,MySQL,Couchbase,Oracle...",NaN,"Docker,Kubernetes","Cypress,Jest"
40,40,SHAH TECHNICAL CONSULTANTS PVT.LTD,HARYANA,9975907956,shahtechnicalconsultantspvt.ltd@internship.com,No,Work from Home,7.7,7,4,...,August,üåêWeb Development,CSS,"Bootstrap,Foundation","Go,Python,Ruby","ASP.NET (C#),Spring (Java),Django (Python)","Oracle,MongoDB,Cassandra,Redis,MySQL,PostgreSQ...","Nginx,Apache,IIS","Kubernetes,Docker","Selenium,Jasmine"
41,41,HYUNDAI MOTORS,HARYANA,9082497504,hyundaimotors@internship.com,No,Work from office,9.9,3,6,...,October,üåêWeb Development,Javascript,"Bulma,Materialize,Backbone.js,Angular,Vue.js,E...","JavaScript (Node.js),Ruby,PHP,Java,Python,C#","Django (Python),Laravel (PHP),Gin (Go)","Redis,Couchbase,MongoDB",Nginx,"Docker,Kubernetes","Cypress,Selenium"

In [4]:
web_dev_df.columns

Index(['Unnamed: 0', 'Name of company', 'Address of company', 'Phone Number',
       'Email Address', 'Previous Visited COEP', 'Work Mode', 'Min CGPA',
       'Seats for Boys', 'Seats for Girls',
       'Number of Dead Backlogs permitted',
       'Number of Active Backlogs permitted',
       'Preffered month of visiting campus', 'Domain to Hire',
       'Frontent Languages', 'Frontend Frameworks', 'Backend Languages',
       'Backend Frameworks', 'Databases for Websites', 'Website Servers',
       'Website Deployment', 'Website Testing Tools'],
      dtype='object')

In [5]:
modified_web_dev_df=web_dev_df.drop(['Unnamed: 0','Address of company', 'Phone Number',
       'Email Address', 'Previous Visited COEP'],axis=1)
modified_web_dev_df

,Name of company,Work Mode,Min CGPA,Seats for Boys,Seats for Girls,Number of Dead Backlogs permitted,Number of Active Backlogs permitted,Preffered month of visiting campus,Domain to Hire,Frontent Languages,Frontend Frameworks,Backend Languages,Backend Frameworks,Databases for Websites,Website Servers,Website Deployment,Website Testing Tools
0,LOANTAP,Work from Home,7.3,2,1,2,1,Novermber,üåêWeb Development,NaN,"Bulma,React.js,Bootstrap,Angular","JavaScript (Node.js),Java,Ruby","Flask (Python),Express.js (Node.js),Laravel (P...","Couchbase,PostgreSQL","Nginx,Apache,IIS",Kubernetes,Selenium
1,VISTEON,Work from office,9.5,1,10,2,2,July,üåêWeb Development,"Javascript,HTML","Vue.js,Bulma,Bootstrap","PHP,Go,Java,Ruby,Python","ASP.NET (C#),Express.js (Node.js)","MySQL,Redis","IIS,Apache","Docker,Kubernetes","Selenium,Jest"
2,GODREJ & BOYCE,Work from office,6.3,6,0,1,0,September,üåêWeb Development,"Javascript,CSS","Foundation,Backbone.js,React.js,Bulma",NaN,Gin (Go),"Cassandra,Microsoft SQL Server,Oracle,PostgreS...",NaN,Docker,NaN
3,ARCESIUM,Work from office,9.0,3,3,1,1,Novermber,üåêWeb Development,"Javascript,CSS,HTML","Backbone.js,Vue.js,Foundation,Bulma,Materializ...","Ruby,Go,PHP,JavaScript (Node.js)","ASP.NET (C#),Spring (Java)","Microsoft SQL Server,PostgreSQL,MongoDB,Oracle",Apache,Kubernetes,Selenium
4,MASTERCARD,Work from Home,8.5,2,6,2,2,December,üåêWeb Development,"Javascript,CSS","Backbone.js,Bootstrap,Materialize,Ember.js,Bul...",Ruby,"Ruby on Rails (Ruby),Laravel (PHP),ASP.NET (C#...","Cassandra,MongoDB,PostgreSQL,Redis,Microsoft S...","Apache,Nginx,IIS",NaN,"Mocha,Jasmine,Selenium,Cypress"
5,ROCKWELL AUTOMATION,Work from office,8.9,0,0,1,0,December,üåêWeb Development,"HTML,Javascript",NaN,"C#,JavaScript (Node.js)","Flask (Python),Laravel (PHP),Ruby on Rails (Ru...",Redis,NaN,Kubernetes,"Mocha,Jasmine"
6,TCS R&I,Work from office,8.1,7,2,1,2,Novermber,üåêWeb Development,"Javascript,HTML,CSS","Backbone.js,Bulma,React.js,Vue.js,Foundation","PHP,Java",ASP.NET (C#),Cassandra,NaN,Docker,"Jest,Jasmine,Cypress,Mocha"
7,V CONSTRUCT,Work from Home,6.3,4,3,0,1,Novermber,üåêWeb Development,"Javascript,HTML,CSS","Backbone.js,Materialize,Ember.js",Python,Flask (Python),"MySQL,Oracle","Nginx,IIS",NaN,"Mocha,Jasmine,Selenium"
8,DANA INDIA,Work from Home,7.0,3,0,1,0,October,üåêWeb Development,NaN,"Bootstrap,Materialize,Ember.js,Foundation,Vue....","C#,Python,Java,JavaScript (Node.js)",NaN,NaN,IIS,NaN,"Mocha,Selenium,Cypress,Jest,Jasmine"
9,ZS ASSOCIATES,Work from office,7.2,3,1,2,0,September,üåêWeb Development,CSS,"Ember.js,Materialize","Java,Ruby,PHP,C#,JavaScript (Node.js)","Express.js (Node.js),Ruby on Rails (Ruby),Flas...",MySQL,"IIS,Nginx,Apache",NaN,"Selenium,Jest,Cypress,Mocha"
10,ATOMBERG,Work from office,7.4,1,0,2,1,December,üåêWeb Development,"HTML,Javascript","Foundation,Bulma","Ruby,JavaScript (Node.js),Python,PHP,Go,C#",NaN,"MongoDB,Oracle,Microsoft SQL Server,MySQL",IIS,NaN,"Cypress,Jasmine,Jest,Selenium"
11,ZS ASSOCIATES,Work from Home,9.2,2,7,0,2,September,üåêWeb Development,"HTML,Javascript","Materialize,Ember.js","PHP,Python","Django (Python),Spring (Java)","Oracle,Couchbase,Microsoft SQL Server,Cassandr...","Apache,Nginx","Docker,Kubernetes",NaN
12,AMURA MARKETING TECHNOLOGIES,Work from office,8.4,10,3,1,0,December,üåêWeb Development,"Javascript,HTML","Backbone.js,Ember.js",PHP,"Laravel (PHP),Django (Python),ASP.NET (C#),Fla...","Redis,MySQL,Microsoft SQL Server,MongoDB,Postg...","Apache,IIS,Nginx",Kubernetes,"Jasmine,Jest,Selenium,Mocha"
13,OLA ELECTRIC,Work from office,8.2,3,4,2,0,September,üåêWeb Development,"Javascript,CSS,HTML","Foundation,Angular,Vue.js,Backbone.js","JavaScript (Node.js),PHP,Java,C#,Python,Ruby",Django (Python),Redis,NaN,"Kubernetes,Docker",Jest
14,TCS R&I,Work from office,6.1,7,10,2,0,August,üåêWeb Development,HTML,"Materialize,React.js,Vue.js,Foundation,Bulma,B...",PHP,"Flask (Python),Express.js (Node.js),Gin (Go),S...","Microsoft SQL Server,MySQL,Oracle,PostgreSQL","Nginx,Apache,IIS",Docker,Mocha
15,INFOGEN LABS,Work from Home,7.2,7,6,2,0,December,üåêWeb Development,"HTML,Javascript","Materialize,Foundation,Angular","C#,Python,Ruby","ASP.NET (C#),Express.js (Node.js),Flask (Pytho...","Redis,Couchbase,MySQL,Oracle,Microsoft SQL Ser...","Nginx,Apache","Kubernetes,Docker",NaN
16,ATOMBERG,Work from Home,9.1,9,4,0,2,December,üåêWeb Development,"Javascript,HTML,CSS","Backbone.js,Ember.js,Bootstrap",NaN,NaN,Oracle,NaN,Kubernetes,"Cypress,Selenium,Mocha,Jasmine,Jest"
17,PRECON SERVICES,Work from office,9.4,5,9,0,1,December,üåêWeb Development,"HTML,Javascript","React.js,Vue.js","Ruby,C#,Java,Python,Go,PHP",Django (Python),"Cassandra,PostgreSQL","Apache,Nginx",NaN,NaN
18,TCS NINJA,Work from Home,7.4,7,6,1,0,July,üåêWeb Development,NaN,NaN,"Python,Ruby,Java,Go,JavaScript (Node.js),C#,PHP","Spring (Java),Ruby on Rails (Ruby)","Oracle,Redis,Couchbase,Microsoft SQL Server,Ca...",Apache,NaN,"Jest,Mocha"
19,STERLITE TECHNOLOGIES,Work from office,6.9,9,4,0,2,June,üåêWeb Development,HTML,"Bootstrap,Foundation,React.js,Bulma,Angular,Vu...","PHP,C#,Go,Python","Flask (Python),Ruby on Rails (Ruby),Laravel (P...",MySQL,"Apache,Nginx,IIS",NaN,"Jasmine,Mocha"
20,GOOGLE,Work from office,6.5,9,5,1,1,December,üåêWeb Development,HTML,"React.js,Materialize,Angular,Foundation,Bootst...","PHP,Python,JavaScript (Node.js),Ruby,Java,Go","Laravel (PHP),ASP.NET (C#),Django (Python),Gin...",NaN,"Apache,IIS,Nginx",Kubernetes,"Cypress,Jest,Mocha,Selenium,Jasmine"
21,ADANI GROUP,Work from Home,9.5,6,2,1,0,Novermber,üåêWeb Development,Javascript,Materialize,"Python,Go,C#,Ruby,Java","Laravel (PHP),Gin (Go),Flask (Python),Express....","MongoDB,Cassandra,Oracle,Redis,Couchbase","IIS,Apache,Nginx",NaN,"Jest,Selenium,Jasmine,Mocha"
22,DAIMLER TRUCK INNOVATION,Work from Home,9.1,5,4,2,1,Novermber,üåêWeb Development,HTML,Backbone.js,"Go,PHP,Python,C#,JavaScript (Node.js)","Ruby on Rails (Ruby),Express.js (Node.js),Gin ...",Couchbase,NaN,"Kubernetes,Docker","Jasmine,Jest,Selenium,Cypress"
23,SEDEMAC,Work from office,7.9,0,1,1,2,October,üåêWeb Development,"CSS,HTML",Bulma,"Java,Go,C#","Flask (Python),ASP.NET (C#),Express.js (Node.j...","Oracle,Redis,Couchbase,MongoDB,MySQL,Microsoft...","Apache,IIS",NaN,Jest
24,BAJAJ AUTO,Work from Home,8.9,3,10,2,1,Novermber,üåêWeb Development,NaN,"Bootstrap,Foundation,Ember.js",NaN,ASP.NET (C#),NaN,IIS,"Kubernetes,Docker",Selenium
25,ELECTROMECH,Work from Home,9.1,7,8,1,2,Novermber,üåêWeb Development,NaN,NaN,"Python,PHP,Java,Ruby,JavaScript (Node.js),C#",Laravel (PHP),NaN,Apache,"Docker,Kubernetes",Selenium
26,KPIT TECHNOLOGIES,Work from Home,8.0,3,5,2,0,October,üåêWeb Development,Javascript,"Ember.js,Foundation","Java,Python,PHP,JavaScript (Node.js),Ruby","Spring (Java),ASP.NET (C#),Laravel (PHP),Djang...","Oracle,MongoDB,PostgreSQL,Couchbase,Redis,Cass...","IIS,Nginx",Docker,"Cypress,Jest,Jasmine,Mocha"
27,HDFC BANK,Work from Home,6.6,9,0,2,0,July,üåêWeb Development,HTML,Foundation,PHP,"Spring (Java),ASP.NET (C#),Flask (Python),Lara...","MongoDB,Microsoft SQL Server,Couchbase,Postgre...",NaN,"Docker,Kubernetes",Jasmine
28,ARCESIUM,Work from Home,6.5,3,5,0,0,December,üåêWeb Development,"CSS,HTML","Bootstrap,Materialize,Ember.js,Bulma","Java,C#,Ruby,JavaScript (Node.js),Python","Spring (Java),Gin (Go),Django (Python),Ruby on...","Microsoft SQL Server,Oracle,Redis,MySQL,MongoD...","Nginx,IIS",Kubernetes,NaN
29,ADM,Work from office,6.4,1,1,2,2,June,üåêWeb Development,"HTML,CSS","Ember.js,Vue.js,Bulma,Foundation,React.js,Back...","PHP,Go","Ruby on Rails (Ruby),Flask (Python),Django (Py...","Microsoft SQL Server,PostgreSQL","Nginx,Apache,IIS","Kubernetes,Docker","Jasmine,Selenium,Jest,Mocha"
30,ROCKWELL AUTOMATION,Work from office,7.4,0,6,2,1,July,üåêWeb Development,NaN,NaN,Python,"Django (Python),ASP.NET (C#)","PostgreSQL,Redis,MySQL,Cassandra,Oracle,Micros...",NaN,Docker,"Cypress,Jest,Jasmine,Mocha,Selenium"
31,MICHELIN,Work from Home,9.3,2,6,1,1,Novermber,üåêWeb Development,"HTML,CSS",Materialize,"C#,Java,Ruby,JavaScript (Node.js)",Laravel (PHP),"Microsoft SQL Server,Cassandra,MongoDB,Couchba...",NaN,Docker,Mocha
32,AMURA MARKETING TECHNOLOGIES,Work from Home,8.4,0,9,1,1,September,üåêWeb Development,NaN,"Vue.js,React.js",NaN,"Ruby on Rails (Ruby),ASP.NET (C#),Express.js (...","MySQL,Redis,Microsoft SQL Server,MongoDB,Couch...","Nginx,Apache",NaN,Jasmine
33,ION GROUP,Work from office,7.8,0,3,0,0,July,üåêWeb Development,"Javascript,HTML",NaN,"Python,Ruby,Go,PHP","Laravel (PHP),ASP.NET (C#)","MySQL,Cassandra,PostgreSQL,Couchbase","Nginx,IIS,Apache","Docker,Kubernetes","Jest,Selenium,Cypress"
34,MOTT MACDONALD,Work from Home,9.8,7,10,2,2,July,üåêWeb Development,"CSS,HTML,Javascript",Bootstrap,"PHP,Python,C#,JavaScript (Node.js),Go,Ruby","Ruby on Rails (Ruby),Gin (Go),Laravel (PHP),Sp...","MongoDB,Couchbase,Cassandra,Microsoft SQL Serv...",NaN,"Docker,Kubernetes","Mocha,Jasmine,Selenium"
35,GOLDMAN SACHS,Work from Home,7.4,0,10,2,1,August,üåêWeb Development,"CSS,HTML,Javascript","Bootstrap,Foundation,Bulma,Ember.js",JavaScript (Node.js),"ASP.NET (C#),Express.js (Node.js)","Couchbase,Cassandra,Redis","IIS,Nginx","Docker,Kubernetes","Jasmine,Selenium"
36,ARCESIUM,Work from Home,9.4,5,5,1,2,October,üåêWeb Development,"CSS,Javascript","Backbone.js,Angular,Materialize,Vue.js,React.j...","C#,Go,JavaScript (Node.js),PHP","Spring (Java),Ruby on Rails (Ruby)",NaN,NaN,Kubernetes,"Cypress,Mocha,Selenium,Jasmine,Jest"
37,COGNIZANT GENC,Work from Home,8.0,3,4,1,1,September,üåêWeb Development,"CSS,HTML",NaN,"C#,Ruby,PHP","Django (Python),ASP.NET (C#)","Couchbase,Cassandra,MySQL,MongoDB","Nginx,Apache",NaN,"Selenium,Mocha,Jasmine,Cypress"
38,CION DIGITAL,Work from Home,9.0,7,5,0,0,October,üåêWeb Development,NaN,"React.js,Bulma,Backbone.js,Materialize,Foundat...","Python,Go,Java,PHP,C#,JavaScript (Node.js)","Django (Python),Gin (Go),Ruby on Rails (Ruby),...",NaN,IIS,Kubernetes,"Mocha,Selenium,Jasmine,Cypress"
39,BAJAJ FINSERV,Work from Home,7.9,6,7,2,2,December,üåêWeb Development,"CSS,HTML,Javascript","Materialize,Foundation,Ember.js,Bulma,React.js...","PHP,Java,JavaScript (Node.js)","Laravel (PHP),Spring (Java),Flask (Python),ASP...","Cassandra,MongoDB,Redis,MySQL,Couchbase,Oracle...",NaN,"Docker,Kubernetes","Cypress,Jest"
40,SHAH TECHNICAL CONSULTANTS PVT.LTD,Work from Home,7.7,7,4,0,2,August,üåêWeb Development,CSS,"Bootstrap,Foundation","Go,Python,Ruby","ASP.NET (C#),Spring (Java),Django (Python)","Oracle,MongoDB,Cassandra,Redis,MySQL,PostgreSQ...","Nginx,Apache,IIS","Kubernetes,Docker","Selenium,Jasmine"
41,HYUNDAI MOTORS,Work from office,9.9,3,6,0,0,October,üåêWeb Development,Javascript,"Bulma,Materialize,Backbone.js,Angular,Vue.js,E...","JavaScript (Node.js),Ruby,PHP,Java,Python,C#","Django (Python),Laravel (PHP),Gin (Go)","Redis,Couchbase,MongoDB",Nginx,"Docker,Kubernetes","Cypress,Selenium"

In [6]:
modified_web_dev_df.to_csv("~\Desktop\RPOOPS\Mini Project\Part_B\Final_Data\Final_web_dev_data.csv")

In [7]:
app_dev_df=pd.read_csv("~\Desktop\RPOOPS\Mini Project\Part_B\Raw_Data_Generated\Raw_app_dev_data.csv")
app_dev_df

,Unnamed: 0,Name of company,Address of company,Phone Number,Email Address,Previous Visited COEP,Work Mode,Min CGPA,Seats for Boys,Seats for Girls,...,Domain to Hire,Native Mobile App Development,Cross-Platform Mobile App Development,Backend Development Languages,Backend Development Frameworks,Databases for Apps,Web Services for App Development,Cloud Platform,Deployment of App,Testing of App
0,0,PIRAMAL,NAVI MUMBAI,9146494742,piramal@internship.com,No,Work from office,7.8,7,6,...,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)","React Native,Xamarin","C#,Python,Go,PHP,Java","Flask (Python),Gin (Go),Express.js (Node.js),L...","MySQL,Cassandra,MongoDB,Oracle,Microsoft SQL S...",NaN,"Microsoft Azure,AWS,Google Cloud Platform",Docker,"Jest,Selenium,Jasmine,Mocha,Cypress,Appium"
1,1,UGAM SOLUTIONS,NOIDA,9391745295,ugamsolutions@internship.com,Yes,Work from Home,6.6,2,0,...,üì±Mobile App Development,"Java (Android),Swift/Objective-C (iOS)","Flutter,React Native,Xamarin","Java,Go,Python,JavaScript (Node.js),Ruby,C#","Laravel (PHP),Flask (Python),ASP.NET (C#),Spri...",NaN,"GraphQL,RESTful APIs",NaN,NaN,"Jasmine,Selenium,Jest,Mocha"
2,2,SOC GEN,AURANGABAD,9790924075,socgen@internship.com,No,Work from Home,7.7,4,4,...,üì±Mobile App Development,"Java (Android),Swift/Objective-C (iOS)",React Native,"Java,PHP,Python","Flask (Python),Express.js (Node.js),Django (Py...","Redis,MongoDB,Oracle,MySQL,Microsoft SQL Serve...",RESTful APIs,"Microsoft Azure,AWS,Google Cloud Platform",NaN,Appium
3,3,HINDUJA TECH LIMITED,AHMEDABAD,9969000757,hindujatechlimited@internship.com,Yes,Work from Home,9.9,9,10,...,üì±Mobile App Development,NaN,NaN,"JavaScript (Node.js),C#","Laravel (PHP),Spring (Java),Express.js (Node.j...","MongoDB,Cassandra,Redis,Microsoft SQL Server,M...",NaN,AWS,"Docker,Kubernetes","Appium,Mocha"
4,4,TAVISCA,JAIPUR,9451165928,tavisca@internship.com,Yes,Work from Home,9.2,7,8,...,üì±Mobile App Development,Swift/Objective-C (iOS),"Xamarin,Flutter,React Native","C#,JavaScript (Node.js)","Ruby on Rails (Ruby),ASP.NET (C#),Django (Pyth...","Couchbase,MySQL",RESTful APIs,Google Cloud Platform,Docker,"Cypress,Jest"
5,5,WINJIT TECHNOLOGIES,LATUR,9522052136,winjittechnologies@internship.com,Yes,Work from office,7.2,2,3,...,üì±Mobile App Development,Java (Android),"Flutter,React Native","C#,Java,Go,PHP","Spring (Java),Flask (Python),Laravel (PHP),Rub...",Cassandra,NaN,"Google Cloud Platform,AWS",NaN,"Jest,Jasmine,Cypress,Selenium,Appium,Mocha"
6,6,VISTEON,HARYANA,9496549957,visteon@internship.com,Yes,Work from office,7.7,1,9,...,üì±Mobile App Development,Swift/Objective-C (iOS),NaN,"Java,PHP,Ruby,C#","Ruby on Rails (Ruby),Flask (Python),ASP.NET (C...","Cassandra,MySQL,Couchbase,PostgreSQL,Redis,Mic...",NaN,AWS,NaN,Appium
7,7,TCS NINJA,JAIPUR,9962690400,tcsninja@internship.com,Yes,Work from office,8.8,6,2,...,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)","React Native,Flutter","Java,Ruby,C#,Go","Gin (Go),ASP.NET (C#),Flask (Python),Express.j...","Cassandra,MongoDB,MySQL",GraphQL,Microsoft Azure,Kubernetes,"Cypress,Mocha,Jest,Appium,Selenium"
8,8,BAJAJ FINSERV,NASHIK,9789429572,bajajfinserv@internship.com,Yes,Work from Home,6.7,10,0,...,üì±Mobile App Development,NaN,React Native,"PHP,Java,Python","Express.js (Node.js),Ruby on Rails (Ruby),Spri...","Redis,Microsoft SQL Server,PostgreSQL,MySQL",NaN,"AWS,Microsoft Azure",Kubernetes,"Appium,Jest"
9,9,NUANCE,CHENNAI,9001290504,nuance@internship.com,Yes,Work from office,8.3,7,6,...,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)",Xamarin,"JavaScript (Node.js),PHP,Go,Ruby",Express.js (Node.js),"Couchbase,Redis,Oracle,PostgreSQL",RESTful APIs,"Microsoft Azure,AWS",Docker,"Jasmine,Selenium,Jest"
10,10,ADOR WELDING,LATUR,9976365489,adorwelding@internship.com,Yes,Work from Home,6.3,8,10,...,üì±Mobile App Development,Java (Android),Xamarin,"Python,JavaScript (Node.js),C#,Ruby","Spring (Java),Ruby on Rails (Ruby),Laravel (PH...","Couchbase,MongoDB,Redis,PostgreSQL,Microsoft S...",RESTful APIs,AWS,Kubernetes,Jest
11,11,EY INDIA,NAVI MUMBAI,9391163565,eyindia@internship.com,No,Work from office,6.0,0,1,...,üì±Mobile App Development,NaN,React Native,"C#,Go,Python","Ruby on Rails (Ruby),Flask (Python),Gin (Go),D...",NaN,NaN,Google Cloud Platform,"Kubernetes,Docker","Cypress,Selenium"
12,12,TEXAS INSTRUMENTS,MUMBAI,9495674092,texasinstruments@internship.com,Yes,Work from office,8.1,4,1,...,üì±Mobile App Development,"Java (Android),Swift/Objective-C (iOS)","Xamarin,React Native,Flutter","JavaScript (Node.js),C#,Ruby,PHP,Java,Go","Flask (Python),Laravel (PHP),Ruby on Rails (Ru...","PostgreSQL,Microsoft SQL Server",NaN,"Microsoft Azure,Google Cloud Platform",Docker,"Jest,Selenium,Jasmine,Cypress,Mocha,Appium"
13,13,SIEMENS LIMITED COBRA,NAVI MUMBAI,9923602142,siemenslimitedcobra@internship.com,Yes,Work from Home,6.5,1,10,...,üì±Mobile App Development,NaN,"Flutter,Xamarin,React Native","Java,Python,JavaScript (Node.js),Ruby","Ruby on Rails (Ruby),Express.js (Node.js),Lara...","Microsoft SQL Server,Couchbase",NaN,"Google Cloud Platform,Microsoft Azure","Docker,Kubernetes","Mocha,Jasmine,Jest,Selenium,Appium,Cypress"
14,14,EY INDIA,CHENNAI,9967550088,eyindia@internship.com,No,Work from office,8.5,6,0,...,üì±Mobile App Development,"Java (Android),Swift/Objective-C (iOS)","Flutter,Xamarin,React Native","Ruby,Python",NaN,"Couchbase,Oracle","RESTful APIs,GraphQL",NaN,"Kubernetes,Docker","Appium,Cypress,Mocha,Selenium"
15,15,CREDIT SUISSE,KOLKATA,9544619208,creditsuisse@internship.com,Yes,Work from office,8.3,7,5,...,üì±Mobile App Development,NaN,"Xamarin,Flutter,React Native","Java,C#,Go,PHP,Python","ASP.NET (C#),Django (Python),Gin (Go),Ruby on ...","MongoDB,Oracle",NaN,Google Cloud Platform,"Kubernetes,Docker",NaN
16,16,MG MOTOR,LATUR,9654000523,mgmotor@internship.com,No,Work from Home,8.0,3,1,...,üì±Mobile App Development,Swift/Objective-C (iOS),NaN,"PHP,JavaScript (Node.js),C#,Ruby,Java,Python","Spring (Java),ASP.NET (C#),Gin (Go)","Redis,Couchbase,MySQL,PostgreSQL",NaN,NaN,"Docker,Kubernetes","Selenium,Jasmine,Jest"
17,17,ADITYA BIRLA GROUP,JAIPUR,9526227839,adityabirlagroup@internship.com,Yes,Work from Home,6.1,6,10,...,üì±Mobile App Development,NaN,NaN,"Ruby,C#,Java,PHP","Spring (Java),Flask (Python),Laravel (PHP),Gin...",MySQL,NaN,Microsoft Azure,"Docker,Kubernetes",NaN
18,18,TVS MOTOR,MUMBAI,9516490899,tvsmotor@internship.com,Yes,Work from office,9.6,7,7,...,üì±Mobile App Development,Java (Android),NaN,"C#,Java,PHP,JavaScript (Node.js),Python,Go","Express.js (Node.js),Flask (Python),Gin (Go),S...","Oracle,PostgreSQL","GraphQL,RESTful APIs",AWS,Kubernetes,"Mocha,Jasmine"
19,19,ADITYA BIRLA GROUP,LATUR,9775423354,adityabirlagroup@internship.com,Yes,Work from office,9.9,3,1,...,üì±Mobile App Development,NaN,Flutter,NaN,"Laravel (PHP),Express.js (Node.js),Spring (Jav...","MySQL,Couchbase,Microsoft SQL Server,Oracle,Mo...",RESTful APIs,NaN,Kubernetes,"Cypress,Selenium,Mocha,Jasmine,Appium"
20,20,WINJIT TECHNOLOGIES,CHENNAI,9321907447,winjittechnologies@internship.com,Yes,Work from Home,8.9,1,7,...,üì±Mobile App Development,NaN,React Native,"Go,C#","Gin (Go),Flask (Python),Laravel (PHP),Express....","Redis,Microsoft SQL Server,Couchbase,Cassandra","RESTful APIs,GraphQL","AWS,Microsoft Azure",Kubernetes,"Jasmine,Jest,Selenium,Appium,Mocha,Cypress"
21,21,SEDEMAC,JAPAN,9203013543,sedemac@internship.com,No,Work from Home,7.1,2,0,...,üì±Mobile App Development,NaN,NaN,NaN,"Gin (Go),Laravel (PHP),Ruby on Rails (Ruby),Sp...","Microsoft SQL Server,Redis,MySQL,Couchbase,Mon...",NaN,"Microsoft Azure,Google Cloud Platform","Kubernetes,Docker","Cypress,Jest,Appium,Mocha"
22,22,AMERICAN AXLE MANUFACTURING INDIA PVT.LTD,WALCHAND,9109760954,americanaxlemanufacturingindiapvt.ltd@internsh...,No,Work from office,6.3,1,10,...,üì±Mobile App Development,Java (Android),"React Native,Xamarin,Flutter",NaN,ASP.NET (C#),NaN,RESTful APIs,AWS,NaN,NaN
23,23,GODREJ & BOYCE,JAIPUR,9536571796,godrej&boyce@internship.com,No,Work from office,9.1,10,7,...,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)",Xamarin,"Go,PHP","Ruby on Rails (Ruby),Express.js (Node.js),ASP....","Couchbase,Microsoft SQL Server,Cassandra",NaN,Microsoft Azure,NaN,"Jasmine,Cypress"
24,24,EMERSON EXPORTS ENGINEERING CENTER,NASHIK,9605416576,emersonexportsengineeringcenter@internship.com,Yes,Work from office,9.0,7,9,...,üì±Mobile App Development,NaN,Xamarin,"Python,PHP,Ruby","Spring (Java),ASP.NET (C#),Gin (Go)",Oracle,RESTful APIs,NaN,Kubernetes,"Selenium,Cypress,Mocha,Jasmine"
25,25,SAARLOHA ADVANCE MATERIALS,JAIPUR,9858172197,saarlohaadvancematerials@internship.com,Yes,Work from office,6.9,9,10,...,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)","React Native,Xamarin,Flutter","Java,Python,JavaScript (Node.js),C#,Ruby","Spring (Java),Django (Python),Ruby on Rails (R...","Microsoft SQL Server,Cassandra","RESTful APIs,GraphQL","AWS,Microsoft Azure","Kubernetes,Docker","Jest,Jasmine"
26,26,SEDEMAC,WALCHAND,9096590013,sedemac@internship.com,No,Work from office,7.6,10,6,...,üì±Mobile App Development,NaN,Xamarin,Python,"ASP.NET (C#),Django (Python),Spring (Java),Gin...","Redis,PostgreSQL,Cassandra",RESTful APIs,Microsoft Azure,"Docker,Kubernetes","Selenium,Appium,Cypress,Jasmine,Jest"
27,27,LG ELECTRONICS,WALCHAND,9084392295,lgelectronics@internship.com,No,Work from office,8.0,1,10,...,üì±Mobile App Development,NaN,"Flutter,React Native,Xamarin","Python,PHP,Ruby,JavaScript (Node.js),C#,Java,Go","ASP.NET (C#),Flask (Python)","PostgreSQL,Couchbase,Microsoft SQL Server,Oracle","GraphQL,RESTful APIs",NaN,NaN,"Jest,Mocha"
28,28,BAJAJ AUTO,JAIPUR,9821614002,bajajauto@internship.com,No,Work from Home,7.8,3,9,...,üì±Mobile App Development,Java (Android),"Xamarin,Flutter,React Native","PHP,Ruby,JavaScript (Node.js)",Express.js (Node.js),"Cassandra,Oracle,Couchbase,Redis,MySQL,Microso...","RESTful APIs,GraphQL","Google Cloud Platform,Microsoft Azure,AWS",NaN,NaN
29,29,TATA AUTOCOMP SYSTEMS,JAPAN,9508614201,tataautocompsystems@internship.com,No,Work from office,6.2,6,0,...,üì±Mobile App Development,NaN,"React Native,Flutter",C#,"Django (Python),Spring (Java),Express.js (Node...","Microsoft SQL Server,MySQL,PostgreSQL,Oracle,C...",NaN,NaN,NaN,"Cypress,Selenium,Appium"
30,30,OLA ELECTRIC,HARYANA,9879498151,olaelectric@internship.com,No,Work from office,6.3,9,0,...,üì±Mobile App Development,NaN,"Flutter,React Native,Xamarin",JavaScript (Node.js),NaN,"Cassandra,Microsoft SQL Server,PostgreSQL,Oracle",GraphQL,"Google Cloud Platform,AWS",NaN,"Cypress,Mocha"
31,31,MERCEDES BENZ,HYDERABAD,9388646019,mercedesbenz@internship.com,Yes,Work from Home,8.4,0,6,...,üì±Mobile App Development,"Java (Android),Swift/Objective-C (iOS)","React Native,Xamarin",NaN,"Laravel (PHP),Express.js (Node.js)","Couchbase,MySQL,MongoDB,Oracle,Cassandra","GraphQL,RESTful APIs",Microsoft Azure,NaN,"Cypress,Jasmine,Jest,Selenium,Appium"
32,32,TATA STEEL DOWNSTREAM PRODUCTS LTD,AHMEDABAD,9494561886,tatasteeldownstreamproductsltd@internship.com,No,Work from office,8.9,3,0,...,üì±Mobile App Development,NaN,Flutter,"Go,C#,JavaScript (Node.js)","Ruby on Rails (Ruby),Express.js (Node.js),Gin ...","Redis,MySQL",NaN,NaN,Kubernetes,"Cypress,Selenium,Mocha"
33,33,WALCHAND INDUSTRIES,HARYANA,9284206350,walchandindustries@internship.com,No,Work from Home,6.4,2,9,...,üì±Mobile App Development,NaN,Flutter,NaN,"Gin (Go),Laravel (PHP),Flask (Python),Django (...","MySQL,PostgreSQL,Couchbase,Microsoft SQL Server","GraphQL,RESTful APIs","AWS,Microsoft Azure",Kubernetes,NaN
34,34,BROSE INDIA,WALCHAND,9518610251,broseindia@internship.com,Yes,Work from office,9.2,3,1,...,üì±Mobile App Development,Java (Android),Xamarin,"Go,C#","Spring (Java),ASP.NET (C#),Laravel (PHP),Ruby ...",Redis,NaN,"AWS,Microsoft Azure",NaN,"Mocha,Appium,Jasmine,Jest,Cypress"
35,35,GAINSIGHT,NOIDA,9693736494,gainsight@internship.com,Yes,Work from office,7.7,10,5,...,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)","Xamarin,Flutter","Ruby,Python,Go,Java,JavaScript (Node.js),C#,PHP","Ruby on Rails (Ruby),Spring (Java),Gin (Go)","Microsoft SQL Server,MySQL,Redis,Cassandra,Mon...","RESTful APIs,GraphQL","AWS,Google Cloud Platform,Microsoft Azure",Docker,"Selenium,Jasmine,Cypress,Jest,Appium"
36,36,TATA TECHNOLOGIES,LATUR,9106114823,tatatechnologies@internship.com,Yes,Work from Home,8.1,1,10,...,üì±Mobile App Development,NaN,"React Native,Xamarin","C#,Go,Java,PHP,Ruby,JavaScript (Node.js)","ASP.NET (C#),Flask (Python),Gin (Go),Ruby on R...","Oracle,MySQL,Cassandra,Couchbase,Microsoft SQL...",GraphQL,NaN,NaN,Appium
37,37,ICICI BANK,JAIPUR,9900374736,icicibank@internship.com,Yes,Work from office,7.3,10,6,...,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)","Xamarin,Flutter",NaN,"Laravel (PHP),Django (Python),Gin (Go),Ruby on...","PostgreSQL,Microsoft SQL Server,Redis,MySQL,Ca...","RESTful APIs,GraphQL",Microsoft Azure,"Docker,Kubernetes","Cypress,Selenium"
38,38,LOANTAP,LATUR,9889665941,loantap@internship.com,Yes,Work from Home,9.8,5,9,...,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)","Flutter,Xamarin",NaN,"Django (Python),Express.js (Node.js)","MySQL,MongoDB,Microsoft SQL Server,PostgreSQL",GraphQL,"AWS,Microsoft Azure,Google Cloud Platform",NaN,"Appium,Cypress,Mocha,Jest,Selenium"
39,39,GGS ENGINEERING SERVICES INDIA PVT.LTD,NASHIK,9284351177,ggsengineeringservicesindiapvt.ltd@internship.com,Yes,Work from Home,9.7,0,6,...,üì±Mobile App Development,Swift/Objective-C (iOS),NaN,"Java,Python,C#","Express.js (Node.js),Ruby on Rails (Ruby),Spri...",Redis,"GraphQL,RESTful APIs",NaN,NaN,"Cypress,Jest,Mocha,Selenium,Appium,Jasmine"
40,40,HDFC BANK,GUJARAT,9669236226,hdfcbank@internship.com,Yes,Work from Home,8.4,9,10,...,üì±Mobile App Development,Java (Android),"React Native,Xamarin,Flutter","JavaScript (Node.js),Ruby,Go,PHP,C#,Python","ASP.NET (C#),Flask (Python),Spring (Java),Lara...","PostgreSQL,MongoDB,MySQL",NaN,"AWS,Google Cloud Platform,Microsoft Azure",NaN,NaN
41,41,SAMSUNG R&D,WALCHAND,9728380771,samsungr&d@internship.com,Yes,Work from Home,8.6,5,7,...,üì±Mobile App Development,NaN,React Native,"Go,Python,C#,Java,JavaScript (Node.js),Ruby,PHP","Flask (Python),Ruby on Rails (Ruby),Spring (Ja...","Couchbase,Oracle,Cassandra,Redis,Microsoft SQL...",RESTful APIs,NaN,"Docker,Kubernetes","Jasmine,Selenium,Mocha,Jest,Appium"
42,42,DIVGI TORQ TRANSFER SYSTEMS LTD,HYDERABAD,9208035592,divgitorqtransfersystemsltd@internship.com,No,Work from office,9.4,10,4,...,üì±Mobile App Development,Swift/Objective-C (iOS),NaN,"JavaScript (Node.js),Ruby,C#","Spring (Java),Laravel (PHP),Express.js (Node.j...",NaN,NaN,"Google Cloud Platform,Microsoft Azure,AWS",Docker,"Appium,Jest,Mocha,Cypress"
43,43,BJYUS,CHENNAI,9228742236,bjyus@internship.com,Yes,Work from Home,7.5,3,6,...,üì±Mobile App Development,Java (Android),"Flutter,Xamarin,React Native","C#,Ruby,Java,Go,PHP,JavaScript (Node.js)","Flask (Python),Express.js (Node.js),Gin (Go),D...",NaN,"GraphQL,RESTful APIs",NaN,Kubernetes,NaN
44,44,09 SOLUTIONS,NAVI MUMBAI,9920554485,09solutions@internship.com,Yes,Work from office,7.6,10,9,...,üì±Mobile App Development,NaN,React Native,NaN,"Flask (Python),Laravel (PHP),Express.js (Node.js)","PostgreSQL,Couchbase,MongoDB,Oracle","GraphQL,RESTful APIs",NaN,"Docker,Kubernetes","Mocha,Appium,Jest"
45,45,BETSOL,NASHIK,9291147003,betsol@internship.com,Yes,Work from Home,9.0,4,10,...,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)",NaN,Python,"Django (Python),Laravel (PHP),Gin (Go),Flask (...","PostgreSQL,MongoDB,Cassandra,MySQL,Redis,Oracl...",NaN,Google Cloud Platform,"Docker,Kubernetes","Appium,Cypress,Mocha"
46,46,BES CONSULTANT PVT.LTD,JAPAN,9459808860,besconsultantpvt.ltd@internship.com,Yes,Work from Home,6.0,5,5,...,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)",React Native,"C#,JavaScript (Node.js),Python,Ruby,PHP",NaN,"Oracle,PostgreSQL,MongoDB,Cassandra",GraphQL,NaN,"Docker,Kubernetes",NaN
47,47,HEXAGON,NAVI MUMBAI,9808587237,hexagon@internship.com,Yes,Work from office,9.7,6,5,...,üì±Mobile App Development,"Java (Android),Swift/Objective-C (iOS)","Xamarin,Flutter","C#,Go,PHP,Java",NaN,"Couchbase,MySQL","GraphQL,RESTful APIs","Microsoft Azure,AWS",Docker,"Mocha,Selenium,Jasmine"
48,48,GAINSIGHT,KOLKATA,9290776301,gainsight@internship.com,No,Work from Home,6.9,3,2,...,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)","React Native,Flutter","PHP,Java,C#,Ruby","Ruby on Rails (Ruby),Express.js (Node.js),Djan...","MongoDB,Redis,PostgreSQL,MySQL,Oracle,Couchbas...","GraphQL,RESTful APIs",NaN,Kubernetes,"Appium,Jest"
49,49,PRECON SERVICES,JAIPUR,9061397729,preconservices@internship.com,Yes,Work from Home,6.3,0,6,...,üì±Mobile App Development,NaN,"React Native,Xamarin,Flutter",Java,NaN,NaN,NaN,"Microsoft Azure,Google Cloud Platform",NaN,"Selenium,Jest,Appium,Mocha,Jasmine,Cypress"
50,50,WIPRO TURBO HIRING,CHENNAI,9412348973,wiproturbohiring@internship.com,No,Work from office,8.4,5,9,...,üì±Mobile App Development,Java (Android),"Xamarin,React Native",Java,"Spring (Java),Ruby on Rails (Ruby),Django (Pyt...","Microsoft SQL Server,Cassandra,PostgreSQL,Orac...",RESTful APIs,"Google Cloud Platform,AWS","Kubernetes,Docker",NaN
51,51,AMERICAN AXLE MANUFACTURING INDIA PVT.LTD,PUNE,9435887339,americanaxlemanufacturingindiapvt.ltd@internsh...,Yes,Work from office,7.9,2,4,...,üì±Mobile App Development,Java (Android),"React Native,Flutter","Ruby,PHP","Gin (Go),Spring (Java),Express.js (Node.js),Dj...","PostgreSQL,Microsoft SQL Server,Cassandra,Orac...","GraphQL,RESTful APIs",NaN,Kubernetes,"Jasmine,Mocha"
52,52,EY INDIA,NASHIK,9847391715,eyindia@internship.com,No,Work from Home,8.4,7,3,...,üì±Mobile App Development,Java (Android),NaN,"Java,Ruby,Go,PHP,Python,C#",Express.js (Node.js),"Couchbase,MongoDB",NaN,NaN,"Docker,Kubernetes",Appium
53,53,PRECON SERVICES,GUJARAT,9381787191,preconservices@internship.com,Yes,Work from Home,9.3,0,5,...,üì±Mobile App Development,Swift/Objective-C (iOS),React Native,"C#,Ruby,PHP,Java,Python,Go,JavaScript (Node.js)","Ruby on Rails (Ruby),Express.js (Node.js),Djan...","Couchbase,PostgreSQL","GraphQL,RESTful APIs",NaN,NaN,"Selenium,Jest"
54,54,MG MOTOR,KOLKATA,9687015372,mgmotor@internship.com,Yes,Work from Home,8.5,2,6,...,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)","Flutter,Xamarin","Python,C#","Spring (Java),Express.js (Node.js),Django (Pyt...","MySQL,MongoDB,Cassandra,Redis,Oracle,Microsoft...",NaN,"AWS,Google Cloud Platform",Docker,"Jasmine,Jest"
55,55,CREDIT SUISSE,NAVI MUMBAI,9799229284,creditsuisse@internship.com,Yes,Work from office,7.5,9,4,...,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)","Flutter,React Native","PHP,JavaScript (Node.js),Ruby,Python,C#,Java","Spring (Java),ASP.NET (C#),Ruby on Rails (Ruby...",NaN,NaN,"Microsoft Azure,Google Cloud Platform,AWS","Kubernetes,Docker","Cypress,Jest,Jasmine,Selenium,Mocha,Appium"
56,56,FINIQ,GUJARAT,9819326787,finiq@internship.com,No,Work from Home,7.2,8,8,...,üì±Mobile App Development,"Java (Android),Swift/Objective-C (iOS)",React Native,"Ruby,Java","Laravel (PHP),Ruby on Rails (Ruby),Django (Pyt...",NaN,RESTful APIs,NaN,Kubernetes,NaN

In [8]:
modified_app_dev_df=app_dev_df.drop(['Unnamed: 0','Address of company', 'Phone Number',
       'Email Address', 'Previous Visited COEP'],axis=1)
modified_app_dev_df

,Name of company,Work Mode,Min CGPA,Seats for Boys,Seats for Girls,Number of Dead Backlogs permitted,Number of Active Backlogs permitted,Preffered month of visiting campus,Domain to Hire,Native Mobile App Development,Cross-Platform Mobile App Development,Backend Development Languages,Backend Development Frameworks,Databases for Apps,Web Services for App Development,Cloud Platform,Deployment of App,Testing of App
0,PIRAMAL,Work from office,7.8,7,6,0,2,October,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)","React Native,Xamarin","C#,Python,Go,PHP,Java","Flask (Python),Gin (Go),Express.js (Node.js),L...","MySQL,Cassandra,MongoDB,Oracle,Microsoft SQL S...",NaN,"Microsoft Azure,AWS,Google Cloud Platform",Docker,"Jest,Selenium,Jasmine,Mocha,Cypress,Appium"
1,UGAM SOLUTIONS,Work from Home,6.6,2,0,1,1,August,üì±Mobile App Development,"Java (Android),Swift/Objective-C (iOS)","Flutter,React Native,Xamarin","Java,Go,Python,JavaScript (Node.js),Ruby,C#","Laravel (PHP),Flask (Python),ASP.NET (C#),Spri...",NaN,"GraphQL,RESTful APIs",NaN,NaN,"Jasmine,Selenium,Jest,Mocha"
2,SOC GEN,Work from Home,7.7,4,4,0,0,December,üì±Mobile App Development,"Java (Android),Swift/Objective-C (iOS)",React Native,"Java,PHP,Python","Flask (Python),Express.js (Node.js),Django (Py...","Redis,MongoDB,Oracle,MySQL,Microsoft SQL Serve...",RESTful APIs,"Microsoft Azure,AWS,Google Cloud Platform",NaN,Appium
3,HINDUJA TECH LIMITED,Work from Home,9.9,9,10,2,2,Novermber,üì±Mobile App Development,NaN,NaN,"JavaScript (Node.js),C#","Laravel (PHP),Spring (Java),Express.js (Node.j...","MongoDB,Cassandra,Redis,Microsoft SQL Server,M...",NaN,AWS,"Docker,Kubernetes","Appium,Mocha"
4,TAVISCA,Work from Home,9.2,7,8,2,0,September,üì±Mobile App Development,Swift/Objective-C (iOS),"Xamarin,Flutter,React Native","C#,JavaScript (Node.js)","Ruby on Rails (Ruby),ASP.NET (C#),Django (Pyth...","Couchbase,MySQL",RESTful APIs,Google Cloud Platform,Docker,"Cypress,Jest"
5,WINJIT TECHNOLOGIES,Work from office,7.2,2,3,1,0,July,üì±Mobile App Development,Java (Android),"Flutter,React Native","C#,Java,Go,PHP","Spring (Java),Flask (Python),Laravel (PHP),Rub...",Cassandra,NaN,"Google Cloud Platform,AWS",NaN,"Jest,Jasmine,Cypress,Selenium,Appium,Mocha"
6,VISTEON,Work from office,7.7,1,9,0,2,December,üì±Mobile App Development,Swift/Objective-C (iOS),NaN,"Java,PHP,Ruby,C#","Ruby on Rails (Ruby),Flask (Python),ASP.NET (C...","Cassandra,MySQL,Couchbase,PostgreSQL,Redis,Mic...",NaN,AWS,NaN,Appium
7,TCS NINJA,Work from office,8.8,6,2,0,0,July,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)","React Native,Flutter","Java,Ruby,C#,Go","Gin (Go),ASP.NET (C#),Flask (Python),Express.j...","Cassandra,MongoDB,MySQL",GraphQL,Microsoft Azure,Kubernetes,"Cypress,Mocha,Jest,Appium,Selenium"
8,BAJAJ FINSERV,Work from Home,6.7,10,0,0,2,June,üì±Mobile App Development,NaN,React Native,"PHP,Java,Python","Express.js (Node.js),Ruby on Rails (Ruby),Spri...","Redis,Microsoft SQL Server,PostgreSQL,MySQL",NaN,"AWS,Microsoft Azure",Kubernetes,"Appium,Jest"
9,NUANCE,Work from office,8.3,7,6,1,0,July,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)",Xamarin,"JavaScript (Node.js),PHP,Go,Ruby",Express.js (Node.js),"Couchbase,Redis,Oracle,PostgreSQL",RESTful APIs,"Microsoft Azure,AWS",Docker,"Jasmine,Selenium,Jest"
10,ADOR WELDING,Work from Home,6.3,8,10,1,2,September,üì±Mobile App Development,Java (Android),Xamarin,"Python,JavaScript (Node.js),C#,Ruby","Spring (Java),Ruby on Rails (Ruby),Laravel (PH...","Couchbase,MongoDB,Redis,PostgreSQL,Microsoft S...",RESTful APIs,AWS,Kubernetes,Jest
11,EY INDIA,Work from office,6.0,0,1,1,2,July,üì±Mobile App Development,NaN,React Native,"C#,Go,Python","Ruby on Rails (Ruby),Flask (Python),Gin (Go),D...",NaN,NaN,Google Cloud Platform,"Kubernetes,Docker","Cypress,Selenium"
12,TEXAS INSTRUMENTS,Work from office,8.1,4,1,1,2,June,üì±Mobile App Development,"Java (Android),Swift/Objective-C (iOS)","Xamarin,React Native,Flutter","JavaScript (Node.js),C#,Ruby,PHP,Java,Go","Flask (Python),Laravel (PHP),Ruby on Rails (Ru...","PostgreSQL,Microsoft SQL Server",NaN,"Microsoft Azure,Google Cloud Platform",Docker,"Jest,Selenium,Jasmine,Cypress,Mocha,Appium"
13,SIEMENS LIMITED COBRA,Work from Home,6.5,1,10,2,2,July,üì±Mobile App Development,NaN,"Flutter,Xamarin,React Native","Java,Python,JavaScript (Node.js),Ruby","Ruby on Rails (Ruby),Express.js (Node.js),Lara...","Microsoft SQL Server,Couchbase",NaN,"Google Cloud Platform,Microsoft Azure","Docker,Kubernetes","Mocha,Jasmine,Jest,Selenium,Appium,Cypress"
14,EY INDIA,Work from office,8.5,6,0,0,0,Novermber,üì±Mobile App Development,"Java (Android),Swift/Objective-C (iOS)","Flutter,Xamarin,React Native","Ruby,Python",NaN,"Couchbase,Oracle","RESTful APIs,GraphQL",NaN,"Kubernetes,Docker","Appium,Cypress,Mocha,Selenium"
15,CREDIT SUISSE,Work from office,8.3,7,5,2,0,August,üì±Mobile App Development,NaN,"Xamarin,Flutter,React Native","Java,C#,Go,PHP,Python","ASP.NET (C#),Django (Python),Gin (Go),Ruby on ...","MongoDB,Oracle",NaN,Google Cloud Platform,"Kubernetes,Docker",NaN
16,MG MOTOR,Work from Home,8.0,3,1,1,0,July,üì±Mobile App Development,Swift/Objective-C (iOS),NaN,"PHP,JavaScript (Node.js),C#,Ruby,Java,Python","Spring (Java),ASP.NET (C#),Gin (Go)","Redis,Couchbase,MySQL,PostgreSQL",NaN,NaN,"Docker,Kubernetes","Selenium,Jasmine,Jest"
17,ADITYA BIRLA GROUP,Work from Home,6.1,6,10,2,0,December,üì±Mobile App Development,NaN,NaN,"Ruby,C#,Java,PHP","Spring (Java),Flask (Python),Laravel (PHP),Gin...",MySQL,NaN,Microsoft Azure,"Docker,Kubernetes",NaN
18,TVS MOTOR,Work from office,9.6,7,7,0,0,December,üì±Mobile App Development,Java (Android),NaN,"C#,Java,PHP,JavaScript (Node.js),Python,Go","Express.js (Node.js),Flask (Python),Gin (Go),S...","Oracle,PostgreSQL","GraphQL,RESTful APIs",AWS,Kubernetes,"Mocha,Jasmine"
19,ADITYA BIRLA GROUP,Work from office,9.9,3,1,0,2,Novermber,üì±Mobile App Development,NaN,Flutter,NaN,"Laravel (PHP),Express.js (Node.js),Spring (Jav...","MySQL,Couchbase,Microsoft SQL Server,Oracle,Mo...",RESTful APIs,NaN,Kubernetes,"Cypress,Selenium,Mocha,Jasmine,Appium"
20,WINJIT TECHNOLOGIES,Work from Home,8.9,1,7,1,2,October,üì±Mobile App Development,NaN,React Native,"Go,C#","Gin (Go),Flask (Python),Laravel (PHP),Express....","Redis,Microsoft SQL Server,Couchbase,Cassandra","RESTful APIs,GraphQL","AWS,Microsoft Azure",Kubernetes,"Jasmine,Jest,Selenium,Appium,Mocha,Cypress"
21,SEDEMAC,Work from Home,7.1,2,0,0,2,October,üì±Mobile App Development,NaN,NaN,NaN,"Gin (Go),Laravel (PHP),Ruby on Rails (Ruby),Sp...","Microsoft SQL Server,Redis,MySQL,Couchbase,Mon...",NaN,"Microsoft Azure,Google Cloud Platform","Kubernetes,Docker","Cypress,Jest,Appium,Mocha"
22,AMERICAN AXLE MANUFACTURING INDIA PVT.LTD,Work from office,6.3,1,10,0,0,June,üì±Mobile App Development,Java (Android),"React Native,Xamarin,Flutter",NaN,ASP.NET (C#),NaN,RESTful APIs,AWS,NaN,NaN
23,GODREJ & BOYCE,Work from office,9.1,10,7,0,1,October,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)",Xamarin,"Go,PHP","Ruby on Rails (Ruby),Express.js (Node.js),ASP....","Couchbase,Microsoft SQL Server,Cassandra",NaN,Microsoft Azure,NaN,"Jasmine,Cypress"
24,EMERSON EXPORTS ENGINEERING CENTER,Work from office,9.0,7,9,1,0,December,üì±Mobile App Development,NaN,Xamarin,"Python,PHP,Ruby","Spring (Java),ASP.NET (C#),Gin (Go)",Oracle,RESTful APIs,NaN,Kubernetes,"Selenium,Cypress,Mocha,Jasmine"
25,SAARLOHA ADVANCE MATERIALS,Work from office,6.9,9,10,0,2,August,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)","React Native,Xamarin,Flutter","Java,Python,JavaScript (Node.js),C#,Ruby","Spring (Java),Django (Python),Ruby on Rails (R...","Microsoft SQL Server,Cassandra","RESTful APIs,GraphQL","AWS,Microsoft Azure","Kubernetes,Docker","Jest,Jasmine"
26,SEDEMAC,Work from office,7.6,10,6,1,0,June,üì±Mobile App Development,NaN,Xamarin,Python,"ASP.NET (C#),Django (Python),Spring (Java),Gin...","Redis,PostgreSQL,Cassandra",RESTful APIs,Microsoft Azure,"Docker,Kubernetes","Selenium,Appium,Cypress,Jasmine,Jest"
27,LG ELECTRONICS,Work from office,8.0,1,10,0,2,Novermber,üì±Mobile App Development,NaN,"Flutter,React Native,Xamarin","Python,PHP,Ruby,JavaScript (Node.js),C#,Java,Go","ASP.NET (C#),Flask (Python)","PostgreSQL,Couchbase,Microsoft SQL Server,Oracle","GraphQL,RESTful APIs",NaN,NaN,"Jest,Mocha"
28,BAJAJ AUTO,Work from Home,7.8,3,9,1,1,October,üì±Mobile App Development,Java (Android),"Xamarin,Flutter,React Native","PHP,Ruby,JavaScript (Node.js)",Express.js (Node.js),"Cassandra,Oracle,Couchbase,Redis,MySQL,Microso...","RESTful APIs,GraphQL","Google Cloud Platform,Microsoft Azure,AWS",NaN,NaN
29,TATA AUTOCOMP SYSTEMS,Work from office,6.2,6,0,0,0,July,üì±Mobile App Development,NaN,"React Native,Flutter",C#,"Django (Python),Spring (Java),Express.js (Node...","Microsoft SQL Server,MySQL,PostgreSQL,Oracle,C...",NaN,NaN,NaN,"Cypress,Selenium,Appium"
30,OLA ELECTRIC,Work from office,6.3,9,0,2,0,October,üì±Mobile App Development,NaN,"Flutter,React Native,Xamarin",JavaScript (Node.js),NaN,"Cassandra,Microsoft SQL Server,PostgreSQL,Oracle",GraphQL,"Google Cloud Platform,AWS",NaN,"Cypress,Mocha"
31,MERCEDES BENZ,Work from Home,8.4,0,6,2,1,December,üì±Mobile App Development,"Java (Android),Swift/Objective-C (iOS)","React Native,Xamarin",NaN,"Laravel (PHP),Express.js (Node.js)","Couchbase,MySQL,MongoDB,Oracle,Cassandra","GraphQL,RESTful APIs",Microsoft Azure,NaN,"Cypress,Jasmine,Jest,Selenium,Appium"
32,TATA STEEL DOWNSTREAM PRODUCTS LTD,Work from office,8.9,3,0,2,2,September,üì±Mobile App Development,NaN,Flutter,"Go,C#,JavaScript (Node.js)","Ruby on Rails (Ruby),Express.js (Node.js),Gin ...","Redis,MySQL",NaN,NaN,Kubernetes,"Cypress,Selenium,Mocha"
33,WALCHAND INDUSTRIES,Work from Home,6.4,2,9,1,2,June,üì±Mobile App Development,NaN,Flutter,NaN,"Gin (Go),Laravel (PHP),Flask (Python),Django (...","MySQL,PostgreSQL,Couchbase,Microsoft SQL Server","GraphQL,RESTful APIs","AWS,Microsoft Azure",Kubernetes,NaN
34,BROSE INDIA,Work from office,9.2,3,1,2,0,July,üì±Mobile App Development,Java (Android),Xamarin,"Go,C#","Spring (Java),ASP.NET (C#),Laravel (PHP),Ruby ...",Redis,NaN,"AWS,Microsoft Azure",NaN,"Mocha,Appium,Jasmine,Jest,Cypress"
35,GAINSIGHT,Work from office,7.7,10,5,1,1,October,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)","Xamarin,Flutter","Ruby,Python,Go,Java,JavaScript (Node.js),C#,PHP","Ruby on Rails (Ruby),Spring (Java),Gin (Go)","Microsoft SQL Server,MySQL,Redis,Cassandra,Mon...","RESTful APIs,GraphQL","AWS,Google Cloud Platform,Microsoft Azure",Docker,"Selenium,Jasmine,Cypress,Jest,Appium"
36,TATA TECHNOLOGIES,Work from Home,8.1,1,10,2,1,July,üì±Mobile App Development,NaN,"React Native,Xamarin","C#,Go,Java,PHP,Ruby,JavaScript (Node.js)","ASP.NET (C#),Flask (Python),Gin (Go),Ruby on R...","Oracle,MySQL,Cassandra,Couchbase,Microsoft SQL...",GraphQL,NaN,NaN,Appium
37,ICICI BANK,Work from office,7.3,10,6,2,2,October,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)","Xamarin,Flutter",NaN,"Laravel (PHP),Django (Python),Gin (Go),Ruby on...","PostgreSQL,Microsoft SQL Server,Redis,MySQL,Ca...","RESTful APIs,GraphQL",Microsoft Azure,"Docker,Kubernetes","Cypress,Selenium"
38,LOANTAP,Work from Home,9.8,5,9,0,0,August,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)","Flutter,Xamarin",NaN,"Django (Python),Express.js (Node.js)","MySQL,MongoDB,Microsoft SQL Server,PostgreSQL",GraphQL,"AWS,Microsoft Azure,Google Cloud Platform",NaN,"Appium,Cypress,Mocha,Jest,Selenium"
39,GGS ENGINEERING SERVICES INDIA PVT.LTD,Work from Home,9.7,0,6,2,1,Novermber,üì±Mobile App Development,Swift/Objective-C (iOS),NaN,"Java,Python,C#","Express.js (Node.js),Ruby on Rails (Ruby),Spri...",Redis,"GraphQL,RESTful APIs",NaN,NaN,"Cypress,Jest,Mocha,Selenium,Appium,Jasmine"
40,HDFC BANK,Work from Home,8.4,9,10,2,1,December,üì±Mobile App Development,Java (Android),"React Native,Xamarin,Flutter","JavaScript (Node.js),Ruby,Go,PHP,C#,Python","ASP.NET (C#),Flask (Python),Spring (Java),Lara...","PostgreSQL,MongoDB,MySQL",NaN,"AWS,Google Cloud Platform,Microsoft Azure",NaN,NaN
41,SAMSUNG R&D,Work from Home,8.6,5,7,2,0,July,üì±Mobile App Development,NaN,React Native,"Go,Python,C#,Java,JavaScript (Node.js),Ruby,PHP","Flask (Python),Ruby on Rails (Ruby),Spring (Ja...","Couchbase,Oracle,Cassandra,Redis,Microsoft SQL...",RESTful APIs,NaN,"Docker,Kubernetes","Jasmine,Selenium,Mocha,Jest,Appium"
42,DIVGI TORQ TRANSFER SYSTEMS LTD,Work from office,9.4,10,4,2,2,September,üì±Mobile App Development,Swift/Objective-C (iOS),NaN,"JavaScript (Node.js),Ruby,C#","Spring (Java),Laravel (PHP),Express.js (Node.j...",NaN,NaN,"Google Cloud Platform,Microsoft Azure,AWS",Docker,"Appium,Jest,Mocha,Cypress"
43,BJYUS,Work from Home,7.5,3,6,1,1,October,üì±Mobile App Development,Java (Android),"Flutter,Xamarin,React Native","C#,Ruby,Java,Go,PHP,JavaScript (Node.js)","Flask (Python),Express.js (Node.js),Gin (Go),D...",NaN,"GraphQL,RESTful APIs",NaN,Kubernetes,NaN
44,09 SOLUTIONS,Work from office,7.6,10,9,1,2,October,üì±Mobile App Development,NaN,React Native,NaN,"Flask (Python),Laravel (PHP),Express.js (Node.js)","PostgreSQL,Couchbase,MongoDB,Oracle","GraphQL,RESTful APIs",NaN,"Docker,Kubernetes","Mocha,Appium,Jest"
45,BETSOL,Work from Home,9.0,4,10,0,0,June,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)",NaN,Python,"Django (Python),Laravel (PHP),Gin (Go),Flask (...","PostgreSQL,MongoDB,Cassandra,MySQL,Redis,Oracl...",NaN,Google Cloud Platform,"Docker,Kubernetes","Appium,Cypress,Mocha"
46,BES CONSULTANT PVT.LTD,Work from Home,6.0,5,5,1,0,June,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)",React Native,"C#,JavaScript (Node.js),Python,Ruby,PHP",NaN,"Oracle,PostgreSQL,MongoDB,Cassandra",GraphQL,NaN,"Docker,Kubernetes",NaN
47,HEXAGON,Work from office,9.7,6,5,0,2,July,üì±Mobile App Development,"Java (Android),Swift/Objective-C (iOS)","Xamarin,Flutter","C#,Go,PHP,Java",NaN,"Couchbase,MySQL","GraphQL,RESTful APIs","Microsoft Azure,AWS",Docker,"Mocha,Selenium,Jasmine"
48,GAINSIGHT,Work from Home,6.9,3,2,2,0,December,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)","React Native,Flutter","PHP,Java,C#,Ruby","Ruby on Rails (Ruby),Express.js (Node.js),Djan...","MongoDB,Redis,PostgreSQL,MySQL,Oracle,Couchbas...","GraphQL,RESTful APIs",NaN,Kubernetes,"Appium,Jest"
49,PRECON SERVICES,Work from Home,6.3,0,6,0,1,June,üì±Mobile App Development,NaN,"React Native,Xamarin,Flutter",Java,NaN,NaN,NaN,"Microsoft Azure,Google Cloud Platform",NaN,"Selenium,Jest,Appium,Mocha,Jasmine,Cypress"
50,WIPRO TURBO HIRING,Work from office,8.4,5,9,0,1,October,üì±Mobile App Development,Java (Android),"Xamarin,React Native",Java,"Spring (Java),Ruby on Rails (Ruby),Django (Pyt...","Microsoft SQL Server,Cassandra,PostgreSQL,Orac...",RESTful APIs,"Google Cloud Platform,AWS","Kubernetes,Docker",NaN
51,AMERICAN AXLE MANUFACTURING INDIA PVT.LTD,Work from office,7.9,2,4,2,2,October,üì±Mobile App Development,Java (Android),"React Native,Flutter","Ruby,PHP","Gin (Go),Spring (Java),Express.js (Node.js),Dj...","PostgreSQL,Microsoft SQL Server,Cassandra,Orac...","GraphQL,RESTful APIs",NaN,Kubernetes,"Jasmine,Mocha"
52,EY INDIA,Work from Home,8.4,7,3,0,1,July,üì±Mobile App Development,Java (Android),NaN,"Java,Ruby,Go,PHP,Python,C#",Express.js (Node.js),"Couchbase,MongoDB",NaN,NaN,"Docker,Kubernetes",Appium
53,PRECON SERVICES,Work from Home,9.3,0,5,1,0,Novermber,üì±Mobile App Development,Swift/Objective-C (iOS),React Native,"C#,Ruby,PHP,Java,Python,Go,JavaScript (Node.js)","Ruby on Rails (Ruby),Express.js (Node.js),Djan...","Couchbase,PostgreSQL","GraphQL,RESTful APIs",NaN,NaN,"Selenium,Jest"
54,MG MOTOR,Work from Home,8.5,2,6,1,1,December,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)","Flutter,Xamarin","Python,C#","Spring (Java),Express.js (Node.js),Django (Pyt...","MySQL,MongoDB,Cassandra,Redis,Oracle,Microsoft...",NaN,"AWS,Google Cloud Platform",Docker,"Jasmine,Jest"
55,CREDIT SUISSE,Work from office,7.5,9,4,0,1,September,üì±Mobile App Development,"Swift/Objective-C (iOS),Java (Android)","Flutter,React Native","PHP,JavaScript (Node.js),Ruby,Python,C#,Java","Spring (Java),ASP.NET (C#),Ruby on Rails (Ruby...",NaN,NaN,"Microsoft Azure,Google Cloud Platform,AWS","Kubernetes,Docker","Cypress,Jest,Jasmine,Selenium,Mocha,Appium"
56,FINIQ,Work from Home,7.2,8,8,1,2,December,üì±Mobile App Development,"Java (Android),Swift/Objective-C (iOS)",React Native,"Ruby,Java","Laravel (PHP),Ruby on Rails (Ruby),Django (Pyt...",NaN,RESTful APIs,NaN,Kubernetes,NaN

In [9]:
modified_app_dev_df.to_csv("~\Desktop\RPOOPS\Mini Project\Part_B\Final_Data\Final_app_dev_data.csv")

In [10]:
data_sci_df=pd.read_csv("~\Desktop\RPOOPS\Mini Project\Part_B\Raw_Data_Generated\Raw_data_sci_data.csv")
data_sci_df

,Unnamed: 0,Name of company,Address of company,Phone Number,Email Address,Previous Visited COEP,Work Mode,Min CGPA,Seats for Boys,Seats for Girls,Number of Dead Backlogs permitted,Number of Active Backlogs permitted,Preffered month of visiting campus,Domain to Hire,Data Collection and Storage,Data Cleaning and Preprocessing,Data Visualization,Statistical Analysis,Business Intelligence (BI),Data Warehousing
0,0,TCS R&I,PUNE,9563932087,tcsr&i@internship.com,Yes,Work from office,9.4,1,3,0,0,October,üìàData Science and Analytics,NaN,Tidyverse,ggplot2 in R,"SAS,Data.table,SPSS,Tidyverse,Base R","Oracle BI,IBM Cognos,SAP BusinessObjects","Microsoft SQL Server,Snowflake,Amazon Redshift"
1,1,ION GROUP,JAPAN,9512647521,iongroup@internship.com,No,Work from office,7.0,3,9,2,1,December,üìàData Science and Analytics,"MLlib,MongoDB,Spark Streaming,HBase,GraphX,Cas...","Tidyverse,Scikit-learn",NaN,Tidyverse,"IBM Cognos,Oracle BI",NaN
2,2,PIRAMAL,NOIDA,9507691664,piramal@internship.com,No,Work from office,8.3,8,1,1,2,August,üìàData Science and Analytics,"YARN,HDFS,HBase,MapReduce,Redis,Cassandra,Spar...","Pandas,OpenRefine,NumPy",NaN,"Base R,Data.table,SPSS,SAS",NaN,NaN
3,3,SKF ENGINEERING AND LUBRICATION INDIA,AURANGABAD,9271008742,skfengineeringandlubricationindia@internship.com,No,Work from office,9.0,10,4,0,2,August,üìàData Science and Analytics,"MapReduce,Hive,Cassandra,Redis,HBase,Spark SQL...","NumPy,Dplyr,Pandas,Scikit-learn",NaN,"SPSS,Tidyverse,SAS,Data.table",Oracle BI,"Microsoft SQL Server,Amazon Redshift,Snowflake"
4,4,DAR GROUP,NOIDA,9653528859,dargroup@internship.com,No,Work from office,8.1,10,10,2,0,July,üìàData Science and Analytics,NaN,"Tidyverse,OpenRefine,Pandas",Tableau,"Base R,Data.table,Tidyverse",NaN,"Snowflake,Amazon Redshift,Microsoft SQL Server"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,63,HIGHWAY 9 NETWORKS,CHENNAI,9368242410,highway9networks@internship.com,Yes,Work from Home,9.2,4,2,1,2,September,üìàData Science and Analytics,"YARN,Spark Streaming,Hive,Cassandra,MapReduce","NumPy,Scikit-learn,Pandas,Data.table,Dplyr,Tid...",Tableau,"Base R,SAS,Tidyverse,Data.table,SPSS","Oracle BI,SAP BusinessObjects,IBM Cognos","Snowflake,Amazon Redshift,Microsoft SQL Server"
64,64,ZENSAR,NASHIK,9367673773,zensar@internship.com,Yes,Work from Home,7.5,9,6,0,2,Novermber,üìàData Science and Analytics,"Hive,MongoDB,HDFS,HBase,YARN,Cassandra,Spark SQL","Scikit-learn,Pandas,OpenRefine,NumPy,Dplyr,Tid...","Tableau,ggplot2 in R",NaN,"Oracle BI,IBM Cognos",NaN
65,65,DANA INDIA,CHENNAI,9951894536,danaindia@internship.com,Yes,Work from office,8.2,10,6,0,2,October,üìàData Science and Analytics,"Spark Streaming,Redis,HBase,MongoDB,Cassandra,...","Data.table,NumPy,Dplyr",PowerBI,Data.table,"SAP BusinessObjects,IBM Cognos,Oracle BI","Amazon Redshift,Microsoft SQL Server,Snowflake"
66,66,SIEMENS LIMITED,JAIPUR,9419882859,siemenslimited@internship.com,Yes,Work from office,9.9,9,0,2,0,September,üìàData Science and Analytics,"Cassandra,Spark Streaming,Spark SQL,HBase,YARN...","OpenRefine,Data.table,Pandas",NaN,"Data.table,SAS,Base R","SAP BusinessObjects,IBM Cognos,Oracle BI","Snowflake,Microsoft SQL Server,Amazon Redshift"
67,67,TCS XPLORE,KOLKATA,9315057670,tcsxplore@internship.com,No,Work from office,8.1,3,4,1,0,October,üìàData Science and Analytics,"Hive,Spark SQL,MapReduce",NaN,"Tableau,ggplot2 in R,PowerBI","SAS,Base R,SPSS,Tidyverse,Data.table","SAP BusinessObjects,IBM Cognos",Snowflake

In [11]:
modified_data_sci_df=data_sci_df.drop(['Unnamed: 0','Address of company', 'Phone Number',
       'Email Address', 'Previous Visited COEP'],axis=1)
modified_data_sci_df

,Name of company,Work Mode,Min CGPA,Seats for Boys,Seats for Girls,Number of Dead Backlogs permitted,Number of Active Backlogs permitted,Preffered month of visiting campus,Domain to Hire,Data Collection and Storage,Data Cleaning and Preprocessing,Data Visualization,Statistical Analysis,Business Intelligence (BI),Data Warehousing
0,TCS R&I,Work from office,9.4,1,3,0,0,October,üìàData Science and Analytics,NaN,Tidyverse,ggplot2 in R,"SAS,Data.table,SPSS,Tidyverse,Base R","Oracle BI,IBM Cognos,SAP BusinessObjects","Microsoft SQL Server,Snowflake,Amazon Redshift"
1,ION GROUP,Work from office,7.0,3,9,2,1,December,üìàData Science and Analytics,"MLlib,MongoDB,Spark Streaming,HBase,GraphX,Cas...","Tidyverse,Scikit-learn",NaN,Tidyverse,"IBM Cognos,Oracle BI",NaN
2,PIRAMAL,Work from office,8.3,8,1,1,2,August,üìàData Science and Analytics,"YARN,HDFS,HBase,MapReduce,Redis,Cassandra,Spar...","Pandas,OpenRefine,NumPy",NaN,"Base R,Data.table,SPSS,SAS",NaN,NaN
3,SKF ENGINEERING AND LUBRICATION INDIA,Work from office,9.0,10,4,0,2,August,üìàData Science and Analytics,"MapReduce,Hive,Cassandra,Redis,HBase,Spark SQL...","NumPy,Dplyr,Pandas,Scikit-learn",NaN,"SPSS,Tidyverse,SAS,Data.table",Oracle BI,"Microsoft SQL Server,Amazon Redshift,Snowflake"
4,DAR GROUP,Work from office,8.1,10,10,2,0,July,üìàData Science and Analytics,NaN,"Tidyverse,OpenRefine,Pandas",Tableau,"Base R,Data.table,Tidyverse",NaN,"Snowflake,Amazon Redshift,Microsoft SQL Server"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,HIGHWAY 9 NETWORKS,Work from Home,9.2,4,2,1,2,September,üìàData Science and Analytics,"YARN,Spark Streaming,Hive,Cassandra,MapReduce","NumPy,Scikit-learn,Pandas,Data.table,Dplyr,Tid...",Tableau,"Base R,SAS,Tidyverse,Data.table,SPSS","Oracle BI,SAP BusinessObjects,IBM Cognos","Snowflake,Amazon Redshift,Microsoft SQL Server"
64,ZENSAR,Work from Home,7.5,9,6,0,2,Novermber,üìàData Science and Analytics,"Hive,MongoDB,HDFS,HBase,YARN,Cassandra,Spark SQL","Scikit-learn,Pandas,OpenRefine,NumPy,Dplyr,Tid...","Tableau,ggplot2 in R",NaN,"Oracle BI,IBM Cognos",NaN
65,DANA INDIA,Work from office,8.2,10,6,0,2,October,üìàData Science and Analytics,"Spark Streaming,Redis,HBase,MongoDB,Cassandra,...","Data.table,NumPy,Dplyr",PowerBI,Data.table,"SAP BusinessObjects,IBM Cognos,Oracle BI","Amazon Redshift,Microsoft SQL Server,Snowflake"
66,SIEMENS LIMITED,Work from office,9.9,9,0,2,0,September,üìàData Science and Analytics,"Cassandra,Spark Streaming,Spark SQL,HBase,YARN...","OpenRefine,Data.table,Pandas",NaN,"Data.table,SAS,Base R","SAP BusinessObjects,IBM Cognos,Oracle BI","Snowflake,Microsoft SQL Server,Amazon Redshift"
67,TCS XPLORE,Work from office,8.1,3,4,1,0,October,üìàData Science and Analytics,"Hive,Spark SQL,MapReduce",NaN,"Tableau,ggplot2 in R,PowerBI","SAS,Base R,SPSS,Tidyverse,Data.table","SAP BusinessObjects,IBM Cognos",Snowflake

In [12]:
modified_data_sci_df.to_csv("~\Desktop\RPOOPS\Mini Project\Part_B\Final_Data\Final_data_sci_data.csv")

In [13]:
aiml_df=pd.read_csv("~\Desktop\RPOOPS\Mini Project\Part_B\Raw_Data_Generated\Raw_aiml_data.csv")
aiml_df

,Unnamed: 0,Name of company,Address of company,Phone Number,Email Address,Previous Visited COEP,Work Mode,Min CGPA,Seats for Boys,Seats for Girls,Number of Dead Backlogs permitted,Number of Active Backlogs permitted,Preffered month of visiting campus,Domain to Hire,Natural Language Processing (NLP),Computer Vision,Deep Learning,Machine Learning,Robotics
0,0,TATA STEEL DOWNSTREAM PRODUCTS LTD,HARYANA,9512941364,tatasteeldownstreamproductsltd@internship.com,Yes,Work from office,9.9,2,5,1,2,December,üß†Artificial Intelligence and Machine Learning,"Natural Language Toolkit (NLTK),spaCy,Microsof...","Detectron2,Mask R-CNN,YOLO,OpenCV,PyTorch",Keras,"H2O.ai,Weka,XGBoost,R,Scikit-learn",PyBullet
1,1,HERO MOTOCORP,GURGAON,9052929263,heromotocorp@internship.com,Yes,Work from office,8.0,5,0,2,0,September,üß†Artificial Intelligence and Machine Learning,"AllenNLP,Stanford NLP,Natural Language Toolkit...","OpenCV,TensorFlow,Mask R-CNN","MXNet,Caffe,Keras",XGBoost,"TensorFlow Robotics,RoboFlow,Robot Operating S..."
2,2,V CONSTRUCT,KOLKATA,9717389691,vconstruct@internship.com,Yes,Work from office,9.4,8,10,0,0,July,üß†Artificial Intelligence and Machine Learning,"Natural Language Toolkit (NLTK),Google Cloud N...","Detectron2,Mask R-CNN,TensorFlow,OpenCV,PyTorc...","MXNet,PyTorch",RapidMiner,"RoboFlow,ROS 2,TensorFlow Robotics,Gazebo,PyBu..."
3,3,WHIRLPOOL INDIA,GURGAON,9826045432,whirlpoolindia@internship.com,No,Work from office,8.7,8,8,0,0,December,üß†Artificial Intelligence and Machine Learning,NaN,"Detectron2,YOLO","ONNX,MXNet","XGBoost,Scikit-learn,H2O.ai,Weka,R,RapidMiner",NaN
4,4,GOOGLE,NASHIK,9063879689,google@internship.com,No,Work from Home,6.4,1,2,2,0,July,üß†Artificial Intelligence and Machine Learning,NaN,NaN,"Caffe,PyTorch,MXNet,ONNX,Keras,TensorFlow","R,RapidMiner,H2O.ai,Weka,XGBoost,Scikit-learn",ROS 2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,68,CREDIT SUISSE,NASHIK,9873472999,creditsuisse@internship.com,No,Work from office,6.5,2,7,2,1,July,üß†Artificial Intelligence and Machine Learning,"AllenNLP,Microsoft Cognitive Services","Mask R-CNN,Detectron2,YOLO","PyTorch,ONNX","RapidMiner,Weka,Scikit-learn,H2O.ai","RoboFlow,PyBullet,Robot Operating System (ROS)"
69,69,INFOGEN LABS,GUJARAT,9569517579,infogenlabs@internship.com,Yes,Work from Home,9.6,9,5,2,1,June,üß†Artificial Intelligence and Machine Learning,NaN,NaN,"Caffe,PyTorch,ONNX","Scikit-learn,R,H2O.ai","PyBullet,RoboFlow,Gazebo,TensorFlow Robotics,R..."
70,70,SIEMENS LIMITED,HYDERABAD,9203040714,siemenslimited@internship.com,Yes,Work from office,7.5,5,2,0,1,June,üß†Artificial Intelligence and Machine Learning,"spaCy,AllenNLP","OpenCV,Detectron2","ONNX,Caffe","RapidMiner,H2O.ai,XGBoost,Scikit-learn","TensorFlow Robotics,RoboFlow,PyBullet,Gazebo,R..."
71,71,AKZONOBEL,AHMEDABAD,9435696117,akzonobel@internship.com,Yes,Work from Home,9.0,0,8,0,0,August,üß†Artificial Intelligence and Machine Learning,"AllenNLP,Google Cloud Natural Language API,Sta...","PyTorch,YOLO,Mask R-CNN,OpenCV",Keras,NaN,NaN
72,72,BETSOL,CHENNAI,9561030266,betsol@internship.com,Yes,Work from office,9.7,2,9,2,0,August,üß†Artificial Intelligence and Machine Learning,"AllenNLP,spaCy,Google Cloud Natural Language A...",NaN,"Keras,ONNX,Caffe","R,Scikit-learn","PyBullet,ROS 2,Robot Operating System (ROS),Te..."

In [14]:
modified_aiml_df=aiml_df.drop(['Unnamed: 0','Address of company', 'Phone Number',
       'Email Address', 'Previous Visited COEP'],axis=1)
modified_aiml_df

,Name of company,Work Mode,Min CGPA,Seats for Boys,Seats for Girls,Number of Dead Backlogs permitted,Number of Active Backlogs permitted,Preffered month of visiting campus,Domain to Hire,Natural Language Processing (NLP),Computer Vision,Deep Learning,Machine Learning,Robotics
0,TATA STEEL DOWNSTREAM PRODUCTS LTD,Work from office,9.9,2,5,1,2,December,üß†Artificial Intelligence and Machine Learning,"Natural Language Toolkit (NLTK),spaCy,Microsof...","Detectron2,Mask R-CNN,YOLO,OpenCV,PyTorch",Keras,"H2O.ai,Weka,XGBoost,R,Scikit-learn",PyBullet
1,HERO MOTOCORP,Work from office,8.0,5,0,2,0,September,üß†Artificial Intelligence and Machine Learning,"AllenNLP,Stanford NLP,Natural Language Toolkit...","OpenCV,TensorFlow,Mask R-CNN","MXNet,Caffe,Keras",XGBoost,"TensorFlow Robotics,RoboFlow,Robot Operating S..."
2,V CONSTRUCT,Work from office,9.4,8,10,0,0,July,üß†Artificial Intelligence and Machine Learning,"Natural Language Toolkit (NLTK),Google Cloud N...","Detectron2,Mask R-CNN,TensorFlow,OpenCV,PyTorc...","MXNet,PyTorch",RapidMiner,"RoboFlow,ROS 2,TensorFlow Robotics,Gazebo,PyBu..."
3,WHIRLPOOL INDIA,Work from office,8.7,8,8,0,0,December,üß†Artificial Intelligence and Machine Learning,NaN,"Detectron2,YOLO","ONNX,MXNet","XGBoost,Scikit-learn,H2O.ai,Weka,R,RapidMiner",NaN
4,GOOGLE,Work from Home,6.4,1,2,2,0,July,üß†Artificial Intelligence and Machine Learning,NaN,NaN,"Caffe,PyTorch,MXNet,ONNX,Keras,TensorFlow","R,RapidMiner,H2O.ai,Weka,XGBoost,Scikit-learn",ROS 2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,CREDIT SUISSE,Work from office,6.5,2,7,2,1,July,üß†Artificial Intelligence and Machine Learning,"AllenNLP,Microsoft Cognitive Services","Mask R-CNN,Detectron2,YOLO","PyTorch,ONNX","RapidMiner,Weka,Scikit-learn,H2O.ai","RoboFlow,PyBullet,Robot Operating System (ROS)"
69,INFOGEN LABS,Work from Home,9.6,9,5,2,1,June,üß†Artificial Intelligence and Machine Learning,NaN,NaN,"Caffe,PyTorch,ONNX","Scikit-learn,R,H2O.ai","PyBullet,RoboFlow,Gazebo,TensorFlow Robotics,R..."
70,SIEMENS LIMITED,Work from office,7.5,5,2,0,1,June,üß†Artificial Intelligence and Machine Learning,"spaCy,AllenNLP","OpenCV,Detectron2","ONNX,Caffe","RapidMiner,H2O.ai,XGBoost,Scikit-learn","TensorFlow Robotics,RoboFlow,PyBullet,Gazebo,R..."
71,AKZONOBEL,Work from Home,9.0,0,8,0,0,August,üß†Artificial Intelligence and Machine Learning,"AllenNLP,Google Cloud Natural Language API,Sta...","PyTorch,YOLO,Mask R-CNN,OpenCV",Keras,NaN,NaN
72,BETSOL,Work from office,9.7,2,9,2,0,August,üß†Artificial Intelligence and Machine Learning,"AllenNLP,spaCy,Google Cloud Natural Language A...",NaN,"Keras,ONNX,Caffe","R,Scikit-learn","PyBullet,ROS 2,Robot Operating System (ROS),Te..."

In [15]:
modified_aiml_df.to_csv("~\Desktop\RPOOPS\Mini Project\Part_B\Final_Data\Final_aiml_data.csv")

In [16]:
cloud_df=pd.read_csv("~\Desktop\RPOOPS\Mini Project\Part_B\Raw_Data_Generated\Raw_cloud_data.csv")
cloud_df

,Unnamed: 0,Name of company,Address of company,Phone Number,Email Address,Previous Visited COEP,Work Mode,Min CGPA,Seats for Boys,Seats for Girls,...,Cloud Infrastructure Programming languages,Cloud Infrastructure Frameworks,Cloud Storage Programming languages,Cloud Storage Frameworks,Cloud Computing Programming languages,Cloud Computing Frameworks,Cloud Security Programming languages,Cloud Security Frameworks,Cloud Monitoring Programming languages,Cloud Monitoring Frameworks
0,0,SIEMENS LIMITED,HYDERABAD,9869487537,siemenslimited@internship.com,Yes,Work from Home,6.2,10,3,...,"Azure Resource Manager Templates,CloudFormatio...",NaN,"Java,Python","AWS SDK for .NET,AWS SDK for Java,AWS SDK for ...","Java,Node.js",NaN,"C#,Python,Java",Azure Active Directory,Java,"Azure Monitor,Google Cloud Monitoring,AWS Clou..."
1,1,SYNOPSYS,AHMEDABAD,9803384829,synopsys@internship.com,Yes,Work from office,6.7,0,9,...,NaN,AWS Cloud Development Kit (CDK),"C#,Java",NaN,"Python,.NET,Java",Google Cloud Network Connectivity Center,"Python,C#",AWS Identity and Access Management (IAM),Python,AWS CloudWatch
2,2,NBC BEARING,NAVI MUMBAI,9115143887,nbcbearing@internship.com,Yes,Work from office,6.3,1,8,...,"CloudFormation,Azure Resource Manager Template...",AWS Cloud Development Kit (CDK),"Java,C#,Python,Node.js",NaN,NaN,AWS Network Development Kit (NDK),"Java,C#,Python",NaN,"Java,Go,Python",Google Cloud Monitoring
3,3,IDEAS,KOLKATA,9306981978,ideas@internship.com,No,Work from office,6.5,7,3,...,Azure Resource Manager Templates,"AWS Cloud Development Kit (CDK),Pulumi",Python,NaN,NaN,AWS Network Development Kit (NDK),NaN,NaN,NaN,"AWS CloudWatch,Google Cloud Monitoring,Azure M..."
4,4,ZS ASSOCIATES,HYDERABAD,9882338128,zsassociates@internship.com,No,Work from office,8.3,4,0,...,"Terraform,CloudFormation","Pulumi,AWS Cloud Development Kit (CDK)","Node.js,Java",AWS SDK for .NET,"Java,Node.js,Python,Go",NaN,NaN,"AWS Identity and Access Management (IAM),Azure...",NaN,Azure Monitor
5,5,LOANTAP,JAPAN,9675592822,loantap@internship.com,Yes,Work from Home,7.1,0,8,...,NaN,NaN,"Python,Node.js","AWS SDK for .NET,AWS SDK for Java","Python,Java,Node.js,Go",Google Cloud Network Connectivity Center,Python,NaN,NaN,NaN
6,6,SAARLOHA ADVANCE MATERIALS,CHENNAI,9465959163,saarlohaadvancematerials@internship.com,Yes,Work from Home,8.4,5,10,...,"Azure Resource Manager Templates,Terraform,Clo...",NaN,NaN,NaN,".NET,Go","AWS Network Development Kit (NDK),Google Cloud...",C#,"Azure Active Directory,AWS Identity and Access...","Go,Java","Google Cloud Monitoring,Azure Monitor,AWS Clou..."
7,7,FOURFRONT PVT.LTD,MUMBAI,9590004847,fourfrontpvt.ltd@internship.com,No,Work from Home,9.0,3,2,...,NaN,"AWS Cloud Development Kit (CDK),Pulumi","Node.js,Python","AWS SDK for Java,AWS SDK for Python",.NET,NaN,C#,Azure Active Directory,NaN,NaN
8,8,HIRSCHVOGEL COMPONENTS INDIA PVT.LTD,NASHIK,9014859017,hirschvogelcomponentsindiapvt.ltd@internship.com,Yes,Work from Home,10.0,10,1,...,NaN,NaN,"Java,C#,Python,Node.js",AWS SDK for .NET,"Go,Java,Node.js,Python,.NET",Google Cloud Network Connectivity Center,"C#,Python",AWS Identity and Access Management (IAM),"Go,Python,Java","Azure Monitor,Google Cloud Monitoring"
9,9,ADM,HARYANA,9135502377,adm@internship.com,Yes,Work from office,8.6,7,5,...,"CloudFormation,Azure Resource Manager Templates",NaN,"C#,Node.js",AWS SDK for Python,NaN,Google Cloud Network Connectivity Center,C#,NaN,"Java,Go","Google Cloud Monitoring,AWS CloudWatch,Azure M..."
10,10,FOURFRONT PVT.LTD,MUMBAI,9691352876,fourfrontpvt.ltd@internship.com,No,Work from Home,8.6,6,0,...,CloudFormation,AWS Cloud Development Kit (CDK),"Java,Node.js,C#,Python",AWS SDK for .NET,"Java,Python,Node.js,Go,.NET",NaN,C#,NaN,"Go,Python,Java","Google Cloud Monitoring,AWS CloudWatch"
11,11,HOLTECCASIA,HARYANA,9516781416,holteccasia@internship.com,Yes,Work from Home,6.7,7,3,...,"Azure Resource Manager Templates,CloudFormation",Pulumi,"C#,Node.js",NaN,"Java,Node.js,.NET,Python","Google Cloud Network Connectivity Center,AWS N...","Java,Python",NaN,NaN,"Google Cloud Monitoring,Azure Monitor"
12,12,ICICI SECURITIES,BANGALORE,9316134288,icicisecurities@internship.com,No,Work from Home,9.9,5,2,...,Terraform,"Pulumi,AWS Cloud Development Kit (CDK)",NaN,AWS SDK for Java,Node.js,Google Cloud Network Connectivity Center,"C#,Java","AWS Identity and Access Management (IAM),Azure...","Java,Python","AWS CloudWatch,Azure Monitor,Google Cloud Moni..."
13,13,RENISHAW,KOLKATA,9033974203,renishaw@internship.com,No,Work from Home,6.1,7,6,...,"CloudFormation,Azure Resource Manager Templates",NaN,"Python,C#",NaN,"Python,Node.js,.NET,Go,Java",Google Cloud Network Connectivity Center,NaN,NaN,"Go,Java","Azure Monitor,AWS CloudWatch,Google Cloud Moni..."
14,14,DAIMLER TRUCK INNOVATION,NOIDA,9097393563,daimlertruckinnovation@internship.com,No,Work from Home,9.5,7,4,...,"Terraform,CloudFormation,Azure Resource Manage...",NaN,"Node.js,C#,Python","AWS SDK for .NET,AWS SDK for Python,AWS SDK fo...","Go,Java,Node.js,Python","Google Cloud Network Connectivity Center,AWS N...","C#,Java","Azure Active Directory,AWS Identity and Access...",NaN,"Google Cloud Monitoring,AWS CloudWatch,Azure M..."
15,15,TEJAS NETWORKS,NAVI MUMBAI,9689228696,tejasnetworks@internship.com,Yes,Work from Home,9.9,3,4,...,NaN,"AWS Cloud Development Kit (CDK),Pulumi",NaN,AWS SDK for .NET,Java,"AWS Network Development Kit (NDK),Google Cloud...","Java,Python","Azure Active Directory,AWS Identity and Access...",NaN,"Azure Monitor,AWS CloudWatch,Google Cloud Moni..."
16,16,09 SOLUTIONS,AHMEDABAD,9878897156,09solutions@internship.com,No,Work from Home,8.9,8,6,...,NaN,Pulumi,"Python,C#",AWS SDK for Python,"Python,.NET,Node.js",AWS Network Development Kit (NDK),C#,NaN,Python,AWS CloudWatch
17,17,AMERICAN AXLE MANUFACTURING INDIA PVT.LTD,BANGALORE,9039024425,americanaxlemanufacturingindiapvt.ltd@internsh...,No,Work from office,8.0,10,7,...,"Azure Resource Manager Templates,CloudFormation",NaN,"Java,Python,Node.js,C#",AWS SDK for Java,Java,"AWS Network Development Kit (NDK),Google Cloud...","Java,C#,Python",Azure Active Directory,Go,"Google Cloud Monitoring,Azure Monitor,AWS Clou..."
18,18,AFOUR TECHNOLOGIES,CHENNAI,9534624289,afourtechnologies@internship.com,Yes,Work from Home,6.9,4,6,...,"Terraform,Azure Resource Manager Templates",NaN,"Node.js,Python,Java,C#",AWS SDK for Java,"Java,Python,Node.js,.NET,Go",NaN,NaN,"Azure Active Directory,AWS Identity and Access...",NaN,Google Cloud Monitoring
19,19,CADENCE,JAIPUR,9784113433,cadence@internship.com,Yes,Work from Home,6.3,4,10,...,"Terraform,CloudFormation,Azure Resource Manage...",NaN,"Java,C#,Node.js,Python",AWS SDK for Python,"Node.js,Java,Python",NaN,C#,AWS Identity and Access Management (IAM),Python,"Google Cloud Monitoring,AWS CloudWatch"
20,20,FAMITECH TECHNOLOGY,PUNE,9086492921,famitechtechnology@internship.com,No,Work from Home,6.0,5,3,...,"CloudFormation,Azure Resource Manager Template...","Pulumi,AWS Cloud Development Kit (CDK)","Java,Node.js","AWS SDK for .NET,AWS SDK for Java","Node.js,Java,.NET,Python",Google Cloud Network Connectivity Center,"Python,Java,C#",NaN,"Python,Go","AWS CloudWatch,Azure Monitor"
21,21,COGNIZANT GENC,AHMEDABAD,9385642841,cognizantgenc@internship.com,Yes,Work from Home,7.7,3,6,...,Azure Resource Manager Templates,NaN,NaN,AWS SDK for Python,".NET,Go","AWS Network Development Kit (NDK),Google Cloud...","C#,Java",NaN,"Java,Go,Python","AWS CloudWatch,Azure Monitor,Google Cloud Moni..."
22,22,TEJAS NETWORKS,HYDERABAD,9272516112,tejasnetworks@internship.com,No,Work from Home,9.2,2,9,...,NaN,"AWS Cloud Development Kit (CDK),Pulumi","C#,Python","AWS SDK for Python,AWS SDK for .NET,AWS SDK fo...",Java,NaN,"C#,Java,Python",AWS Identity and Access Management (IAM),"Java,Python,Go","Azure Monitor,Google Cloud Monitoring,AWS Clou..."
23,23,BAJAJ AUTO,NAVI MUMBAI,9415653533,bajajauto@internship.com,No,Work from Home,6.2,4,0,...,"Azure Resource Manager Templates,Terraform,Clo...","AWS Cloud Development Kit (CDK),Pulumi","Java,Node.js,C#,Python",AWS SDK for .NET,"Go,Python,Java",NaN,Python,AWS Identity and Access Management (IAM),NaN,Azure Monitor
24,24,HINDUSTAN UNIVER,PUNE,9755676254,hindustanuniver@internship.com,No,Work from Home,9.9,3,4,...,"CloudFormation,Azure Resource Manager Template...",Pulumi,"C#,Python,Node.js",NaN,.NET,NaN,NaN,NaN,Java,"AWS CloudWatch,Google Cloud Monitoring"
25,25,TAVISCA,WALCHAND,9350925901,tavisca@internship.com,Yes,Work from Home,9.7,7,10,...,"Azure Resource Manager Templates,Terraform","AWS Cloud Development Kit (CDK),Pulumi","Node.js,Java",NaN,"Python,Node.js,Go,.NET,Java",AWS Network Development Kit (NDK),Python,"Azure Active Directory,AWS Identity and Access...","Java,Go",Google Cloud Monitoring
26,26,ACCOLITE,GUJARAT,9633752459,accolite@internship.com,No,Work from office,6.6,1,1,...,"CloudFormation,Azure Resource Manager Templates",Pulumi,"Node.js,C#,Python,Java",NaN,Go,"Google Cloud Network Connectivity Center,AWS N...",NaN,"AWS Identity and Access Management (IAM),Azure...","Python,Go,Java",Azure Monitor
27,27,TCS XPLORE,KOLKATA,9079659482,tcsxplore@internship.com,Yes,Work from office,9.6,3,9,...,CloudFormation,Pulumi,"Node.js,Python",NaN,NaN,"Google Cloud Network Connectivity Center,AWS N...",C#,NaN,NaN,"AWS CloudWatch,Azure Monitor"
28,28,FEV INDIA,AHMEDABAD,9664772430,fevindia@internship.com,Yes,Work from Home,7.8,4,3,...,Azure Resource Manager Templates,"AWS Cloud Development Kit (CDK),Pulumi","Node.js,Python",NaN,NaN,AWS Network Development Kit (NDK),NaN,Azure Active Directory,Java,NaN
29,29,ECLERX,NASHIK,9568113582,eclerx@internship.com,Yes,Work from office,6.3,1,7,...,NaN,NaN,"C#,Node.js,Python","AWS SDK for Python,AWS SDK for Java","Node.js,.NET,Python",NaN,NaN,NaN,"Go,Python,Java","Azure Monitor,Google Cloud Monitoring,AWS Clou..."
30,30,GOLDMAN SACHS,NAVI MUMBAI,9419036439,goldmansachs@internship.com,No,Work from office,7.2,3,9,...,"Azure Resource Manager Templates,CloudFormation",AWS Cloud Development Kit (CDK),"Java,Python,Node.js,C#",AWS SDK for Python,.NET,Google Cloud Network Connectivity Center,"Java,Python",Azure Active Directory,"Go,Java,Python",NaN
31,31,CADENCE,HARYANA,9418836074,cadence@internship.com,Yes,Work from office,7.4,9,1,...,NaN,Pulumi,"Node.js,Java",AWS SDK for .NET,"Node.js,Java,Python,.NET,Go","Google Cloud Network Connectivity Center,AWS N...","Java,Python,C#",AWS Identity and Access Management (IAM),"Go,Python,Java",NaN
32,32,WELLS FARGO,HYDERABAD,9653905178,wellsfargo@internship.com,No,Work from Home,7.8,2,2,...,"CloudFormation,Terraform,Azure Resource Manage...",NaN,Python,"AWS SDK for .NET,AWS SDK for Java","Go,Java",Google Cloud Network Connectivity Center,NaN,NaN,NaN,Google Cloud Monitoring
33,33,LOANTAP,GUJARAT,9337497925,loantap@internship.com,Yes,Work from Home,9.0,0,2,...,"Azure Resource Manager Templates,Terraform",AWS Cloud Development Kit (CDK),NaN,"AWS SDK for Python,AWS SDK for .NET",.NET,Google Cloud Network Connectivity Center,Java,NaN,NaN,Azure Monitor
34,34,MASTERCARD,HARYANA,9621998675,mastercard@internship.com,Yes,Work from office,7.7,1,9,...,NaN,NaN,"Java,Node.js,Python,C#","AWS SDK for Python,AWS SDK for .NET,AWS SDK fo...",".NET,Go,Java",NaN,"Python,C#,Java",AWS Identity and Access Management (IAM),"Java,Python,Go",Google Cloud Monitoring
35,35,GODREJ & BOYCE,HARYANA,9115600458,godrej&boyce@internship.com,No,Work from office,9.2,3,6,...,NaN,"Pulumi,AWS Cloud Development Kit (CDK)","C#,Java,Python,Node.js","AWS SDK for Python,AWS SDK for .NET","Java,.NET,Go,Python","AWS Network Development Kit (NDK),Google Cloud...",Java,Azure Active Directory,NaN,"AWS CloudWatch,Azure Monitor,Google Cloud Moni..."
36,36,MSCI,CHENNAI,9047872401,msci@internship.com,Yes,Work from office,6.6,2,7,...,NaN,Pulumi,Node.js,"AWS SDK for Java,AWS SDK for .NET,AWS SDK for ...","Python,Node.js",Google Cloud Network Connectivity Center,"Java,C#,Python",NaN,"Java,Go",Azure Monitor
37,37,WALCHAND INDUSTRIES,MUMBAI,9512669856,walchandindustries@internship.com,No,Work from Home,6.8,8,0,...,"Azure Resource Manager Templates,Terraform,Clo...",NaN,NaN,"AWS SDK for .NET,AWS SDK for Java,AWS SDK for ...","Java,Go,Node.js",AWS Network Development Kit (NDK),Java,NaN,"Python,Java,Go",Azure Monitor
38,38,JSW GROUP,GURGAON,9889435218,jswgroup@internship.com,No,Work from Home,7.4,1,3,...,NaN,"AWS Cloud Development Kit (CDK),Pulumi",NaN,NaN,".NET,Node.js",AWS Network Development Kit (NDK),"C#,Java,Python",AWS Identity and Access Management (IAM),Go,"AWS CloudWatch,Azure Monitor,Google Cloud Moni..."
39,39,CAP GEMINI,AHMEDABAD,9959209823,capgemini@internship.com,Yes,Work from office,10.0,3,4,...,NaN,Pulumi,"Node.js,C#,Java",AWS SDK for Java,"Java,Python,Node.js,.NET,Go","AWS Network Development Kit (NDK),Google Cloud...","C#,Java",AWS Identity and Access Management (IAM),"Python,Java",AWS CloudWatch
40,40,AMERICAN AXLE MANUFACTURING INDIA PVT.LTD,CHENNAI,9266274596,americanaxlemanufacturingindiapvt.ltd@internsh...,No,Work from Home,9.1,5,5,...,"CloudFormation,Terraform,Azure Resource Manage...",NaN,C#,"AWS SDK for Java,AWS SDK for .NET,AWS SDK for ...","Go,Python,.NET",Google Cloud Network Connectivity Center,C#,"AWS Identity and Access Management (IAM),Azure...",Java,"Google Cloud Monitoring,Azure Monitor"
41,41,TEXAS INSTRUMENTS,AHMEDABAD,9807845817,texasinstruments@internship.com,Yes,Work from office,6.6,3,9,...,"Terraform,CloudFormation","AWS Cloud Development Kit (CDK),Pulumi","Python,Node.js,C#","AWS SDK for Python,AWS SDK for Java,AWS SDK fo...",NaN,NaN,"Python,C#",NaN,Go,Azure Monitor
42,42,MASTERCARD,HARYANA,9647806642,mastercard@internship.com,No,Work from office,10.0,4,7,...,"Azure Resource Manager Templates,Terraform,Clo...",NaN,"C#,Python,Java,Node.js","AWS SDK for Java,AWS SDK for Python,AWS SDK fo...","Node.js,Java","AWS Network Development Kit (NDK),Google Cloud...",C#,"AWS Identity and Access Management (IAM),Azure...",Java,NaN
43,43,SAARLOHA ADVANCE MATERIALS,LATUR,9196366217,saarlohaadvancematerials@internship.com,Yes,Work from Home,7.7,9,9,...,"Azure Resource Manager Templates,Terraform",AWS Cloud Development Kit (CDK),NaN,AWS SDK for Java,"Java,Go",AWS Network Development Kit (NDK),"C#,Python",AWS Identity and Access Management (IAM),NaN,"Google Cloud Monitoring,Azure Monitor,AWS Clou..."
44,44,CATERPILLAR,AURANGABAD,9738747586,caterpillar@internship.com,No,Work from office,9.2,0,5,...,NaN,"Pulumi,AWS Cloud Development Kit (CDK)","C#,Java,Python,Node.js",AWS SDK for Python,NaN,NaN,"C#,Python,Java","AWS Identity and Access Management (IAM),Azure...","Go,Java,Python","Azure Monitor,Google Cloud Monitoring,AWS Clou..."
45,45,OLA ELECTRIC,HYDERABAD,9411823749,olaelectric@internship.com,No,Work from office,7.2,10,7,...,NaN,"Pulumi,AWS Cloud Development Kit (CDK)","C#,Node.js",NaN,"Python,.NET,Node.js","AWS Network Development Kit (NDK),Google Cloud...",Python,NaN,"Python,Java,Go",NaN
46,46,SOC GEN,HARYANA,9076167505,socgen@internship.com,No,Work from office,6.0,1,6,...,"Azure Resource Manager Templates,Terraform,Clo...","Pulumi,AWS Cloud Development Kit (CDK)","Java,C#,Python,Node.js","AWS SDK for Java,AWS SDK for Python","Python,.NET",Google Cloud Network Connectivity Center,C#,AWS Identity and Access Management (IAM),"Java,Python,Go",AWS CloudWatch
47,47,CENTRIO,WALCHAND,9621379210,centrio@internship.com,Yes,Work from Home,9.7,8,3,...,"CloudFormation,Terraform,Azure Resource Manage...",AWS Cloud Development Kit (CDK),NaN,AWS SDK for Java,NaN,"AWS Network Development Kit (NDK),Google Cloud...","Python,C#","AWS Identity and Access Management (IAM),Azure...",NaN,NaN
48,48,PUBLICIS SAPIENT,NASHIK,9836889197,publicissapient@internship.com,Yes,Work from Home,6.7,1,9,...,"Terraform,Azure Resource Manager Templates,Clo...","Pulumi,AWS Cloud Development Kit (CDK)","Python,Node.js","AWS SDK for .NET,AWS SDK for Java,AWS SDK for ...","Node.js,Python,.NET",NaN,Java,"AWS Identity and Access Management (IAM),Azure...","Go,Python","Google Cloud Monitoring,Azure Monitor,AWS Clou..."
49,49,DEUTSCHE BANK,KOLKATA,9576905028,deutschebank@internship.com,No,Work from Home,8.2,8,2,...,NaN,NaN,"Node.js,Java","AWS SDK for .NET,AWS SDK for Java,AWS SDK for ...","Go,.NET",NaN,C#,NaN,NaN,NaN
50,50,EY INDIA,LATUR,9836562396,eyindia@internship.com,No,Work from office,7.5,4,1,...,"Azure Resource Manager Templates,Terraform","Pulumi,AWS Cloud Development Kit (CDK)",NaN,NaN,".NET,Node.js,Go,Python",AWS Network Development Kit (NDK),"Java,Python",NaN,"Go,Java,Python","Azure Monitor,AWS CloudWatch"
51,51,ADM,HYDERABAD,9043495076,adm@internship.com,No,Work from office,9.6,7,4,...,Terraform,NaN,"C#,Node.js","AWS SDK for Python,AWS SDK for Java,AWS SDK fo...",".NET,Go","AWS Network Development Kit (NDK),Google Cloud...",NaN,"Azure Active Directory,AWS Identity and Access...","Python,Go","AWS CloudWatch,Google Cloud Monitoring"
52,52,RELIANCE JIO,BANGALORE,9982224884,reliancejio@internship.com,No,Work from Home,9.0,6,6,...,"Terraform,CloudFormation,Azure Resource Manage...","AWS Cloud Development Kit (CDK),Pulumi","Python,Node.js,Java,C#","AWS SDK for Java,AWS SDK for Python,AWS SDK fo...",Go,NaN,"C#,Java,Python","Azure Active Directory,AWS Identity and Access...","Go,Java",NaN
53,53,INFOSYS DSE,LATUR,9684927464,infosysdse@internship.com,Yes,Work from Home,7.1,2,1,...,NaN,NaN,"Node.js,Java,Python","AWS SDK for Java,AWS SDK for .NET,AWS SDK for ...","Node.js,Go",AWS Network Development Kit (NDK),"Python,Java,C#",NaN,"Java,Go",Google Cloud Monitoring
54,54,PRECON SERVICES,NAVI MUMBAI,9247045430,preconservices@internship.com,Yes,Work from Home,9.4,3,8,...,Terraform,"Pulumi,AWS Cloud Development Kit (CDK)","Java,C#",AWS SDK for .NET,"Go,Node.js",NaN,NaN,NaN,"Python,Java",Azure Monitor
55,55,MASTERCARD,NOIDA,9177354673,mastercard@internship.com,No,Work from Home,7.2,8,5,...,Azure Resource Manager Templates,NaN,C#,NaN,".NET,Node.js,Python,Java",NaN,NaN,"Azure Active Directory,AWS Identity and Access...","Python,Java,Go","Azure Monitor,AWS CloudWatch"
56,56,VODAFONE,CHENNAI,9698648246,vodafone@internship.com,No,Work from office,7.7,0,6,...,CloudFormation,AWS Cloud Development Kit (CDK),"Python,Java","AWS SDK for .NET,AWS SDK for Python","Go,.NET,Node.js,Python",AWS Network Development Kit (NDK),NaN,NaN,"Go,Java","Google Cloud Monitoring,AWS CloudWatch,Azure M..."
57,57,SHAH TECHNICAL CONSULTANTS PVT.LTD,JAIPUR,9924063253,shahtechnicalconsultantspvt.ltd@internship.com,Yes,Work from Home,8.6,6,10,...,NaN,"AWS Cloud Development Kit (CDK),Pulumi",Python,NaN,".NET,Java,Go,Python,Node.js",AWS Network Development Kit (NDK),"Java,Python",NaN,Java,"Google Cloud Monitoring,AWS CloudWatch"
58,58,DAIMLER TRUCK INNOVATION,AURANGABAD,9541466911,daimlertruckinnovation@internship.com,No,Work from Home,6.7,6,5,...,"Terraform,Azure Resource Manager Templates","Pulumi,AWS Cloud Development Kit (CDK)","C#,Python,Java",AWS SDK for Java,"Python,Node.js,Go,Java,.NET",NaN,"Java,Python",NaN,"Python,Go",NaN
59,59,NCR CORPORATION,NASHIK,9821882305,ncrcorporation@internship.com,Yes,Work from office,7.5,7,0,...,"Terraform,Azure Resource Manager Templates",NaN,NaN,NaN,".NET,Python,Node.js,Java,Go","Google Cloud Network Connectivity Center,AWS N...",NaN,"Azure Active Directory,AWS Identity and Access...","Go,Python",AWS CloudWatch

In [17]:
modified_cloud_df=cloud_df.drop(['Unnamed: 0','Address of company', 'Phone Number',
       'Email Address', 'Previous Visited COEP'],axis=1)
modified_cloud_df

,Name of company,Work Mode,Min CGPA,Seats for Boys,Seats for Girls,Number of Dead Backlogs permitted,Number of Active Backlogs permitted,Preffered month of visiting campus,Domain to Hire,Cloud Infrastructure Programming languages,Cloud Infrastructure Frameworks,Cloud Storage Programming languages,Cloud Storage Frameworks,Cloud Computing Programming languages,Cloud Computing Frameworks,Cloud Security Programming languages,Cloud Security Frameworks,Cloud Monitoring Programming languages,Cloud Monitoring Frameworks
0,SIEMENS LIMITED,Work from Home,6.2,10,3,1,0,September,‚òÅÔ∏èCloud Engineer,"Azure Resource Manager Templates,CloudFormatio...",NaN,"Java,Python","AWS SDK for .NET,AWS SDK for Java,AWS SDK for ...","Java,Node.js",NaN,"C#,Python,Java",Azure Active Directory,Java,"Azure Monitor,Google Cloud Monitoring,AWS Clou..."
1,SYNOPSYS,Work from office,6.7,0,9,0,1,December,‚òÅÔ∏èCloud Engineer,NaN,AWS Cloud Development Kit (CDK),"C#,Java",NaN,"Python,.NET,Java",Google Cloud Network Connectivity Center,"Python,C#",AWS Identity and Access Management (IAM),Python,AWS CloudWatch
2,NBC BEARING,Work from office,6.3,1,8,0,2,October,‚òÅÔ∏èCloud Engineer,"CloudFormation,Azure Resource Manager Template...",AWS Cloud Development Kit (CDK),"Java,C#,Python,Node.js",NaN,NaN,AWS Network Development Kit (NDK),"Java,C#,Python",NaN,"Java,Go,Python",Google Cloud Monitoring
3,IDEAS,Work from office,6.5,7,3,2,0,September,‚òÅÔ∏èCloud Engineer,Azure Resource Manager Templates,"AWS Cloud Development Kit (CDK),Pulumi",Python,NaN,NaN,AWS Network Development Kit (NDK),NaN,NaN,NaN,"AWS CloudWatch,Google Cloud Monitoring,Azure M..."
4,ZS ASSOCIATES,Work from office,8.3,4,0,2,2,Novermber,‚òÅÔ∏èCloud Engineer,"Terraform,CloudFormation","Pulumi,AWS Cloud Development Kit (CDK)","Node.js,Java",AWS SDK for .NET,"Java,Node.js,Python,Go",NaN,NaN,"AWS Identity and Access Management (IAM),Azure...",NaN,Azure Monitor
5,LOANTAP,Work from Home,7.1,0,8,0,1,July,‚òÅÔ∏èCloud Engineer,NaN,NaN,"Python,Node.js","AWS SDK for .NET,AWS SDK for Java","Python,Java,Node.js,Go",Google Cloud Network Connectivity Center,Python,NaN,NaN,NaN
6,SAARLOHA ADVANCE MATERIALS,Work from Home,8.4,5,10,1,2,October,‚òÅÔ∏èCloud Engineer,"Azure Resource Manager Templates,Terraform,Clo...",NaN,NaN,NaN,".NET,Go","AWS Network Development Kit (NDK),Google Cloud...",C#,"Azure Active Directory,AWS Identity and Access...","Go,Java","Google Cloud Monitoring,Azure Monitor,AWS Clou..."
7,FOURFRONT PVT.LTD,Work from Home,9.0,3,2,1,1,December,‚òÅÔ∏èCloud Engineer,NaN,"AWS Cloud Development Kit (CDK),Pulumi","Node.js,Python","AWS SDK for Java,AWS SDK for Python",.NET,NaN,C#,Azure Active Directory,NaN,NaN
8,HIRSCHVOGEL COMPONENTS INDIA PVT.LTD,Work from Home,10.0,10,1,2,0,August,‚òÅÔ∏èCloud Engineer,NaN,NaN,"Java,C#,Python,Node.js",AWS SDK for .NET,"Go,Java,Node.js,Python,.NET",Google Cloud Network Connectivity Center,"C#,Python",AWS Identity and Access Management (IAM),"Go,Python,Java","Azure Monitor,Google Cloud Monitoring"
9,ADM,Work from office,8.6,7,5,1,1,July,‚òÅÔ∏èCloud Engineer,"CloudFormation,Azure Resource Manager Templates",NaN,"C#,Node.js",AWS SDK for Python,NaN,Google Cloud Network Connectivity Center,C#,NaN,"Java,Go","Google Cloud Monitoring,AWS CloudWatch,Azure M..."
10,FOURFRONT PVT.LTD,Work from Home,8.6,6,0,2,0,Novermber,‚òÅÔ∏èCloud Engineer,CloudFormation,AWS Cloud Development Kit (CDK),"Java,Node.js,C#,Python",AWS SDK for .NET,"Java,Python,Node.js,Go,.NET",NaN,C#,NaN,"Go,Python,Java","Google Cloud Monitoring,AWS CloudWatch"
11,HOLTECCASIA,Work from Home,6.7,7,3,0,0,October,‚òÅÔ∏èCloud Engineer,"Azure Resource Manager Templates,CloudFormation",Pulumi,"C#,Node.js",NaN,"Java,Node.js,.NET,Python","Google Cloud Network Connectivity Center,AWS N...","Java,Python",NaN,NaN,"Google Cloud Monitoring,Azure Monitor"
12,ICICI SECURITIES,Work from Home,9.9,5,2,0,2,December,‚òÅÔ∏èCloud Engineer,Terraform,"Pulumi,AWS Cloud Development Kit (CDK)",NaN,AWS SDK for Java,Node.js,Google Cloud Network Connectivity Center,"C#,Java","AWS Identity and Access Management (IAM),Azure...","Java,Python","AWS CloudWatch,Azure Monitor,Google Cloud Moni..."
13,RENISHAW,Work from Home,6.1,7,6,0,0,October,‚òÅÔ∏èCloud Engineer,"CloudFormation,Azure Resource Manager Templates",NaN,"Python,C#",NaN,"Python,Node.js,.NET,Go,Java",Google Cloud Network Connectivity Center,NaN,NaN,"Go,Java","Azure Monitor,AWS CloudWatch,Google Cloud Moni..."
14,DAIMLER TRUCK INNOVATION,Work from Home,9.5,7,4,0,1,Novermber,‚òÅÔ∏èCloud Engineer,"Terraform,CloudFormation,Azure Resource Manage...",NaN,"Node.js,C#,Python","AWS SDK for .NET,AWS SDK for Python,AWS SDK fo...","Go,Java,Node.js,Python","Google Cloud Network Connectivity Center,AWS N...","C#,Java","Azure Active Directory,AWS Identity and Access...",NaN,"Google Cloud Monitoring,AWS CloudWatch,Azure M..."
15,TEJAS NETWORKS,Work from Home,9.9,3,4,1,0,Novermber,‚òÅÔ∏èCloud Engineer,NaN,"AWS Cloud Development Kit (CDK),Pulumi",NaN,AWS SDK for .NET,Java,"AWS Network Development Kit (NDK),Google Cloud...","Java,Python","Azure Active Directory,AWS Identity and Access...",NaN,"Azure Monitor,AWS CloudWatch,Google Cloud Moni..."
16,09 SOLUTIONS,Work from Home,8.9,8,6,0,2,August,‚òÅÔ∏èCloud Engineer,NaN,Pulumi,"Python,C#",AWS SDK for Python,"Python,.NET,Node.js",AWS Network Development Kit (NDK),C#,NaN,Python,AWS CloudWatch
17,AMERICAN AXLE MANUFACTURING INDIA PVT.LTD,Work from office,8.0,10,7,0,0,August,‚òÅÔ∏èCloud Engineer,"Azure Resource Manager Templates,CloudFormation",NaN,"Java,Python,Node.js,C#",AWS SDK for Java,Java,"AWS Network Development Kit (NDK),Google Cloud...","Java,C#,Python",Azure Active Directory,Go,"Google Cloud Monitoring,Azure Monitor,AWS Clou..."
18,AFOUR TECHNOLOGIES,Work from Home,6.9,4,6,2,0,September,‚òÅÔ∏èCloud Engineer,"Terraform,Azure Resource Manager Templates",NaN,"Node.js,Python,Java,C#",AWS SDK for Java,"Java,Python,Node.js,.NET,Go",NaN,NaN,"Azure Active Directory,AWS Identity and Access...",NaN,Google Cloud Monitoring
19,CADENCE,Work from Home,6.3,4,10,2,0,Novermber,‚òÅÔ∏èCloud Engineer,"Terraform,CloudFormation,Azure Resource Manage...",NaN,"Java,C#,Node.js,Python",AWS SDK for Python,"Node.js,Java,Python",NaN,C#,AWS Identity and Access Management (IAM),Python,"Google Cloud Monitoring,AWS CloudWatch"
20,FAMITECH TECHNOLOGY,Work from Home,6.0,5,3,2,2,Novermber,‚òÅÔ∏èCloud Engineer,"CloudFormation,Azure Resource Manager Template...","Pulumi,AWS Cloud Development Kit (CDK)","Java,Node.js","AWS SDK for .NET,AWS SDK for Java","Node.js,Java,.NET,Python",Google Cloud Network Connectivity Center,"Python,Java,C#",NaN,"Python,Go","AWS CloudWatch,Azure Monitor"
21,COGNIZANT GENC,Work from Home,7.7,3,6,2,1,December,‚òÅÔ∏èCloud Engineer,Azure Resource Manager Templates,NaN,NaN,AWS SDK for Python,".NET,Go","AWS Network Development Kit (NDK),Google Cloud...","C#,Java",NaN,"Java,Go,Python","AWS CloudWatch,Azure Monitor,Google Cloud Moni..."
22,TEJAS NETWORKS,Work from Home,9.2,2,9,0,1,August,‚òÅÔ∏èCloud Engineer,NaN,"AWS Cloud Development Kit (CDK),Pulumi","C#,Python","AWS SDK for Python,AWS SDK for .NET,AWS SDK fo...",Java,NaN,"C#,Java,Python",AWS Identity and Access Management (IAM),"Java,Python,Go","Azure Monitor,Google Cloud Monitoring,AWS Clou..."
23,BAJAJ AUTO,Work from Home,6.2,4,0,0,0,June,‚òÅÔ∏èCloud Engineer,"Azure Resource Manager Templates,Terraform,Clo...","AWS Cloud Development Kit (CDK),Pulumi","Java,Node.js,C#,Python",AWS SDK for .NET,"Go,Python,Java",NaN,Python,AWS Identity and Access Management (IAM),NaN,Azure Monitor
24,HINDUSTAN UNIVER,Work from Home,9.9,3,4,2,1,June,‚òÅÔ∏èCloud Engineer,"CloudFormation,Azure Resource Manager Template...",Pulumi,"C#,Python,Node.js",NaN,.NET,NaN,NaN,NaN,Java,"AWS CloudWatch,Google Cloud Monitoring"
25,TAVISCA,Work from Home,9.7,7,10,0,2,June,‚òÅÔ∏èCloud Engineer,"Azure Resource Manager Templates,Terraform","AWS Cloud Development Kit (CDK),Pulumi","Node.js,Java",NaN,"Python,Node.js,Go,.NET,Java",AWS Network Development Kit (NDK),Python,"Azure Active Directory,AWS Identity and Access...","Java,Go",Google Cloud Monitoring
26,ACCOLITE,Work from office,6.6,1,1,0,0,July,‚òÅÔ∏èCloud Engineer,"CloudFormation,Azure Resource Manager Templates",Pulumi,"Node.js,C#,Python,Java",NaN,Go,"Google Cloud Network Connectivity Center,AWS N...",NaN,"AWS Identity and Access Management (IAM),Azure...","Python,Go,Java",Azure Monitor
27,TCS XPLORE,Work from office,9.6,3,9,1,0,Novermber,‚òÅÔ∏èCloud Engineer,CloudFormation,Pulumi,"Node.js,Python",NaN,NaN,"Google Cloud Network Connectivity Center,AWS N...",C#,NaN,NaN,"AWS CloudWatch,Azure Monitor"
28,FEV INDIA,Work from Home,7.8,4,3,1,0,December,‚òÅÔ∏èCloud Engineer,Azure Resource Manager Templates,"AWS Cloud Development Kit (CDK),Pulumi","Node.js,Python",NaN,NaN,AWS Network Development Kit (NDK),NaN,Azure Active Directory,Java,NaN
29,ECLERX,Work from office,6.3,1,7,1,2,October,‚òÅÔ∏èCloud Engineer,NaN,NaN,"C#,Node.js,Python","AWS SDK for Python,AWS SDK for Java","Node.js,.NET,Python",NaN,NaN,NaN,"Go,Python,Java","Azure Monitor,Google Cloud Monitoring,AWS Clou..."
30,GOLDMAN SACHS,Work from office,7.2,3,9,0,1,July,‚òÅÔ∏èCloud Engineer,"Azure Resource Manager Templates,CloudFormation",AWS Cloud Development Kit (CDK),"Java,Python,Node.js,C#",AWS SDK for Python,.NET,Google Cloud Network Connectivity Center,"Java,Python",Azure Active Directory,"Go,Java,Python",NaN
31,CADENCE,Work from office,7.4,9,1,2,0,June,‚òÅÔ∏èCloud Engineer,NaN,Pulumi,"Node.js,Java",AWS SDK for .NET,"Node.js,Java,Python,.NET,Go","Google Cloud Network Connectivity Center,AWS N...","Java,Python,C#",AWS Identity and Access Management (IAM),"Go,Python,Java",NaN
32,WELLS FARGO,Work from Home,7.8,2,2,1,2,Novermber,‚òÅÔ∏èCloud Engineer,"CloudFormation,Terraform,Azure Resource Manage...",NaN,Python,"AWS SDK for .NET,AWS SDK for Java","Go,Java",Google Cloud Network Connectivity Center,NaN,NaN,NaN,Google Cloud Monitoring
33,LOANTAP,Work from Home,9.0,0,2,2,1,June,‚òÅÔ∏èCloud Engineer,"Azure Resource Manager Templates,Terraform",AWS Cloud Development Kit (CDK),NaN,"AWS SDK for Python,AWS SDK for .NET",.NET,Google Cloud Network Connectivity Center,Java,NaN,NaN,Azure Monitor
34,MASTERCARD,Work from office,7.7,1,9,0,1,October,‚òÅÔ∏èCloud Engineer,NaN,NaN,"Java,Node.js,Python,C#","AWS SDK for Python,AWS SDK for .NET,AWS SDK fo...",".NET,Go,Java",NaN,"Python,C#,Java",AWS Identity and Access Management (IAM),"Java,Python,Go",Google Cloud Monitoring
35,GODREJ & BOYCE,Work from office,9.2,3,6,0,0,June,‚òÅÔ∏èCloud Engineer,NaN,"Pulumi,AWS Cloud Development Kit (CDK)","C#,Java,Python,Node.js","AWS SDK for Python,AWS SDK for .NET","Java,.NET,Go,Python","AWS Network Development Kit (NDK),Google Cloud...",Java,Azure Active Directory,NaN,"AWS CloudWatch,Azure Monitor,Google Cloud Moni..."
36,MSCI,Work from office,6.6,2,7,2,2,Novermber,‚òÅÔ∏èCloud Engineer,NaN,Pulumi,Node.js,"AWS SDK for Java,AWS SDK for .NET,AWS SDK for ...","Python,Node.js",Google Cloud Network Connectivity Center,"Java,C#,Python",NaN,"Java,Go",Azure Monitor
37,WALCHAND INDUSTRIES,Work from Home,6.8,8,0,0,2,October,‚òÅÔ∏èCloud Engineer,"Azure Resource Manager Templates,Terraform,Clo...",NaN,NaN,"AWS SDK for .NET,AWS SDK for Java,AWS SDK for ...","Java,Go,Node.js",AWS Network Development Kit (NDK),Java,NaN,"Python,Java,Go",Azure Monitor
38,JSW GROUP,Work from Home,7.4,1,3,1,1,December,‚òÅÔ∏èCloud Engineer,NaN,"AWS Cloud Development Kit (CDK),Pulumi",NaN,NaN,".NET,Node.js",AWS Network Development Kit (NDK),"C#,Java,Python",AWS Identity and Access Management (IAM),Go,"AWS CloudWatch,Azure Monitor,Google Cloud Moni..."
39,CAP GEMINI,Work from office,10.0,3,4,2,0,July,‚òÅÔ∏èCloud Engineer,NaN,Pulumi,"Node.js,C#,Java",AWS SDK for Java,"Java,Python,Node.js,.NET,Go","AWS Network Development Kit (NDK),Google Cloud...","C#,Java",AWS Identity and Access Management (IAM),"Python,Java",AWS CloudWatch
40,AMERICAN AXLE MANUFACTURING INDIA PVT.LTD,Work from Home,9.1,5,5,0,0,October,‚òÅÔ∏èCloud Engineer,"CloudFormation,Terraform,Azure Resource Manage...",NaN,C#,"AWS SDK for Java,AWS SDK for .NET,AWS SDK for ...","Go,Python,.NET",Google Cloud Network Connectivity Center,C#,"AWS Identity and Access Management (IAM),Azure...",Java,"Google Cloud Monitoring,Azure Monitor"
41,TEXAS INSTRUMENTS,Work from office,6.6,3,9,2,2,June,‚òÅÔ∏èCloud Engineer,"Terraform,CloudFormation","AWS Cloud Development Kit (CDK),Pulumi","Python,Node.js,C#","AWS SDK for Python,AWS SDK for Java,AWS SDK fo...",NaN,NaN,"Python,C#",NaN,Go,Azure Monitor
42,MASTERCARD,Work from office,10.0,4,7,2,1,September,‚òÅÔ∏èCloud Engineer,"Azure Resource Manager Templates,Terraform,Clo...",NaN,"C#,Python,Java,Node.js","AWS SDK for Java,AWS SDK for Python,AWS SDK fo...","Node.js,Java","AWS Network Development Kit (NDK),Google Cloud...",C#,"AWS Identity and Access Management (IAM),Azure...",Java,NaN
43,SAARLOHA ADVANCE MATERIALS,Work from Home,7.7,9,9,0,2,December,‚òÅÔ∏èCloud Engineer,"Azure Resource Manager Templates,Terraform",AWS Cloud Development Kit (CDK),NaN,AWS SDK for Java,"Java,Go",AWS Network Development Kit (NDK),"C#,Python",AWS Identity and Access Management (IAM),NaN,"Google Cloud Monitoring,Azure Monitor,AWS Clou..."
44,CATERPILLAR,Work from office,9.2,0,5,0,1,Novermber,‚òÅÔ∏èCloud Engineer,NaN,"Pulumi,AWS Cloud Development Kit (CDK)","C#,Java,Python,Node.js",AWS SDK for Python,NaN,NaN,"C#,Python,Java","AWS Identity and Access Management (IAM),Azure...","Go,Java,Python","Azure Monitor,Google Cloud Monitoring,AWS Clou..."
45,OLA ELECTRIC,Work from office,7.2,10,7,2,0,December,‚òÅÔ∏èCloud Engineer,NaN,"Pulumi,AWS Cloud Development Kit (CDK)","C#,Node.js",NaN,"Python,.NET,Node.js","AWS Network Development Kit (NDK),Google Cloud...",Python,NaN,"Python,Java,Go",NaN
46,SOC GEN,Work from office,6.0,1,6,0,1,October,‚òÅÔ∏èCloud Engineer,"Azure Resource Manager Templates,Terraform,Clo...","Pulumi,AWS Cloud Development Kit (CDK)","Java,C#,Python,Node.js","AWS SDK for Java,AWS SDK for Python","Python,.NET",Google Cloud Network Connectivity Center,C#,AWS Identity and Access Management (IAM),"Java,Python,Go",AWS CloudWatch
47,CENTRIO,Work from Home,9.7,8,3,1,2,December,‚òÅÔ∏èCloud Engineer,"CloudFormation,Terraform,Azure Resource Manage...",AWS Cloud Development Kit (CDK),NaN,AWS SDK for Java,NaN,"AWS Network Development Kit (NDK),Google Cloud...","Python,C#","AWS Identity and Access Management (IAM),Azure...",NaN,NaN
48,PUBLICIS SAPIENT,Work from Home,6.7,1,9,1,2,August,‚òÅÔ∏èCloud Engineer,"Terraform,Azure Resource Manager Templates,Clo...","Pulumi,AWS Cloud Development Kit (CDK)","Python,Node.js","AWS SDK for .NET,AWS SDK for Java,AWS SDK for ...","Node.js,Python,.NET",NaN,Java,"AWS Identity and Access Management (IAM),Azure...","Go,Python","Google Cloud Monitoring,Azure Monitor,AWS Clou..."
49,DEUTSCHE BANK,Work from Home,8.2,8,2,2,2,July,‚òÅÔ∏èCloud Engineer,NaN,NaN,"Node.js,Java","AWS SDK for .NET,AWS SDK for Java,AWS SDK for ...","Go,.NET",NaN,C#,NaN,NaN,NaN
50,EY INDIA,Work from office,7.5,4,1,1,2,August,‚òÅÔ∏èCloud Engineer,"Azure Resource Manager Templates,Terraform","Pulumi,AWS Cloud Development Kit (CDK)",NaN,NaN,".NET,Node.js,Go,Python",AWS Network Development Kit (NDK),"Java,Python",NaN,"Go,Java,Python","Azure Monitor,AWS CloudWatch"
51,ADM,Work from office,9.6,7,4,0,1,Novermber,‚òÅÔ∏èCloud Engineer,Terraform,NaN,"C#,Node.js","AWS SDK for Python,AWS SDK for Java,AWS SDK fo...",".NET,Go","AWS Network Development Kit (NDK),Google Cloud...",NaN,"Azure Active Directory,AWS Identity and Access...","Python,Go","AWS CloudWatch,Google Cloud Monitoring"
52,RELIANCE JIO,Work from Home,9.0,6,6,2,1,June,‚òÅÔ∏èCloud Engineer,"Terraform,CloudFormation,Azure Resource Manage...","AWS Cloud Development Kit (CDK),Pulumi","Python,Node.js,Java,C#","AWS SDK for Java,AWS SDK for Python,AWS SDK fo...",Go,NaN,"C#,Java,Python","Azure Active Directory,AWS Identity and Access...","Go,Java",NaN
53,INFOSYS DSE,Work from Home,7.1,2,1,0,0,September,‚òÅÔ∏èCloud Engineer,NaN,NaN,"Node.js,Java,Python","AWS SDK for Java,AWS SDK for .NET,AWS SDK for ...","Node.js,Go",AWS Network Development Kit (NDK),"Python,Java,C#",NaN,"Java,Go",Google Cloud Monitoring
54,PRECON SERVICES,Work from Home,9.4,3,8,2,2,Novermber,‚òÅÔ∏èCloud Engineer,Terraform,"Pulumi,AWS Cloud Development Kit (CDK)","Java,C#",AWS SDK for .NET,"Go,Node.js",NaN,NaN,NaN,"Python,Java",Azure Monitor
55,MASTERCARD,Work from Home,7.2,8,5,1,0,August,‚òÅÔ∏èCloud Engineer,Azure Resource Manager Templates,NaN,C#,NaN,".NET,Node.js,Python,Java",NaN,NaN,"Azure Active Directory,AWS Identity and Access...","Python,Java,Go","Azure Monitor,AWS CloudWatch"
56,VODAFONE,Work from office,7.7,0,6,0,0,Novermber,‚òÅÔ∏èCloud Engineer,CloudFormation,AWS Cloud Development Kit (CDK),"Python,Java","AWS SDK for .NET,AWS SDK for Python","Go,.NET,Node.js,Python",AWS Network Development Kit (NDK),NaN,NaN,"Go,Java","Google Cloud Monitoring,AWS CloudWatch,Azure M..."
57,SHAH TECHNICAL CONSULTANTS PVT.LTD,Work from Home,8.6,6,10,1,0,September,‚òÅÔ∏èCloud Engineer,NaN,"AWS Cloud Development Kit (CDK),Pulumi",Python,NaN,".NET,Java,Go,Python,Node.js",AWS Network Development Kit (NDK),"Java,Python",NaN,Java,"Google Cloud Monitoring,AWS CloudWatch"
58,DAIMLER TRUCK INNOVATION,Work from Home,6.7,6,5,2,0,August,‚òÅÔ∏èCloud Engineer,"Terraform,Azure Resource Manager Templates","Pulumi,AWS Cloud Development Kit (CDK)","C#,Python,Java",AWS SDK for Java,"Python,Node.js,Go,Java,.NET",NaN,"Java,Python",NaN,"Python,Go",NaN
59,NCR CORPORATION,Work from office,7.5,7,0,0,0,September,‚òÅÔ∏èCloud Engineer,"Terraform,Azure Resource Manager Templates",NaN,NaN,NaN,".NET,Python,Node.js,Java,Go","Google Cloud Network Connectivity Center,AWS N...",NaN,"Azure Active Directory,AWS Identity and Access...","Go,Python",AWS CloudWatch

In [18]:
modified_cloud_df.to_csv("~\Desktop\RPOOPS\Mini Project\Part_B\Final_Data\Final_cloud_data.csv")

In [20]:
dbms_df=pd.read_csv("~\Desktop\RPOOPS\Mini Project\Part_B\Raw_Data_Generated\Raw_dbms_data.csv")
dbms_df

,Unnamed: 0,Name of company,Address of company,Phone Number,Email Address,Previous Visited COEP,Work Mode,Min CGPA,Seats for Boys,Seats for Girls,...,Preffered month of visiting campus,Domain to Hire,Database Design,Datbase Development,Database Administration,Database Migration,Database Performance Tuning,Database Security,Data Warehousing,Big Data
0,0,CION DIGITAL,WALCHAND,9370023372,ciondigital@internship.com,No,Work from office,9.1,5,8,...,July,üî¢Database Engineer,"ER Diagrams,SQL","MySQL,SQL Server,SQL,PL/SQL,Oracle Database,T-...",PostgreSQL,"Oracle Data Integrator,SQL","MySQL Workbench,PL/SQL","SQL,Microsoft SQL Server Audit,MySQL Enterpris...","PL/SQL,SQL Server Integration Services,SQL,Ora...","SQL,Pig Latin,HiveQL"
1,1,CENTRIO,KOLKATA,9946818711,centrio@internship.com,No,Work from Home,7.6,4,0,...,October,üî¢Database Engineer,"ER Diagrams,SQL",NaN,"Oracle Database,SQL Server",Apache NiFi,"PL/SQL,MySQL Workbench,Oracle Enterprise Manag...","PL/SQL,T-SQL,SQL","SQL,Oracle Warehouse Builder,Pentaho Data Inte...","Pig Latin,HiveQL,Apache Spark"
2,2,ZENSAR,NAVI MUMBAI,9751818754,zensar@internship.com,Yes,Work from Home,9.4,8,0,...,Novermber,üî¢Database Engineer,SQL,NaN,"Oracle Database,PostgreSQL,MySQL","Apache NiFi,Python,SQL,Oracle Data Integrator,...","MySQL Workbench,Oracle Enterprise Manager","T-SQL,Oracle Database Vault","SQL Server Integration Services,SQL,PL/SQL","Apache Pig,Pig Latin,Apache Spark,HiveQL"
3,3,DEMATIC,CHENNAI,9898399620,dematic@internship.com,No,Work from office,8.7,8,8,...,June,üî¢Database Engineer,SQL,MySQL,"PostgreSQL,SQL","Python,Apache NiFi,SQL,AWS Database Migration ...","PL/SQL,SQL Server Management Studio,MySQL Work...",NaN,"PL/SQL,SQL Server Integration Services,Oracle ...","Hadoop,Apache Hadoop,HiveQL"
4,4,RENATA PRECISION COMPONENTS PVT.LTD,LATUR,9640747126,renataprecisioncomponentspvt.ltd@internship.com,Yes,Work from Home,6.8,7,7,...,June,üî¢Database Engineer,SQL,NaN,"PostgreSQL,MySQL","Oracle Data Integrator,Python","T-SQL,MySQL Workbench,PL/SQL,Oracle Enterprise...","PL/SQL,MySQL Enterprise Security","T-SQL,Pentaho Data Integration,PL/SQL,SQL,SQL ...",Apache Spark
5,5,SHAPOORJI PALLONJI,HARYANA,9202130747,shapoorjipallonji@internship.com,No,Work from office,6.9,5,6,...,December,üî¢Database Engineer,"SQL,ER Diagrams",NaN,NaN,NaN,"SQL,MySQL Workbench,T-SQL,Oracle Enterprise Ma...","T-SQL,PL/SQL,Microsoft SQL Server Audit,Oracle...","Pentaho Data Integration,PL/SQL,SQL Server Int...","Apache Pig,Apache Hive,Apache Spark,HiveQL,Had..."
6,6,ICICI BANK,JAIPUR,9406361164,icicibank@internship.com,No,Work from office,8.1,4,9,...,December,üî¢Database Engineer,NaN,"PL/SQL,Oracle Database,MySQL,T-SQL,SQL",NaN,"Python,AWS Database Migration Service,Oracle D...","MySQL Workbench,T-SQL,PL/SQL,SQL Server Manage...",MySQL Enterprise Security,"Oracle Warehouse Builder,Pentaho Data Integrat...","Pig Latin,Apache Spark,Apache Pig,HiveQL,Apach..."
7,7,DAR GROUP,CHENNAI,9732827553,dargroup@internship.com,No,Work from Home,9.0,4,8,...,October,üî¢Database Engineer,SQL,"PL/SQL,T-SQL,SQL,PostgreSQL,Oracle Database,SQ...","MySQL,SQL,Oracle Database,PostgreSQL",NaN,"Oracle Enterprise Manager,MySQL Workbench,T-SQL","Oracle Database Vault,T-SQL,MySQL Enterprise S...","Pentaho Data Integration,SQL,SQL Server Integr...","SQL,Apache Pig,Hadoop,Apache Hive"
8,8,TALLY SOLUTIONS,PUNE,9698414663,tallysolutions@internship.com,No,Work from Home,9.9,7,5,...,July,üî¢Database Engineer,ER Diagrams,"PL/SQL,MySQL,SQL Server,SQL","MySQL,Oracle Database,SQL Server,PostgreSQL",NaN,T-SQL,"PL/SQL,Oracle Database Vault,T-SQL","SQL,PL/SQL,Oracle Warehouse Builder","Apache Hive,HiveQL"
9,9,ENERGY MACHINES PVT.LTD,NAVI MUMBAI,9925477770,energymachinespvt.ltd@internship.com,Yes,Work from office,8.6,5,8,...,September,üî¢Database Engineer,NaN,"PostgreSQL,SQL,MySQL,T-SQL,SQL Server,Oracle D...","SQL Server,SQL,MySQL,PostgreSQL,Oracle Database",NaN,NaN,"Oracle Database Vault,T-SQL","Oracle Warehouse Builder,T-SQL,PL/SQL,SQL Serv...",NaN
10,10,EY INDIA,NOIDA,9152555675,eyindia@internship.com,No,Work from office,9.0,9,3,...,October,üî¢Database Engineer,"SQL,ER Diagrams","Oracle Database,PL/SQL,MySQL,T-SQL,SQL","SQL,SQL Server,MySQL,PostgreSQL","AWS Database Migration Service,Apache NiFi,SQL...","MySQL Workbench,PL/SQL,SQL","SQL,MySQL Enterprise Security,T-SQL,Oracle Dat...",NaN,NaN
11,11,ENERGY MACHINES PVT.LTD,PUNE,9069301801,energymachinespvt.ltd@internship.com,Yes,Work from Home,8.0,5,10,...,September,üî¢Database Engineer,"ER Diagrams,SQL",MySQL,SQL Server,"Apache NiFi,AWS Database Migration Service,Ora...","PL/SQL,Oracle Enterprise Manager","SQL,PL/SQL,Oracle Database Vault,Microsoft SQL...","Pentaho Data Integration,Oracle Warehouse Builder","HiveQL,Pig Latin,Apache Hive,Apache Spark,SQL,..."
12,12,FINIQ,NAVI MUMBAI,9882315264,finiq@internship.com,Yes,Work from Home,8.3,3,0,...,July,üî¢Database Engineer,NaN,"Oracle Database,MySQL",NaN,"Apache NiFi,Python,SQL,AWS Database Migration ...",SQL Server Management Studio,"Microsoft SQL Server Audit,Oracle Database Vau...",Oracle Warehouse Builder,NaN
13,13,EBARA CORPORATION,JAIPUR,9268025559,ebaracorporation@internship.com,Yes,Work from Home,8.3,10,10,...,September,üî¢Database Engineer,ER Diagrams,"PostgreSQL,MySQL","SQL,Oracle Database,MySQL","Python,SQL,Oracle Data Integrator",NaN,"MySQL Enterprise Security,Microsoft SQL Server...","SQL Server Integration Services,Pentaho Data I...","HiveQL,Pig Latin,Hadoop,Apache Hadoop"
14,14,EATON,HYDERABAD,9010132610,eaton@internship.com,No,Work from Home,7.7,6,1,...,August,üî¢Database Engineer,"ER Diagrams,SQL",SQL,"Oracle Database,SQL Server,MySQL,PostgreSQL,SQL","Apache NiFi,AWS Database Migration Service,Ora...","SQL Server Management Studio,T-SQL,Oracle Ente...",MySQL Enterprise Security,"Oracle Warehouse Builder,Pentaho Data Integrat...","HiveQL,Apache Hive,SQL,Apache Spark,Apache Pig..."
15,15,09 SOLUTIONS,JAIPUR,9842669529,09solutions@internship.com,No,Work from Home,6.1,2,10,...,August,üî¢Database Engineer,NaN,"T-SQL,SQL Server,PostgreSQL","SQL Server,PostgreSQL,SQL,Oracle Database,MySQL","Python,Apache NiFi","MySQL Workbench,SQL,PL/SQL,T-SQL,SQL Server Ma...","T-SQL,MySQL Enterprise Security,Oracle Databas...","PL/SQL,SQL","HiveQL,Apache Spark,Apache Hive,Pig Latin,Hado..."
16,16,ION GROUP,AHMEDABAD,9441956036,iongroup@internship.com,No,Work from office,7.9,9,5,...,Novermber,üî¢Database Engineer,"SQL,ER Diagrams",NaN,NaN,"Apache NiFi,SQL,Python,AWS Database Migration ...","SQL Server Management Studio,SQL,Oracle Enterp...","Oracle Database Vault,PL/SQL",NaN,"HiveQL,SQL,Hadoop,Apache Hive"
17,17,ACCENTURE,GUJARAT,9643807376,accenture@internship.com,No,Work from office,10.0,5,10,...,October,üî¢Database Engineer,NaN,PL/SQL,"SQL Server,MySQL","Python,Oracle Data Integrator,AWS Database Mig...","T-SQL,SQL Server Management Studio,Oracle Ente...","T-SQL,MySQL Enterprise Security,PL/SQL","T-SQL,Oracle Warehouse Builder,Pentaho Data In...",Apache Hive
18,18,SKF INDIA,HYDERABAD,9595439645,skfindia@internship.com,No,Work from office,8.8,8,2,...,August,üî¢Database Engineer,SQL,"T-SQL,PostgreSQL,SQL,Oracle Database,MySQL,SQL...",NaN,"SQL,Oracle Data Integrator","Oracle Enterprise Manager,SQL,T-SQL,MySQL Work...",NaN,"T-SQL,Pentaho Data Integration,PL/SQL,SQL Serv...","SQL,HiveQL,Apache Hadoop,Apache Hive,Hadoop,Ap..."
19,19,TATA AUTOCOMP SYSTEMS,JAPAN,9061509231,tataautocompsystems@internship.com,No,Work from office,9.9,2,7,...,October,üî¢Database Engineer,NaN,"MySQL,Oracle Database,SQL,PostgreSQL,T-SQL","Oracle Database,SQL,PostgreSQL","AWS Database Migration Service,Oracle Data Int...","PL/SQL,Oracle Enterprise Manager,SQL Server Ma...","T-SQL,Oracle Database Vault","Oracle Warehouse Builder,PL/SQL,Pentaho Data I...",Apache Pig
20,20,WHIRLPOOL INDIA,JAPAN,9860626834,whirlpoolindia@internship.com,Yes,Work from Home,7.9,9,5,...,December,üî¢Database Engineer,NaN,"SQL,PL/SQL,Oracle Database,MySQL,SQL Server,Po...",NaN,Oracle Data Integrator,"SQL Server Management Studio,Oracle Enterprise...",Microsoft SQL Server Audit,"SQL,Oracle Warehouse Builder","Hadoop,Apache Pig,Apache Hive,HiveQL,Pig Latin..."
21,21,ADANI GROUP,LATUR,9636591728,adanigroup@internship.com,Yes,Work from office,9.2,8,2,...,September,üî¢Database Engineer,ER Diagrams,"SQL Server,PL/SQL,Oracle Database","Oracle Database,SQL Server,SQL,MySQL,PostgreSQL",NaN,NaN,"T-SQL,MySQL Enterprise Security","Pentaho Data Integration,Oracle Warehouse Buil...","Hadoop,Apache Hadoop"
22,22,MINI ORANGE,NASHIK,9153075272,miniorange@internship.com,No,Work from Home,8.5,2,6,...,October,üî¢Database Engineer,NaN,"PostgreSQL,MySQL,SQL,SQL Server","SQL,MySQL,SQL Server,PostgreSQL,Oracle Database",Python,"MySQL Workbench,SQL,T-SQL,SQL Server Managemen...","Oracle Database Vault,PL/SQL,SQL,Microsoft SQL...","T-SQL,PL/SQL","Apache Pig,Pig Latin,Apache Hive,HiveQL,Apache..."
23,23,LOREAL,JAPAN,9358580293,loreal@internship.com,Yes,Work from Home,6.1,4,7,...,October,üî¢Database Engineer,"SQL,ER Diagrams",NaN,"Oracle Database,PostgreSQL,SQL Server,SQL,MySQL","SQL,Oracle Data Integrator,Python,Apache NiFi",PL/SQL,"T-SQL,SQL,Microsoft SQL Server Audit","Pentaho Data Integration,PL/SQL","Apache Hadoop,Hadoop,Pig Latin,Apache Hive,Apa..."
24,24,PHILIPS,JAIPUR,9641272190,philips@internship.com,No,Work from office,6.1,3,0,...,Novermber,üî¢Database Engineer,"SQL,ER Diagrams",NaN,"SQL Server,MySQL","SQL,Apache NiFi,Python","SQL,PL/SQL,Oracle Enterprise Manager,MySQL Wor...","MySQL Enterprise Security,SQL","Pentaho Data Integration,T-SQL,Oracle Warehous...",NaN
25,25,IDEAS,WALCHAND,9340340657,ideas@internship.com,Yes,Work from office,6.4,0,2,...,Novermber,üî¢Database Engineer,NaN,PostgreSQL,PostgreSQL,Apache NiFi,"PL/SQL,MySQL Workbench,Oracle Enterprise Manag...","Microsoft SQL Server Audit,SQL,MySQL Enterpris...",Pentaho Data Integration,"HiveQL,Apache Pig,Hadoop,Apache Hadoop,Apache ..."
26,26,FEV INDIA,GUJARAT,9173026350,fevindia@internship.com,No,Work from office,7.3,2,1,...,December,üî¢Database Engineer,NaN,NaN,"MySQL,PostgreSQL,SQL Server","SQL,Apache NiFi,Oracle Data Integrator,Python","T-SQL,SQL Server Management Studio,Oracle Ente...","PL/SQL,T-SQL","Oracle Warehouse Builder,SQL,T-SQL,PL/SQL,Pent...","Hadoop,SQL,Apache Hive,Apache Hadoop,Apache Pi..."
27,27,ADM,NAVI MUMBAI,9854362597,adm@internship.com,Yes,Work from office,9.7,1,10,...,December,üî¢Database Engineer,ER Diagrams,"T-SQL,SQL Server,MySQL,PostgreSQL,Oracle Database",MySQL,"Apache NiFi,AWS Database Migration Service,Ora...","SQL Server Management Studio,MySQL Workbench,T...","Microsoft SQL Server Audit,Oracle Database Vau...","SQL Server Integration Services,SQL,PL/SQL","HiveQL,SQL,Pig Latin"
28,28,MICROLAND LTD,BANGALORE,9281056759,microlandltd@internship.com,No,Work from Home,6.7,5,4,...,August,üî¢Database Engineer,SQL,"T-SQL,SQL Server,PostgreSQL,SQL,Oracle Database","SQL,MySQL,Oracle Database,PostgreSQL,SQL Server",Apache NiFi,"SQL,T-SQL,PL/SQL,Oracle Enterprise Manager,MyS...","T-SQL,Microsoft SQL Server Audit","Oracle Warehouse Builder,Pentaho Data Integration","Pig Latin,HiveQL,SQL,Apache Spark,Apache Hadoop"
29,29,SAMSUNG R&D,GUJARAT,9554305979,samsungr&d@internship.com,Yes,Work from office,6.2,10,7,...,December,üî¢Database Engineer,"ER Diagrams,SQL","MySQL,PostgreSQL,SQL,PL/SQL,T-SQL,SQL Server,O...",NaN,"AWS Database Migration Service,Python,Apache N...","SQL Server Management Studio,PL/SQL,MySQL Work...",PL/SQL,NaN,"Hadoop,Apache Pig,Apache Spark,Apache Hadoop,A..."
30,30,SYNOPSYS,GUJARAT,9181238230,synopsys@internship.com,No,Work from Home,7.6,9,8,...,September,üî¢Database Engineer,NaN,"PL/SQL,SQL,T-SQL,Oracle Database,SQL Server","PostgreSQL,MySQL,SQL,SQL Server,Oracle Database","AWS Database Migration Service,Python,SQL,Apac...",NaN,"Oracle Database Vault,T-SQL,SQL,PL/SQL","SQL Server Integration Services,SQL,Pentaho Da...","Hadoop,Apache Hadoop,Pig Latin"
31,31,NBC BEARING,AURANGABAD,9855776637,nbcbearing@internship.com,Yes,Work from Home,7.8,5,9,...,October,üî¢Database Engineer,NaN,"SQL,PostgreSQL","SQL,MySQL","Oracle Data Integrator,Apache NiFi,Python","SQL,T-SQL,PL/SQL,Oracle Enterprise Manager","SQL,T-SQL","PL/SQL,Pentaho Data Integration,SQL,T-SQL","HiveQL,Apache Spark,Pig Latin,Apache Hadoop,Ap..."
32,32,POLESTAR,MUMBAI,9089559357,polestar@internship.com,Yes,Work from office,7.3,0,0,...,Novermber,üî¢Database Engineer,"SQL,ER Diagrams","SQL Server,Oracle Database,MySQL","Oracle Database,PostgreSQL,MySQL,SQL Server,SQL","AWS Database Migration Service,SQL","Oracle Enterprise Manager,SQL Server Managemen...","PL/SQL,T-SQL,Microsoft SQL Server Audit",PL/SQL,"SQL,Apache Hadoop"
33,33,ACCENTURE,HYDERABAD,9339253988,accenture@internship.com,No,Work from Home,8.3,6,6,...,October,üî¢Database Engineer,ER Diagrams,NaN,"PostgreSQL,SQL",Apache NiFi,"PL/SQL,Oracle Enterprise Manager,SQL,T-SQL,SQL...",Oracle Database Vault,"Pentaho Data Integration,SQL","Apache Hive,Apache Spark,Apache Pig,Hadoop,Pig..."
34,34,SEDEMAC,WALCHAND,9172081338,sedemac@internship.com,No,Work from Home,6.8,2,1,...,June,üî¢Database Engineer,ER Diagrams,"SQL,PL/SQL,Oracle Database,T-SQL,PostgreSQL,MySQL",SQL Server,Python,"SQL Server Management Studio,PL/SQL,SQL,T-SQL","Oracle Database Vault,SQL,MySQL Enterprise Sec...","Pentaho Data Integration,SQL Server Integratio...","SQL,Apache Pig,Pig Latin,Apache Spark,HiveQL,A..."
35,35,TETRA PAK,BANGALORE,9753829552,tetrapak@internship.com,Yes,Work from office,6.0,3,8,...,December,üî¢Database Engineer,ER Diagrams,Oracle Database,MySQL,"AWS Database Migration Service,SQL","PL/SQL,T-SQL,MySQL Workbench,Oracle Enterprise...","Oracle Database Vault,T-SQL,SQL,MySQL Enterpri...","Pentaho Data Integration,PL/SQL,SQL Server Int...",NaN
36,36,DAR GROUP,PUNE,9847942384,dargroup@internship.com,Yes,Work from Home,6.1,5,0,...,December,üî¢Database Engineer,NaN,"T-SQL,SQL Server,MySQL,Oracle Database,PL/SQL,...",Oracle Database,"Python,Oracle Data Integrator,AWS Database Mig...","Oracle Enterprise Manager,T-SQL","PL/SQL,Oracle Database Vault,MySQL Enterprise ...",NaN,Apache Spark
37,37,VARROC TECHNICAL CENTRE,LATUR,9163017873,varroctechnicalcentre@internship.com,No,Work from office,8.6,10,2,...,December,üî¢Database Engineer,NaN,"SQL Server,SQL,Oracle Database,PostgreSQL,T-SQ...",NaN,"SQL,Oracle Data Integrator,Python,AWS Database...","SQL Server Management Studio,T-SQL,MySQL Workb...","PL/SQL,MySQL Enterprise Security,Oracle Databa...","SQL,Pentaho Data Integration,Oracle Warehouse ...","Apache Spark,SQL,Apache Hive,HiveQL"
38,38,WELLS FARGO,GUJARAT,9811601601,wellsfargo@internship.com,Yes,Work from office,7.4,8,10,...,August,üî¢Database Engineer,NaN,SQL Server,SQL Server,"SQL,Oracle Data Integrator,Python,AWS Database...","SQL Server Management Studio,Oracle Enterprise...","SQL,PL/SQL,T-SQL,MySQL Enterprise Security,Ora...",Pentaho Data Integration,"Hadoop,Apache Pig,Pig Latin,Apache Hadoop,Apac..."
39,39,ZS ASSOCIATES,NAVI MUMBAI,9941368696,zsassociates@internship.com,Yes,Work from office,8.8,0,10,...,June,üî¢Database Engineer,NaN,"MySQL,SQL Server",NaN,"AWS Database Migration Service,SQL,Apache NiFi...","SQL,MySQL Workbench,SQL Server Management Studio","PL/SQL,MySQL Enterprise Security,T-SQL,Oracle ...","SQL Server Integration Services,PL/SQL,T-SQL,O...",NaN
40,40,BELDEN INDIA,AURANGABAD,9784039544,beldenindia@internship.com,Yes,Work from office,6.6,5,10,...,August,üî¢Database Engineer,NaN,"T-SQL,PL/SQL","MySQL,SQL Server,Oracle Database,PostgreSQL,SQL",SQL,"T-SQL,SQL Server Management Studio,Oracle Ente...","MySQL Enterprise Security,Oracle Database Vaul...","PL/SQL,Oracle Warehouse Builder,SQL Server Int...",SQL
41,41,FAURECIA,PUNE,9970664952,faurecia@internship.com,Yes,Work from Home,9.9,0,4,...,October,üî¢Database Engineer,"ER Diagrams,SQL",PostgreSQL,"PostgreSQL,SQL,Oracle Database,SQL Server","Oracle Data Integrator,SQL,Python,Apache NiFi",T-SQL,"Oracle Database Vault,SQL,MySQL Enterprise Sec...",NaN,"Apache Hadoop,Hadoop,SQL,Apache Pig,HiveQL,Apa..."
42,42,PRECON SERVICES,MUMBAI,9692532461,preconservices@internship.com,Yes,Work from office,9.0,10,2,...,Novermber,üî¢Database Engineer,SQL,"PostgreSQL,SQL Server,Oracle Database,T-SQL",NaN,"AWS Database Migration Service,Python,Oracle D...",NaN,"Microsoft SQL Server Audit,SQL,PL/SQL","T-SQL,SQL,PL/SQL,Pentaho Data Integration","Hadoop,Pig Latin,SQL,Apache Spark"
43,43,HINDUSTAN UNIVER,NASHIK,9879784411,hindustanuniver@internship.com,Yes,Work from office,7.0,2,9,...,Novermber,üî¢Database Engineer,NaN,"Oracle Database,PL/SQL,T-SQL",MySQL,Oracle Data Integrator,NaN,"Oracle Database Vault,PL/SQL,Microsoft SQL Ser...","Oracle Warehouse Builder,Pentaho Data Integrat...","HiveQL,Apache Hadoop,Apache Pig,Pig Latin"
44,44,MICROLAND LTD,AURANGABAD,9017441306,microlandltd@internship.com,No,Work from Home,8.1,1,8,...,June,üî¢Database Engineer,"SQL,ER Diagrams",NaN,"MySQL,PostgreSQL","Oracle Data Integrator,AWS Database Migration ...","Oracle Enterprise Manager,MySQL Workbench,SQL ...",NaN,"PL/SQL,SQL,Oracle Warehouse Builder,Pentaho Da...","Apache Spark,Apache Hive,HiveQL,Apache Pig,Had..."
45,45,RENISHAW,KOLKATA,9501184353,renishaw@internship.com,No,Work from office,9.8,10,4,...,December,üî¢Database Engineer,"SQL,ER Diagrams",PL/SQL,"PostgreSQL,Oracle Database","AWS Database Migration Service,Oracle Data Int...","SQL Server Management Studio,Oracle Enterprise...","T-SQL,Microsoft SQL Server Audit,Oracle Databa...","SQL Server Integration Services,Pentaho Data I...",Apache Hadoop
46,46,GOLDMAN SACHS,MUMBAI,9639321142,goldmansachs@internship.com,No,Work from office,7.7,1,3,...,August,üî¢Database Engineer,SQL,Oracle Database,"MySQL,PostgreSQL,Oracle Database,SQL","Oracle Data Integrator,Python,SQL","T-SQL,MySQL Workbench,Oracle Enterprise Manage...",NaN,"PL/SQL,SQL Server Integration Services","Apache Hadoop,Apache Hive,Pig Latin,Hadoop,Apa..."
47,47,MICROLAND LTD,NOIDA,9463825157,microlandltd@internship.com,Yes,Work from office,8.7,8,6,...,Novermber,üî¢Database Engineer,"ER Diagrams,SQL","SQL,PL/SQL,PostgreSQL,SQL Server,Oracle Databa...","Oracle Database,SQL Server,MySQL,PostgreSQL,SQL",NaN,"Oracle Enterprise Manager,SQL Server Managemen...",NaN,SQL,NaN
48,48,CADENCE,GURGAON,9447395290,cadence@internship.com,Yes,Work from office,9.7,3,7,...,August,üî¢Database Engineer,NaN,"T-SQL,SQL Server,PL/SQL,Oracle Database",NaN,"Python,Oracle Data Integrator,Apache NiFi,SQL,...","SQL,MySQL Workbench,T-SQL,Oracle Enterprise Ma...","Oracle Database Vault,Microsoft SQL Server Aud...","PL/SQL,Oracle Warehouse Builder,SQL Server Int...",Apache Hadoop
49,49,TATA CONSULTANCY ENGINEERS,LATUR,9825333933,tataconsultancyengineers@internship.com,Yes,Work from office,7.3,6,7,...,Novermber,üî¢Database Engineer,NaN,"PostgreSQL,PL/SQL",NaN,"AWS Database Migration Service,SQL,Apache NiFi...","SQL,PL/SQL",NaN,SQL,"SQL,Hadoop,Apache Hive,HiveQL,Pig Latin,Apache..."
50,50,TCS XPLORE,BANGALORE,9594437435,tcsxplore@internship.com,Yes,Work from office,6.0,10,7,...,October,üî¢Database Engineer,"ER Diagrams,SQL","Oracle Database,T-SQL,MySQL,PostgreSQL,SQL","SQL Server,MySQL,SQL",NaN,"PL/SQL,MySQL Workbench",Microsoft SQL Server Audit,T-SQL,"SQL,Apache Spark"
51,51,FAURECIA,CHENNAI,9942399593,faurecia@internship.com,No,Work from office,8.3,6,2,...,July,üî¢Database Engineer,"SQL,ER Diagrams","T-SQL,SQL Server,Oracle Database,SQL,PostgreSQ...",NaN,"Python,SQL,AWS Database Migration Service","SQL,Oracle Enterprise Manager","T-SQL,SQL",Pentaho Data Integration,"SQL,Apache Hadoop,Hadoop,Apache Hive,Apache Pig"
52,52,DANA INDIA,JAIPUR,9946358792,danaindia@internship.com,No,Work from office,10.0,0,4,...,July,üî¢Database Engineer,"ER Diagrams,SQL",NaN,"SQL Server,MySQL,PostgreSQL",NaN,"Oracle Enterprise Manager,T-SQL",NaN,"SQL,Oracle Warehouse Builder,SQL Server Integr...","Apache Spark,SQL"

In [21]:
modified_dbms_df=dbms_df.drop(['Unnamed: 0','Address of company', 'Phone Number',
       'Email Address', 'Previous Visited COEP'],axis=1)
modified_dbms_df

,Name of company,Work Mode,Min CGPA,Seats for Boys,Seats for Girls,Number of Dead Backlogs permitted,Number of Active Backlogs permitted,Preffered month of visiting campus,Domain to Hire,Database Design,Datbase Development,Database Administration,Database Migration,Database Performance Tuning,Database Security,Data Warehousing,Big Data
0,CION DIGITAL,Work from office,9.1,5,8,0,1,July,üî¢Database Engineer,"ER Diagrams,SQL","MySQL,SQL Server,SQL,PL/SQL,Oracle Database,T-...",PostgreSQL,"Oracle Data Integrator,SQL","MySQL Workbench,PL/SQL","SQL,Microsoft SQL Server Audit,MySQL Enterpris...","PL/SQL,SQL Server Integration Services,SQL,Ora...","SQL,Pig Latin,HiveQL"
1,CENTRIO,Work from Home,7.6,4,0,2,1,October,üî¢Database Engineer,"ER Diagrams,SQL",NaN,"Oracle Database,SQL Server",Apache NiFi,"PL/SQL,MySQL Workbench,Oracle Enterprise Manag...","PL/SQL,T-SQL,SQL","SQL,Oracle Warehouse Builder,Pentaho Data Inte...","Pig Latin,HiveQL,Apache Spark"
2,ZENSAR,Work from Home,9.4,8,0,1,1,Novermber,üî¢Database Engineer,SQL,NaN,"Oracle Database,PostgreSQL,MySQL","Apache NiFi,Python,SQL,Oracle Data Integrator,...","MySQL Workbench,Oracle Enterprise Manager","T-SQL,Oracle Database Vault","SQL Server Integration Services,SQL,PL/SQL","Apache Pig,Pig Latin,Apache Spark,HiveQL"
3,DEMATIC,Work from office,8.7,8,8,0,2,June,üî¢Database Engineer,SQL,MySQL,"PostgreSQL,SQL","Python,Apache NiFi,SQL,AWS Database Migration ...","PL/SQL,SQL Server Management Studio,MySQL Work...",NaN,"PL/SQL,SQL Server Integration Services,Oracle ...","Hadoop,Apache Hadoop,HiveQL"
4,RENATA PRECISION COMPONENTS PVT.LTD,Work from Home,6.8,7,7,0,1,June,üî¢Database Engineer,SQL,NaN,"PostgreSQL,MySQL","Oracle Data Integrator,Python","T-SQL,MySQL Workbench,PL/SQL,Oracle Enterprise...","PL/SQL,MySQL Enterprise Security","T-SQL,Pentaho Data Integration,PL/SQL,SQL,SQL ...",Apache Spark
5,SHAPOORJI PALLONJI,Work from office,6.9,5,6,0,2,December,üî¢Database Engineer,"SQL,ER Diagrams",NaN,NaN,NaN,"SQL,MySQL Workbench,T-SQL,Oracle Enterprise Ma...","T-SQL,PL/SQL,Microsoft SQL Server Audit,Oracle...","Pentaho Data Integration,PL/SQL,SQL Server Int...","Apache Pig,Apache Hive,Apache Spark,HiveQL,Had..."
6,ICICI BANK,Work from office,8.1,4,9,2,0,December,üî¢Database Engineer,NaN,"PL/SQL,Oracle Database,MySQL,T-SQL,SQL",NaN,"Python,AWS Database Migration Service,Oracle D...","MySQL Workbench,T-SQL,PL/SQL,SQL Server Manage...",MySQL Enterprise Security,"Oracle Warehouse Builder,Pentaho Data Integrat...","Pig Latin,Apache Spark,Apache Pig,HiveQL,Apach..."
7,DAR GROUP,Work from Home,9.0,4,8,2,0,October,üî¢Database Engineer,SQL,"PL/SQL,T-SQL,SQL,PostgreSQL,Oracle Database,SQ...","MySQL,SQL,Oracle Database,PostgreSQL",NaN,"Oracle Enterprise Manager,MySQL Workbench,T-SQL","Oracle Database Vault,T-SQL,MySQL Enterprise S...","Pentaho Data Integration,SQL,SQL Server Integr...","SQL,Apache Pig,Hadoop,Apache Hive"
8,TALLY SOLUTIONS,Work from Home,9.9,7,5,0,2,July,üî¢Database Engineer,ER Diagrams,"PL/SQL,MySQL,SQL Server,SQL","MySQL,Oracle Database,SQL Server,PostgreSQL",NaN,T-SQL,"PL/SQL,Oracle Database Vault,T-SQL","SQL,PL/SQL,Oracle Warehouse Builder","Apache Hive,HiveQL"
9,ENERGY MACHINES PVT.LTD,Work from office,8.6,5,8,0,0,September,üî¢Database Engineer,NaN,"PostgreSQL,SQL,MySQL,T-SQL,SQL Server,Oracle D...","SQL Server,SQL,MySQL,PostgreSQL,Oracle Database",NaN,NaN,"Oracle Database Vault,T-SQL","Oracle Warehouse Builder,T-SQL,PL/SQL,SQL Serv...",NaN
10,EY INDIA,Work from office,9.0,9,3,1,2,October,üî¢Database Engineer,"SQL,ER Diagrams","Oracle Database,PL/SQL,MySQL,T-SQL,SQL","SQL,SQL Server,MySQL,PostgreSQL","AWS Database Migration Service,Apache NiFi,SQL...","MySQL Workbench,PL/SQL,SQL","SQL,MySQL Enterprise Security,T-SQL,Oracle Dat...",NaN,NaN
11,ENERGY MACHINES PVT.LTD,Work from Home,8.0,5,10,2,1,September,üî¢Database Engineer,"ER Diagrams,SQL",MySQL,SQL Server,"Apache NiFi,AWS Database Migration Service,Ora...","PL/SQL,Oracle Enterprise Manager","SQL,PL/SQL,Oracle Database Vault,Microsoft SQL...","Pentaho Data Integration,Oracle Warehouse Builder","HiveQL,Pig Latin,Apache Hive,Apache Spark,SQL,..."
12,FINIQ,Work from Home,8.3,3,0,2,1,July,üî¢Database Engineer,NaN,"Oracle Database,MySQL",NaN,"Apache NiFi,Python,SQL,AWS Database Migration ...",SQL Server Management Studio,"Microsoft SQL Server Audit,Oracle Database Vau...",Oracle Warehouse Builder,NaN
13,EBARA CORPORATION,Work from Home,8.3,10,10,1,1,September,üî¢Database Engineer,ER Diagrams,"PostgreSQL,MySQL","SQL,Oracle Database,MySQL","Python,SQL,Oracle Data Integrator",NaN,"MySQL Enterprise Security,Microsoft SQL Server...","SQL Server Integration Services,Pentaho Data I...","HiveQL,Pig Latin,Hadoop,Apache Hadoop"
14,EATON,Work from Home,7.7,6,1,0,0,August,üî¢Database Engineer,"ER Diagrams,SQL",SQL,"Oracle Database,SQL Server,MySQL,PostgreSQL,SQL","Apache NiFi,AWS Database Migration Service,Ora...","SQL Server Management Studio,T-SQL,Oracle Ente...",MySQL Enterprise Security,"Oracle Warehouse Builder,Pentaho Data Integrat...","HiveQL,Apache Hive,SQL,Apache Spark,Apache Pig..."
15,09 SOLUTIONS,Work from Home,6.1,2,10,2,0,August,üî¢Database Engineer,NaN,"T-SQL,SQL Server,PostgreSQL","SQL Server,PostgreSQL,SQL,Oracle Database,MySQL","Python,Apache NiFi","MySQL Workbench,SQL,PL/SQL,T-SQL,SQL Server Ma...","T-SQL,MySQL Enterprise Security,Oracle Databas...","PL/SQL,SQL","HiveQL,Apache Spark,Apache Hive,Pig Latin,Hado..."
16,ION GROUP,Work from office,7.9,9,5,1,1,Novermber,üî¢Database Engineer,"SQL,ER Diagrams",NaN,NaN,"Apache NiFi,SQL,Python,AWS Database Migration ...","SQL Server Management Studio,SQL,Oracle Enterp...","Oracle Database Vault,PL/SQL",NaN,"HiveQL,SQL,Hadoop,Apache Hive"
17,ACCENTURE,Work from office,10.0,5,10,0,2,October,üî¢Database Engineer,NaN,PL/SQL,"SQL Server,MySQL","Python,Oracle Data Integrator,AWS Database Mig...","T-SQL,SQL Server Management Studio,Oracle Ente...","T-SQL,MySQL Enterprise Security,PL/SQL","T-SQL,Oracle Warehouse Builder,Pentaho Data In...",Apache Hive
18,SKF INDIA,Work from office,8.8,8,2,1,0,August,üî¢Database Engineer,SQL,"T-SQL,PostgreSQL,SQL,Oracle Database,MySQL,SQL...",NaN,"SQL,Oracle Data Integrator","Oracle Enterprise Manager,SQL,T-SQL,MySQL Work...",NaN,"T-SQL,Pentaho Data Integration,PL/SQL,SQL Serv...","SQL,HiveQL,Apache Hadoop,Apache Hive,Hadoop,Ap..."
19,TATA AUTOCOMP SYSTEMS,Work from office,9.9,2,7,1,0,October,üî¢Database Engineer,NaN,"MySQL,Oracle Database,SQL,PostgreSQL,T-SQL","Oracle Database,SQL,PostgreSQL","AWS Database Migration Service,Oracle Data Int...","PL/SQL,Oracle Enterprise Manager,SQL Server Ma...","T-SQL,Oracle Database Vault","Oracle Warehouse Builder,PL/SQL,Pentaho Data I...",Apache Pig
20,WHIRLPOOL INDIA,Work from Home,7.9,9,5,0,1,December,üî¢Database Engineer,NaN,"SQL,PL/SQL,Oracle Database,MySQL,SQL Server,Po...",NaN,Oracle Data Integrator,"SQL Server Management Studio,Oracle Enterprise...",Microsoft SQL Server Audit,"SQL,Oracle Warehouse Builder","Hadoop,Apache Pig,Apache Hive,HiveQL,Pig Latin..."
21,ADANI GROUP,Work from office,9.2,8,2,0,2,September,üî¢Database Engineer,ER Diagrams,"SQL Server,PL/SQL,Oracle Database","Oracle Database,SQL Server,SQL,MySQL,PostgreSQL",NaN,NaN,"T-SQL,MySQL Enterprise Security","Pentaho Data Integration,Oracle Warehouse Buil...","Hadoop,Apache Hadoop"
22,MINI ORANGE,Work from Home,8.5,2,6,0,0,October,üî¢Database Engineer,NaN,"PostgreSQL,MySQL,SQL,SQL Server","SQL,MySQL,SQL Server,PostgreSQL,Oracle Database",Python,"MySQL Workbench,SQL,T-SQL,SQL Server Managemen...","Oracle Database Vault,PL/SQL,SQL,Microsoft SQL...","T-SQL,PL/SQL","Apache Pig,Pig Latin,Apache Hive,HiveQL,Apache..."
23,LOREAL,Work from Home,6.1,4,7,2,1,October,üî¢Database Engineer,"SQL,ER Diagrams",NaN,"Oracle Database,PostgreSQL,SQL Server,SQL,MySQL","SQL,Oracle Data Integrator,Python,Apache NiFi",PL/SQL,"T-SQL,SQL,Microsoft SQL Server Audit","Pentaho Data Integration,PL/SQL","Apache Hadoop,Hadoop,Pig Latin,Apache Hive,Apa..."
24,PHILIPS,Work from office,6.1,3,0,0,0,Novermber,üî¢Database Engineer,"SQL,ER Diagrams",NaN,"SQL Server,MySQL","SQL,Apache NiFi,Python","SQL,PL/SQL,Oracle Enterprise Manager,MySQL Wor...","MySQL Enterprise Security,SQL","Pentaho Data Integration,T-SQL,Oracle Warehous...",NaN
25,IDEAS,Work from office,6.4,0,2,0,0,Novermber,üî¢Database Engineer,NaN,PostgreSQL,PostgreSQL,Apache NiFi,"PL/SQL,MySQL Workbench,Oracle Enterprise Manag...","Microsoft SQL Server Audit,SQL,MySQL Enterpris...",Pentaho Data Integration,"HiveQL,Apache Pig,Hadoop,Apache Hadoop,Apache ..."
26,FEV INDIA,Work from office,7.3,2,1,1,2,December,üî¢Database Engineer,NaN,NaN,"MySQL,PostgreSQL,SQL Server","SQL,Apache NiFi,Oracle Data Integrator,Python","T-SQL,SQL Server Management Studio,Oracle Ente...","PL/SQL,T-SQL","Oracle Warehouse Builder,SQL,T-SQL,PL/SQL,Pent...","Hadoop,SQL,Apache Hive,Apache Hadoop,Apache Pi..."
27,ADM,Work from office,9.7,1,10,2,1,December,üî¢Database Engineer,ER Diagrams,"T-SQL,SQL Server,MySQL,PostgreSQL,Oracle Database",MySQL,"Apache NiFi,AWS Database Migration Service,Ora...","SQL Server Management Studio,MySQL Workbench,T...","Microsoft SQL Server Audit,Oracle Database Vau...","SQL Server Integration Services,SQL,PL/SQL","HiveQL,SQL,Pig Latin"
28,MICROLAND LTD,Work from Home,6.7,5,4,0,2,August,üî¢Database Engineer,SQL,"T-SQL,SQL Server,PostgreSQL,SQL,Oracle Database","SQL,MySQL,Oracle Database,PostgreSQL,SQL Server",Apache NiFi,"SQL,T-SQL,PL/SQL,Oracle Enterprise Manager,MyS...","T-SQL,Microsoft SQL Server Audit","Oracle Warehouse Builder,Pentaho Data Integration","Pig Latin,HiveQL,SQL,Apache Spark,Apache Hadoop"
29,SAMSUNG R&D,Work from office,6.2,10,7,1,2,December,üî¢Database Engineer,"ER Diagrams,SQL","MySQL,PostgreSQL,SQL,PL/SQL,T-SQL,SQL Server,O...",NaN,"AWS Database Migration Service,Python,Apache N...","SQL Server Management Studio,PL/SQL,MySQL Work...",PL/SQL,NaN,"Hadoop,Apache Pig,Apache Spark,Apache Hadoop,A..."
30,SYNOPSYS,Work from Home,7.6,9,8,1,0,September,üî¢Database Engineer,NaN,"PL/SQL,SQL,T-SQL,Oracle Database,SQL Server","PostgreSQL,MySQL,SQL,SQL Server,Oracle Database","AWS Database Migration Service,Python,SQL,Apac...",NaN,"Oracle Database Vault,T-SQL,SQL,PL/SQL","SQL Server Integration Services,SQL,Pentaho Da...","Hadoop,Apache Hadoop,Pig Latin"
31,NBC BEARING,Work from Home,7.8,5,9,0,1,October,üî¢Database Engineer,NaN,"SQL,PostgreSQL","SQL,MySQL","Oracle Data Integrator,Apache NiFi,Python","SQL,T-SQL,PL/SQL,Oracle Enterprise Manager","SQL,T-SQL","PL/SQL,Pentaho Data Integration,SQL,T-SQL","HiveQL,Apache Spark,Pig Latin,Apache Hadoop,Ap..."
32,POLESTAR,Work from office,7.3,0,0,2,1,Novermber,üî¢Database Engineer,"SQL,ER Diagrams","SQL Server,Oracle Database,MySQL","Oracle Database,PostgreSQL,MySQL,SQL Server,SQL","AWS Database Migration Service,SQL","Oracle Enterprise Manager,SQL Server Managemen...","PL/SQL,T-SQL,Microsoft SQL Server Audit",PL/SQL,"SQL,Apache Hadoop"
33,ACCENTURE,Work from Home,8.3,6,6,0,1,October,üî¢Database Engineer,ER Diagrams,NaN,"PostgreSQL,SQL",Apache NiFi,"PL/SQL,Oracle Enterprise Manager,SQL,T-SQL,SQL...",Oracle Database Vault,"Pentaho Data Integration,SQL","Apache Hive,Apache Spark,Apache Pig,Hadoop,Pig..."
34,SEDEMAC,Work from Home,6.8,2,1,1,2,June,üî¢Database Engineer,ER Diagrams,"SQL,PL/SQL,Oracle Database,T-SQL,PostgreSQL,MySQL",SQL Server,Python,"SQL Server Management Studio,PL/SQL,SQL,T-SQL","Oracle Database Vault,SQL,MySQL Enterprise Sec...","Pentaho Data Integration,SQL Server Integratio...","SQL,Apache Pig,Pig Latin,Apache Spark,HiveQL,A..."
35,TETRA PAK,Work from office,6.0,3,8,2,1,December,üî¢Database Engineer,ER Diagrams,Oracle Database,MySQL,"AWS Database Migration Service,SQL","PL/SQL,T-SQL,MySQL Workbench,Oracle Enterprise...","Oracle Database Vault,T-SQL,SQL,MySQL Enterpri...","Pentaho Data Integration,PL/SQL,SQL Server Int...",NaN
36,DAR GROUP,Work from Home,6.1,5,0,1,2,December,üî¢Database Engineer,NaN,"T-SQL,SQL Server,MySQL,Oracle Database,PL/SQL,...",Oracle Database,"Python,Oracle Data Integrator,AWS Database Mig...","Oracle Enterprise Manager,T-SQL","PL/SQL,Oracle Database Vault,MySQL Enterprise ...",NaN,Apache Spark
37,VARROC TECHNICAL CENTRE,Work from office,8.6,10,2,1,1,December,üî¢Database Engineer,NaN,"SQL Server,SQL,Oracle Database,PostgreSQL,T-SQ...",NaN,"SQL,Oracle Data Integrator,Python,AWS Database...","SQL Server Management Studio,T-SQL,MySQL Workb...","PL/SQL,MySQL Enterprise Security,Oracle Databa...","SQL,Pentaho Data Integration,Oracle Warehouse ...","Apache Spark,SQL,Apache Hive,HiveQL"
38,WELLS FARGO,Work from office,7.4,8,10,2,0,August,üî¢Database Engineer,NaN,SQL Server,SQL Server,"SQL,Oracle Data Integrator,Python,AWS Database...","SQL Server Management Studio,Oracle Enterprise...","SQL,PL/SQL,T-SQL,MySQL Enterprise Security,Ora...",Pentaho Data Integration,"Hadoop,Apache Pig,Pig Latin,Apache Hadoop,Apac..."
39,ZS ASSOCIATES,Work from office,8.8,0,10,2,0,June,üî¢Database Engineer,NaN,"MySQL,SQL Server",NaN,"AWS Database Migration Service,SQL,Apache NiFi...","SQL,MySQL Workbench,SQL Server Management Studio","PL/SQL,MySQL Enterprise Security,T-SQL,Oracle ...","SQL Server Integration Services,PL/SQL,T-SQL,O...",NaN
40,BELDEN INDIA,Work from office,6.6,5,10,2,2,August,üî¢Database Engineer,NaN,"T-SQL,PL/SQL","MySQL,SQL Server,Oracle Database,PostgreSQL,SQL",SQL,"T-SQL,SQL Server Management Studio,Oracle Ente...","MySQL Enterprise Security,Oracle Database Vaul...","PL/SQL,Oracle Warehouse Builder,SQL Server Int...",SQL
41,FAURECIA,Work from Home,9.9,0,4,0,2,October,üî¢Database Engineer,"ER Diagrams,SQL",PostgreSQL,"PostgreSQL,SQL,Oracle Database,SQL Server","Oracle Data Integrator,SQL,Python,Apache NiFi",T-SQL,"Oracle Database Vault,SQL,MySQL Enterprise Sec...",NaN,"Apache Hadoop,Hadoop,SQL,Apache Pig,HiveQL,Apa..."
42,PRECON SERVICES,Work from office,9.0,10,2,2,1,Novermber,üî¢Database Engineer,SQL,"PostgreSQL,SQL Server,Oracle Database,T-SQL",NaN,"AWS Database Migration Service,Python,Oracle D...",NaN,"Microsoft SQL Server Audit,SQL,PL/SQL","T-SQL,SQL,PL/SQL,Pentaho Data Integration","Hadoop,Pig Latin,SQL,Apache Spark"
43,HINDUSTAN UNIVER,Work from office,7.0,2,9,2,1,Novermber,üî¢Database Engineer,NaN,"Oracle Database,PL/SQL,T-SQL",MySQL,Oracle Data Integrator,NaN,"Oracle Database Vault,PL/SQL,Microsoft SQL Ser...","Oracle Warehouse Builder,Pentaho Data Integrat...","HiveQL,Apache Hadoop,Apache Pig,Pig Latin"
44,MICROLAND LTD,Work from Home,8.1,1,8,0,0,June,üî¢Database Engineer,"SQL,ER Diagrams",NaN,"MySQL,PostgreSQL","Oracle Data Integrator,AWS Database Migration ...","Oracle Enterprise Manager,MySQL Workbench,SQL ...",NaN,"PL/SQL,SQL,Oracle Warehouse Builder,Pentaho Da...","Apache Spark,Apache Hive,HiveQL,Apache Pig,Had..."
45,RENISHAW,Work from office,9.8,10,4,2,2,December,üî¢Database Engineer,"SQL,ER Diagrams",PL/SQL,"PostgreSQL,Oracle Database","AWS Database Migration Service,Oracle Data Int...","SQL Server Management Studio,Oracle Enterprise...","T-SQL,Microsoft SQL Server Audit,Oracle Databa...","SQL Server Integration Services,Pentaho Data I...",Apache Hadoop
46,GOLDMAN SACHS,Work from office,7.7,1,3,1,2,August,üî¢Database Engineer,SQL,Oracle Database,"MySQL,PostgreSQL,Oracle Database,SQL","Oracle Data Integrator,Python,SQL","T-SQL,MySQL Workbench,Oracle Enterprise Manage...",NaN,"PL/SQL,SQL Server Integration Services","Apache Hadoop,Apache Hive,Pig Latin,Hadoop,Apa..."
47,MICROLAND LTD,Work from office,8.7,8,6,2,0,Novermber,üî¢Database Engineer,"ER Diagrams,SQL","SQL,PL/SQL,PostgreSQL,SQL Server,Oracle Databa...","Oracle Database,SQL Server,MySQL,PostgreSQL,SQL",NaN,"Oracle Enterprise Manager,SQL Server Managemen...",NaN,SQL,NaN
48,CADENCE,Work from office,9.7,3,7,0,0,August,üî¢Database Engineer,NaN,"T-SQL,SQL Server,PL/SQL,Oracle Database",NaN,"Python,Oracle Data Integrator,Apache NiFi,SQL,...","SQL,MySQL Workbench,T-SQL,Oracle Enterprise Ma...","Oracle Database Vault,Microsoft SQL Server Aud...","PL/SQL,Oracle Warehouse Builder,SQL Server Int...",Apache Hadoop
49,TATA CONSULTANCY ENGINEERS,Work from office,7.3,6,7,1,1,Novermber,üî¢Database Engineer,NaN,"PostgreSQL,PL/SQL",NaN,"AWS Database Migration Service,SQL,Apache NiFi...","SQL,PL/SQL",NaN,SQL,"SQL,Hadoop,Apache Hive,HiveQL,Pig Latin,Apache..."
50,TCS XPLORE,Work from office,6.0,10,7,0,2,October,üî¢Database Engineer,"ER Diagrams,SQL","Oracle Database,T-SQL,MySQL,PostgreSQL,SQL","SQL Server,MySQL,SQL",NaN,"PL/SQL,MySQL Workbench",Microsoft SQL Server Audit,T-SQL,"SQL,Apache Spark"
51,FAURECIA,Work from office,8.3,6,2,1,2,July,üî¢Database Engineer,"SQL,ER Diagrams","T-SQL,SQL Server,Oracle Database,SQL,PostgreSQ...",NaN,"Python,SQL,AWS Database Migration Service","SQL,Oracle Enterprise Manager","T-SQL,SQL",Pentaho Data Integration,"SQL,Apache Hadoop,Hadoop,Apache Hive,Apache Pig"
52,DANA INDIA,Work from office,10.0,0,4,0,1,July,üî¢Database Engineer,"ER Diagrams,SQL",NaN,"SQL Server,MySQL,PostgreSQL",NaN,"Oracle Enterprise Manager,T-SQL",NaN,"SQL,Oracle Warehouse Builder,SQL Server Integr...","Apache Spark,SQL"

In [22]:
modified_dbms_df.to_csv("~\Desktop\RPOOPS\Mini Project\Part_B\Final_Data\Final_dbms_data.csv")

In [23]:
devops_df=pd.read_csv("~\Desktop\RPOOPS\Mini Project\Part_B\Raw_Data_Generated\Raw_devops_data.csv")
devops_df

,Unnamed: 0,Name of company,Address of company,Phone Number,Email Address,Previous Visited COEP,Work Mode,Min CGPA,Seats for Boys,Seats for Girls,...,Number of Active Backlogs permitted,Preffered month of visiting campus,Domain to Hire,Version Control,Continuous Integration,Configuration Management,Containerization,Continuous Deployment,Monitoring and Logging,Collaboration and Communication
0,0,SHAH TECHNICAL CONSULTANTS PVT.LTD,NASHIK,9641665012,shahtechnicalconsultantspvt.ltd@internship.com,No,Work from office,9.9,10,0,...,0,October,üë®‚ÄçüíªDevops Engineer,"GitHub,GitLab,Bitbucket,Git","Ruby,Groovy,Jenkins,Python,Travis CI,Java,Circ...","Puppet,YAML,Ansible,Chef",NaN,"Python,YAML,Chef,Ansible","Python,Ruby,Nagios,Grafana,Prometheus,YAML,ELK...","Microsoft Teams,Slack,Jira,Trello"
1,1,SHAPOORJI PALLONJI,GUJARAT,9211992133,shapoorjipallonji@internship.com,No,Work from Home,8.5,8,2,...,2,July,üë®‚ÄçüíªDevops Engineer,"GitLab,GitHub,Bitbucket,Git","Ruby,Groovy,Jenkins,Travis CI,CircleCI","Chef,Ansible,YAML,Puppet","Kubernetes,Docker,Docker Compose,Helm","Chef,Ruby,YAML,Ansible,Python,Puppet","Java,Ruby,YAML","Trello,Jira,Slack,Microsoft Teams"
2,2,ICICI SECURITIES,WALCHAND,9019088258,icicisecurities@internship.com,Yes,Work from office,8.5,3,10,...,1,August,üë®‚ÄçüíªDevops Engineer,"GitHub,Bitbucket","Java,Ruby,Groovy,Travis CI","Python,Ruby,Ansible,Puppet,YAML,Chef","Docker Compose,Helm,Docker,Kubernetes","YAML,Ruby",NaN,NaN
3,3,TATA TECHNOLOGIES,GUJARAT,9116720137,tatatechnologies@internship.com,No,Work from office,7.1,5,4,...,1,October,üë®‚ÄçüíªDevops Engineer,NaN,"CircleCI,Travis CI,Java,Jenkins,Groovy,Ruby","Ansible,YAML",Helm,NaN,"Prometheus,YAML,ELK stack,Java",Trello
4,4,TEJAS NETWORKS,MUMBAI,9068646915,tejasnetworks@internship.com,No,Work from Home,7.9,7,3,...,0,September,üë®‚ÄçüíªDevops Engineer,"GitHub,Bitbucket","Ruby,Groovy,Travis CI,Java,Jenkins,CircleCI,Py...",Chef,"Docker,Helm,Docker Compose,Kubernetes","Python,Chef,Puppet,YAML,Ansible,Ruby","ELK stack,Java,YAML,Python,Prometheus,Nagios",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,66,ARMSTRONG AUTOMATION,HARYANA,9034632990,armstrongautomation@internship.com,No,Work from Home,6.1,10,2,...,2,August,üë®‚ÄçüíªDevops Engineer,"GitHub,Bitbucket","Python,Travis CI","Chef,YAML,Ansible,Ruby,Puppet","Docker Compose,Helm",NaN,Prometheus,"Jira,Microsoft Teams,Slack"
67,67,SOC GEN,PUNE,9535801817,socgen@internship.com,No,Work from office,9.2,10,5,...,0,August,üë®‚ÄçüíªDevops Engineer,GitLab,"Ruby,CircleCI,Groovy,Python","Puppet,Chef,Ruby","Kubernetes,Docker,Helm,Docker Compose",NaN,"Nagios,Ruby,Grafana,Java,Python,Prometheus,ELK...",NaN
68,68,CITI CORPORATION,BANGALORE,9529918804,citicorporation@internship.com,No,Work from Home,7.4,5,4,...,2,June,üë®‚ÄçüíªDevops Engineer,NaN,NaN,"Puppet,Python,Chef","Kubernetes,Docker Compose,Docker",NaN,Ruby,NaN
69,69,SOC GEN,JAIPUR,9891323544,socgen@internship.com,No,Work from office,7.6,7,6,...,1,June,üë®‚ÄçüíªDevops Engineer,"Bitbucket,GitLab,Git,GitHub","Python,Jenkins,CircleCI,Travis CI,Java",Python,Docker Compose,"Chef,Python,YAML,Ansible","Java,Ruby,Python,ELK stack","Jira,Trello"
70,70,SHAPOORJI PALLONJI,JAPAN,9846347012,shapoorjipallonji@internship.com,Yes,Work from office,9.5,7,2,...,0,October,üë®‚ÄçüíªDevops Engineer,"GitHub,GitLab,Git","CircleCI,Python,Jenkins,Groovy","Ruby,Ansible,Chef,Python",NaN,"Ansible,Ruby,YAML","Python,Ruby,Nagios","Microsoft Teams,Jira"

In [24]:
modified_devops_df=devops_df.drop(['Unnamed: 0','Address of company', 'Phone Number',
       'Email Address', 'Previous Visited COEP'],axis=1)
modified_devops_df

,Name of company,Work Mode,Min CGPA,Seats for Boys,Seats for Girls,Number of Dead Backlogs permitted,Number of Active Backlogs permitted,Preffered month of visiting campus,Domain to Hire,Version Control,Continuous Integration,Configuration Management,Containerization,Continuous Deployment,Monitoring and Logging,Collaboration and Communication
0,SHAH TECHNICAL CONSULTANTS PVT.LTD,Work from office,9.9,10,0,1,0,October,üë®‚ÄçüíªDevops Engineer,"GitHub,GitLab,Bitbucket,Git","Ruby,Groovy,Jenkins,Python,Travis CI,Java,Circ...","Puppet,YAML,Ansible,Chef",NaN,"Python,YAML,Chef,Ansible","Python,Ruby,Nagios,Grafana,Prometheus,YAML,ELK...","Microsoft Teams,Slack,Jira,Trello"
1,SHAPOORJI PALLONJI,Work from Home,8.5,8,2,1,2,July,üë®‚ÄçüíªDevops Engineer,"GitLab,GitHub,Bitbucket,Git","Ruby,Groovy,Jenkins,Travis CI,CircleCI","Chef,Ansible,YAML,Puppet","Kubernetes,Docker,Docker Compose,Helm","Chef,Ruby,YAML,Ansible,Python,Puppet","Java,Ruby,YAML","Trello,Jira,Slack,Microsoft Teams"
2,ICICI SECURITIES,Work from office,8.5,3,10,2,1,August,üë®‚ÄçüíªDevops Engineer,"GitHub,Bitbucket","Java,Ruby,Groovy,Travis CI","Python,Ruby,Ansible,Puppet,YAML,Chef","Docker Compose,Helm,Docker,Kubernetes","YAML,Ruby",NaN,NaN
3,TATA TECHNOLOGIES,Work from office,7.1,5,4,0,1,October,üë®‚ÄçüíªDevops Engineer,NaN,"CircleCI,Travis CI,Java,Jenkins,Groovy,Ruby","Ansible,YAML",Helm,NaN,"Prometheus,YAML,ELK stack,Java",Trello
4,TEJAS NETWORKS,Work from Home,7.9,7,3,0,0,September,üë®‚ÄçüíªDevops Engineer,"GitHub,Bitbucket","Ruby,Groovy,Travis CI,Java,Jenkins,CircleCI,Py...",Chef,"Docker,Helm,Docker Compose,Kubernetes","Python,Chef,Puppet,YAML,Ansible,Ruby","ELK stack,Java,YAML,Python,Prometheus,Nagios",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,ARMSTRONG AUTOMATION,Work from Home,6.1,10,2,0,2,August,üë®‚ÄçüíªDevops Engineer,"GitHub,Bitbucket","Python,Travis CI","Chef,YAML,Ansible,Ruby,Puppet","Docker Compose,Helm",NaN,Prometheus,"Jira,Microsoft Teams,Slack"
67,SOC GEN,Work from office,9.2,10,5,0,0,August,üë®‚ÄçüíªDevops Engineer,GitLab,"Ruby,CircleCI,Groovy,Python","Puppet,Chef,Ruby","Kubernetes,Docker,Helm,Docker Compose",NaN,"Nagios,Ruby,Grafana,Java,Python,Prometheus,ELK...",NaN
68,CITI CORPORATION,Work from Home,7.4,5,4,0,2,June,üë®‚ÄçüíªDevops Engineer,NaN,NaN,"Puppet,Python,Chef","Kubernetes,Docker Compose,Docker",NaN,Ruby,NaN
69,SOC GEN,Work from office,7.6,7,6,0,1,June,üë®‚ÄçüíªDevops Engineer,"Bitbucket,GitLab,Git,GitHub","Python,Jenkins,CircleCI,Travis CI,Java",Python,Docker Compose,"Chef,Python,YAML,Ansible","Java,Ruby,Python,ELK stack","Jira,Trello"
70,SHAPOORJI PALLONJI,Work from office,9.5,7,2,2,0,October,üë®‚ÄçüíªDevops Engineer,"GitHub,GitLab,Git","CircleCI,Python,Jenkins,Groovy","Ruby,Ansible,Chef,Python",NaN,"Ansible,Ruby,YAML","Python,Ruby,Nagios","Microsoft Teams,Jira"

In [25]:
modified_devops_df.to_csv("~\Desktop\RPOOPS\Mini Project\Part_B\Final_Data\Final_devops_data.csv")

In [26]:
cs_df=pd.read_csv("~\Desktop\RPOOPS\Mini Project\Part_B\Raw_Data_Generated\Raw_cs_data.csv")
cs_df

,Unnamed: 0,Name of company,Address of company,Phone Number,Email Address,Previous Visited COEP,Work Mode,Min CGPA,Seats for Boys,Seats for Girls,Number of Dead Backlogs permitted,Number of Active Backlogs permitted,Preffered month of visiting campus,Domain to Hire,Network Security,Application Security,Endpoint Security,Cloud Security,Data Security,Web Application Security
0,0,MICHELIN,HYDERABAD,9677311557,michelin@internship.com,Yes,Work from office,9.9,9,0,1,2,October,üïµüèªCyber Security,"Cisco Security Solutions,Juniper Networks Secu...","OpenID Connect,Advanced Encryption Standard (A...",NaN,"Active Directory,Amazon Web Services (AWS) Sec...","SHA-1,Blowfish","AppScan,Metasploit Framework,Burp Suite"
1,1,TAVISCA,CHENNAI,9164604389,tavisca@internship.com,Yes,Work from office,9.3,3,8,1,1,August,üïµüèªCyber Security,Snort,NaN,"Trend Micro Endpoint Security,McAfee Endpoint ...",NaN,"SHA-3,Blowfish,MD5,RSA,SHA-1,SHA-2,Data Encryp...","WebInspect,Acunetix,Metasploit Framework,AppSc..."
2,2,CREDIT SUISSE,JAPAN,9794656525,creditsuisse@internship.com,Yes,Work from office,6.4,4,0,2,0,June,üïµüèªCyber Security,"Cisco Security Solutions,Juniper Networks Secu...",LDAP,"Trend Micro Endpoint Security,Symantec Endpoin...","Microsoft Azure Security Tools,Amazon Web Serv...","SHA-3,RSA,Data Encryption Standard (DES),Advan...","Nessus,McAfee Secure,Burp Suite,OWASP ZAP,Spri..."
3,3,REIANCE JIO MEDIA,BANGALORE,9484233194,reiancejiomedia@internship.com,Yes,Work from office,8.4,6,9,1,1,August,üïµüèªCyber Security,NaN,"MD5,SHA-1,Data Encryption Standard (DES),SHA-2...","Symantec Endpoint Protection,McAfee Endpoint S...","Google Cloud Platform (GCP) Security Tools,Mic...","SHA-3,RSA,SHA-2","Metasploit Framework,Burp Suite,WebInspect,McA..."
4,4,DESHAW,CHENNAI,9108866421,deshaw@internship.com,No,Work from office,6.7,3,5,1,2,June,üïµüèªCyber Security,"Cisco Security Solutions,Juniper Networks Secu...","Blowfish,OpenID Connect,OAuth,SAML",Symantec Endpoint Protection,"Amazon Web Services (AWS) Security Tools,Googl...",NaN,"Qualys,Spring Framework,Nessus,AppScan,WebInsp..."
5,5,MERCEDES BENZ,BANGALORE,9146379983,mercedesbenz@internship.com,Yes,Work from office,9.2,9,2,0,1,July,üïµüèªCyber Security,NaN,NaN,"Symantec Endpoint Protection,Trend Micro Endpo...",Active Directory,"Blowfish,RSA,SHA-1,Data Encryption Standard (D...","Spring Framework,Acunetix,OWASP ZAP,WebInspect..."
6,6,FAURECIA,MUMBAI,9903660445,faurecia@internship.com,No,Work from Home,8.9,0,1,1,0,July,üïµüèªCyber Security,NaN,"Advanced Encryption Standard (AES),SHA-1,OAuth...",Symantec Endpoint Protection,"Google Cloud Platform (GCP) Security Tools,Mic...","Blowfish,SHA-3,Data Encryption Standard (DES),...","WebInspect,McAfee Secure,Metasploit Framework,..."
7,7,HELLA,GUJARAT,9020818745,hella@internship.com,No,Work from office,6.0,1,6,1,1,August,üïµüèªCyber Security,NaN,"Data Encryption Standard (DES),Blowfish,MD5,Op...","Symantec Endpoint Protection,Trend Micro Endpo...","Microsoft Azure Security Tools,Amazon Web Serv...",RSA,"Burp Suite,Spring Framework,Acunetix,AppScan,O..."
8,8,VODAFONE,HYDERABAD,9279520662,vodafone@internship.com,No,Work from Home,7.4,2,6,1,0,October,üïµüèªCyber Security,"Snort,Juniper Networks Security Solutions,Cisc...","SHA-3,SAML,SHA-1,MD5,Blowfish",Trend Micro Endpoint Security,Microsoft Azure Security Tools,"MD5,Blowfish,RSA,SHA-3","OWASP ZAP,AppScan,Nessus,Acunetix,Burp Suite,M..."
9,9,GOOGLE,MUMBAI,9416664071,google@internship.com,Yes,Work from Home,6.3,6,4,1,1,October,üïµüèªCyber Security,NaN,"LDAP,OAuth,OpenID Connect,Blowfish,SHA-3,MD5,S...","McAfee Endpoint Security,Trend Micro Endpoint ...","Active Directory,Microsoft Azure Security Tools","SHA-2,Data Encryption Standard (DES),MD5,SHA-3...","Spring Framework,AppScan,Nessus,WebInspect,Bur..."
10,10,TEXAS INSTRUMENTS,AURANGABAD,9119647552,texasinstruments@internship.com,Yes,Work from Home,8.7,3,10,0,2,December,üïµüèªCyber Security,Juniper Networks Security Solutions,"SHA-1,Blowfish,SAML,SHA-2,Advanced Encryption ...",Trend Micro Endpoint Security,NaN,"SHA-3,MD5,SHA-1","Acunetix,Nessus,Spring Framework,OWASP ZAP,Bur..."
11,11,MICROLAND LTD,JAIPUR,9814097596,microlandltd@internship.com,Yes,Work from office,6.3,8,1,2,2,August,üïµüèªCyber Security,NaN,NaN,"McAfee Endpoint Security,Trend Micro Endpoint ...","Active Directory,Google Cloud Platform (GCP) S...","Data Encryption Standard (DES),SHA-1,Blowfish,...",NaN
12,12,GOOGLE,JAIPUR,9485756041,google@internship.com,No,Work from Home,8.3,1,10,0,2,August,üïµüèªCyber Security,"Cisco Security Solutions,Juniper Networks Secu...",NaN,"Trend Micro Endpoint Security,McAfee Endpoint ...",NaN,"Blowfish,SHA-2,RSA,SHA-1,MD5","OWASP ZAP,AppScan,Metasploit Framework,McAfee ..."
13,13,VODAFONE,KOLKATA,9258840412,vodafone@internship.com,Yes,Work from office,7.5,1,6,0,1,June,üïµüèªCyber Security,Juniper Networks Security Solutions,SHA-3,"Trend Micro Endpoint Security,Symantec Endpoin...",NaN,"SHA-2,MD5,Blowfish,Data Encryption Standard (DES)","Acunetix,AppScan,Burp Suite,Spring Framework,M..."
14,14,GODREJ & BOYCE,NAVI MUMBAI,9014968256,godrej&boyce@internship.com,Yes,Work from Home,7.0,2,4,0,2,October,üïµüèªCyber Security,"Cisco Security Solutions,Juniper Networks Secu...","SHA-1,Blowfish,LDAP,SAML,OpenID Connect,RSA,MD...",NaN,"Amazon Web Services (AWS) Security Tools,Micro...","RSA,Data Encryption Standard (DES),SHA-3,SHA-2...",OWASP ZAP
15,15,DEUTSCHE BANK,KOLKATA,9218777826,deutschebank@internship.com,No,Work from Home,8.6,2,9,2,0,December,üïµüèªCyber Security,NaN,"MD5,LDAP,Blowfish,RSA,OAuth,OpenID Connect,SAM...",Symantec Endpoint Protection,NaN,"RSA,Data Encryption Standard (DES),SHA-3,SHA-1...","Acunetix,Metasploit Framework,Qualys,Nessus,We..."
16,16,BETSOL,BANGALORE,9762947768,betsol@internship.com,Yes,Work from Home,7.5,2,8,0,1,Novermber,üïµüèªCyber Security,"Cisco Security Solutions,Snort","SAML,Blowfish,Data Encryption Standard (DES),A...","Symantec Endpoint Protection,McAfee Endpoint S...",NaN,"Advanced Encryption Standard (AES),Data Encryp...","Metasploit Framework,WebInspect,Nessus,Qualys,..."
17,17,ALIGNED AUTOMATION,HARYANA,9040295118,alignedautomation@internship.com,Yes,Work from office,7.7,7,0,0,0,Novermber,üïµüèªCyber Security,NaN,NaN,McAfee Endpoint Security,"Google Cloud Platform (GCP) Security Tools,Act...","Blowfish,MD5,Advanced Encryption Standard (AES...","AppScan,Acunetix,Qualys,WebInspect,Spring Fram..."
18,18,TALLY SOLUTIONS,PUNE,9451612220,tallysolutions@internship.com,No,Work from office,7.3,10,10,2,0,December,üïµüèªCyber Security,NaN,NaN,"McAfee Endpoint Security,Symantec Endpoint Pro...",NaN,"Blowfish,Advanced Encryption Standard (AES),Da...","Metasploit Framework,Burp Suite,AppScan,Nessus"
19,19,TALLY SOLUTIONS,NOIDA,9888004987,tallysolutions@internship.com,Yes,Work from Home,7.4,0,4,1,0,August,üïµüèªCyber Security,NaN,"Advanced Encryption Standard (AES),SHA-3,OpenI...",McAfee Endpoint Security,"Active Directory,Microsoft Azure Security Tool...","SHA-3,RSA,SHA-1,Data Encryption Standard (DES)","AppScan,Qualys,Nessus,OWASP ZAP,Burp Suite"
20,20,SIEMENS LIMITED COBRA,GURGAON,9181971126,siemenslimitedcobra@internship.com,Yes,Work from Home,8.9,4,4,0,2,December,üïµüèªCyber Security,"Juniper Networks Security Solutions,Snort,Cisc...","RSA,OAuth,Data Encryption Standard (DES)","Symantec Endpoint Protection,McAfee Endpoint S...","Active Directory,Google Cloud Platform (GCP) S...","SHA-2,Blowfish,Advanced Encryption Standard (A...","Metasploit Framework,AppScan,Nessus"
21,21,MERCEDES BENZ,HARYANA,9379156122,mercedesbenz@internship.com,No,Work from office,7.0,4,7,0,0,July,üïµüèªCyber Security,"Juniper Networks Security Solutions,Cisco Secu...","LDAP,Advanced Encryption Standard (AES),SHA-3,...","Trend Micro Endpoint Security,Symantec Endpoin...",Amazon Web Services (AWS) Security Tools,"SHA-1,MD5","Nessus,AppScan"
22,22,FAMITECH TECHNOLOGY,GUJARAT,9814500894,famitechtechnology@internship.com,Yes,Work from Home,7.0,9,8,2,1,December,üïµüèªCyber Security,NaN,"Blowfish,MD5,OpenID Connect,LDAP,SHA-2,Data En...",NaN,Amazon Web Services (AWS) Security Tools,Advanced Encryption Standard (AES),"Nessus,Acunetix,Spring Framework,WebInspect,OW..."
23,23,WINJIT TECHNOLOGIES,MUMBAI,9099248552,winjittechnologies@internship.com,No,Work from Home,9.0,1,8,2,2,June,üïµüèªCyber Security,Cisco Security Solutions,"SHA-1,RSA,OpenID Connect,SHA-2,LDAP,SAML,Blowf...",McAfee Endpoint Security,NaN,"MD5,SHA-2","Spring Framework,Nessus,WebInspect,Metasploit ..."
24,24,ALIGNED AUTOMATION,AURANGABAD,9661326797,alignedautomation@internship.com,Yes,Work from office,8.9,3,4,1,0,August,üïµüèªCyber Security,"Cisco Security Solutions,Snort,Juniper Network...","SHA-3,RSA",NaN,"Active Directory,Microsoft Azure Security Tool...",RSA,"OWASP ZAP,Burp Suite,McAfee Secure,Qualys,WebI..."
25,25,FEV INDIA,WALCHAND,9315997873,fevindia@internship.com,No,Work from Home,8.9,7,6,1,0,October,üïµüèªCyber Security,NaN,"SHA-3,OAuth,RSA,SHA-1,Data Encryption Standard...",NaN,"Active Directory,Google Cloud Platform (GCP) S...","Blowfish,MD5,RSA,Data Encryption Standard (DES...","AppScan,Burp Suite,Qualys,McAfee Secure"
26,26,HYUNDAI MOTORS,LATUR,9617335641,hyundaimotors@internship.com,No,Work from Home,7.6,4,3,1,0,July,üïµüèªCyber Security,"Snort,Cisco Security Solutions",NaN,"McAfee Endpoint Security,Symantec Endpoint Pro...","Microsoft Azure Security Tools,Active Director...","Blowfish,RSA,MD5,SHA-1,Data Encryption Standar...","Nessus,McAfee Secure,OWASP ZAP,Qualys,AppScan,..."
27,27,RELIANCE JIO,LATUR,9056291477,reliancejio@internship.com,Yes,Work from office,6.2,0,0,0,2,September,üïµüèªCyber Security,NaN,"Data Encryption Standard (DES),SAML,OpenID Con...","Trend Micro Endpoint Security,Symantec Endpoin...",NaN,RSA,"AppScan,Qualys,McAfee Secure,Metasploit Framew..."
28,28,NEOSYM,PUNE,9559187635,neosym@internship.com,Yes,Work from Home,10.0,5,10,0,2,December,üïµüèªCyber Security,"Juniper Networks Security Solutions,Cisco Secu...","SHA-2,RSA,SHA-1",NaN,Amazon Web Services (AWS) Security Tools,RSA,"OWASP ZAP,Qualys,Burp Suite,Acunetix,Nessus,Sp..."
29,29,TORRENT GAS,JAPAN,9944561985,torrentgas@internship.com,Yes,Work from Home,7.4,4,2,0,1,Novermber,üïµüèªCyber Security,Juniper Networks Security Solutions,"MD5,LDAP,OpenID Connect,SHA-2,Data Encryption ...",Symantec Endpoint Protection,"Google Cloud Platform (GCP) Security Tools,Mic...","Blowfish,SHA-2,MD5","Metasploit Framework,Spring Framework,Nessus,A..."
30,30,ASSYSTEM STUP,NASHIK,9211997940,assystemstup@internship.com,Yes,Work from office,8.4,8,10,2,2,June,üïµüèªCyber Security,"Juniper Networks Security Solutions,Snort","SHA-1,LDAP,SHA-2,SHA-3,Data Encryption Standar...",Symantec Endpoint Protection,"Amazon Web Services (AWS) Security Tools,Googl...","SHA-3,SHA-1,SHA-2,RSA","Metasploit Framework,Qualys,Spring Framework,A..."
31,31,ATOMBERG,NOIDA,9950392146,atomberg@internship.com,Yes,Work from office,6.6,10,5,0,2,August,üïµüèªCyber Security,NaN,SHA-2,"Trend Micro Endpoint Security,Symantec Endpoin...","Google Cloud Platform (GCP) Security Tools,Mic...","Blowfish,RSA,MD5,Advanced Encryption Standard ...","Acunetix,WebInspect,OWASP ZAP,Spring Framework..."
32,32,L&T LIMITED,KOLKATA,9900714130,l&tlimited@internship.com,No,Work from Home,6.3,6,6,2,0,September,üïµüèªCyber Security,"Cisco Security Solutions,Snort","MD5,SHA-3,SHA-2,RSA,OAuth,Blowfish,OpenID Conn...","McAfee Endpoint Security,Symantec Endpoint Pro...","Active Directory,Amazon Web Services (AWS) Sec...","Blowfish,MD5,SHA-2,SHA-1,Data Encryption Stand...","Acunetix,Qualys,Burp Suite,OWASP ZAP"
33,33,SOC GEN,MUMBAI,9979025847,socgen@internship.com,Yes,Work from Home,6.1,4,10,0,1,June,üïµüèªCyber Security,"Juniper Networks Security Solutions,Snort","OpenID Connect,SHA-1","McAfee Endpoint Security,Trend Micro Endpoint ...","Active Directory,Google Cloud Platform (GCP) S...",SHA-3,WebInspect
34,34,SIEMENS ENERGY,JAIPUR,9820951620,siemensenergy@internship.com,Yes,Work from Home,7.9,10,3,2,2,August,üïµüèªCyber Security,"Juniper Networks Security Solutions,Cisco Secu...","SHA-2,OAuth","Symantec Endpoint Protection,Trend Micro Endpo...","Active Directory,Google Cloud Platform (GCP) S...","Data Encryption Standard (DES),MD5,Advanced En...","Nessus,Spring Framework,Acunetix"
35,35,JSW GROUP,JAIPUR,9561643811,jswgroup@internship.com,No,Work from Home,9.0,5,9,0,1,June,üïµüèªCyber Security,"Juniper Networks Security Solutions,Snort","Data Encryption Standard (DES),SAML,SHA-1,RSA,...",Trend Micro Endpoint Security,"Google Cloud Platform (GCP) Security Tools,Act...","RSA,SHA-1,SHA-3,Blowfish","Burp Suite,Metasploit Framework,OWASP ZAP,WebI..."
36,36,PIRAMAL,MUMBAI,9899732112,piramal@internship.com,No,Work from Home,8.9,3,10,1,2,July,üïµüèªCyber Security,Cisco Security Solutions,"SHA-1,OpenID Connect,Advanced Encryption Stand...",NaN,NaN,"Data Encryption Standard (DES),SHA-1,MD5,Advan...","OWASP ZAP,Qualys,Burp Suite"
37,37,ADM,WALCHAND,9217691474,adm@internship.com,No,Work from Home,6.4,8,5,0,2,Novermber,üïµüèªCyber Security,"Snort,Juniper Networks Security Solutions,Cisc...","RSA,SHA-1,OpenID Connect,LDAP,MD5,SHA-2,SHA-3",NaN,NaN,SHA-1,"Qualys,Burp Suite,McAfee Secure"
38,38,AMURA MARKETING TECHNOLOGIES,NAVI MUMBAI,9086327202,amuramarketingtechnologies@internship.com,Yes,Work from Home,9.5,7,6,2,2,December,üïµüèªCyber Security,"Snort,Cisco Security Solutions,Juniper Network...","Blowfish,LDAP,MD5,Data Encryption Standard (DE...",NaN,NaN,"SHA-2,SHA-1,MD5","McAfee Secure,Burp Suite,AppScan,Metasploit Fr..."
39,39,CATERPILLAR,HYDERABAD,9466581489,caterpillar@internship.com,Yes,Work from office,8.5,10,10,0,2,December,üïµüèªCyber Security,"Juniper Networks Security Solutions,Cisco Secu...",OAuth,McAfee Endpoint Security,NaN,"Data Encryption Standard (DES),SHA-1,RSA,Advan...","Burp Suite,Spring Framework,OWASP ZAP,Metasplo..."
40,40,ION GROUP,JAPAN,9269161746,iongroup@internship.com,No,Work from Home,6.2,6,1,1,2,Novermber,üïµüèªCyber Security,NaN,"OpenID Connect,OAuth,LDAP,SHA-1,Advanced Encry...","Symantec Endpoint Protection,Trend Micro Endpo...",Active Directory,"SHA-3,Advanced Encryption Standard (AES),SHA-2...","Acunetix,AppScan,OWASP ZAP,Nessus,Qualys,Sprin..."
41,41,BAIN CAPABILITY NETWORKS,AURANGABAD,9381296218,baincapabilitynetworks@internship.com,Yes,Work from Home,8.4,8,8,2,2,Novermber,üïµüèªCyber Security,"Cisco Security Solutions,Juniper Networks Secu...","SHA-3,OAuth,OpenID Connect,Blowfish,SAML,MD5,D...","McAfee Endpoint Security,Trend Micro Endpoint ...",NaN,"Advanced Encryption Standard (AES),RSA,SHA-1",NaN
42,42,WHIRLPOOL INDIA,AHMEDABAD,9363920437,whirlpoolindia@internship.com,Yes,Work from Home,8.2,5,8,1,1,July,üïµüèªCyber Security,NaN,"SHA-3,OAuth,OpenID Connect,LDAP,Advanced Encry...",NaN,"Active Directory,Google Cloud Platform (GCP) S...","MD5,SHA-1,SHA-3,RSA","Burp Suite,AppScan,Qualys,McAfee Secure,WebIns..."
43,43,REBEL FOODS,CHENNAI,9422941588,rebelfoods@internship.com,No,Work from Home,9.7,1,7,0,2,December,üïµüèªCyber Security,NaN,"MD5,Advanced Encryption Standard (AES),SHA-2,D...",McAfee Endpoint Security,Amazon Web Services (AWS) Security Tools,"SHA-3,SHA-2,Advanced Encryption Standard (AES)...","AppScan,Spring Framework,Nessus,WebInspect,OWA..."
44,44,SHAH TECHNICAL CONSULTANTS PVT.LTD,NASHIK,9536290664,shahtechnicalconsultantspvt.ltd@internship.com,Yes,Work from Home,6.6,6,9,2,1,July,üïµüèªCyber Security,Juniper Networks Security Solutions,"SHA-3,RSA",NaN,"Microsoft Azure Security Tools,Amazon Web Serv...","SHA-3,SHA-1,RSA,Advanced Encryption Standard (...","OWASP ZAP,Acunetix,Spring Framework,Metasploit..."
45,45,ION GROUP,HARYANA,9912938216,iongroup@internship.com,No,Work from Home,9.0,8,9,1,0,Novermber,üïµüèªCyber Security,"Cisco Security Solutions,Juniper Networks Secu...","Advanced Encryption Standard (AES),RSA,SHA-1,D...","Symantec Endpoint Protection,Trend Micro Endpo...",NaN,"Blowfish,Data Encryption Standard (DES),RSA,SH...","Nessus,WebInspect,OWASP ZAP,Metasploit Framewo..."
46,46,ACCENTURE,NOIDA,9861836554,accenture@internship.com,Yes,Work from Home,8.0,1,10,1,1,June,üïµüèªCyber Security,NaN,"LDAP,RSA,OAuth,SHA-2,SAML",Trend Micro Endpoint Security,NaN,"Blowfish,SHA-1","Metasploit Framework,Burp Suite,Nessus,Qualys,..."
47,47,SKF ENGINEERING AND LUBRICATION INDIA,GURGAON,9829405620,skfengineeringandlubricationindia@internship.com,Yes,Work from office,7.4,1,8,1,0,October,üïµüèªCyber Security,"Cisco Security Solutions,Juniper Networks Secu...","SAML,RSA,LDAP,MD5,OpenID Connect,Blowfish",McAfee Endpoint Security,"Active Directory,Amazon Web Services (AWS) Sec...","Data Encryption Standard (DES),RSA,SHA-1,SHA-2...","Burp Suite,WebInspect,Qualys,McAfee Secure,Spr..."
48,48,MASTERCARD,NOIDA,9268622098,mastercard@internship.com,No,Work from office,9.4,2,6,2,2,October,üïµüèªCyber Security,"Juniper Networks Security Solutions,Cisco Secu...",Advanced Encryption Standard (AES),"Symantec Endpoint Protection,Trend Micro Endpo...","Amazon Web Services (AWS) Security Tools,Googl...","Advanced Encryption Standard (AES),MD5,SHA-3","AppScan,WebInspect,McAfee Secure,Acunetix,Meta..."

In [27]:
modified_cs_df=cs_df.drop(['Unnamed: 0','Address of company', 'Phone Number',
       'Email Address', 'Previous Visited COEP'],axis=1)
modified_cs_df

,Name of company,Work Mode,Min CGPA,Seats for Boys,Seats for Girls,Number of Dead Backlogs permitted,Number of Active Backlogs permitted,Preffered month of visiting campus,Domain to Hire,Network Security,Application Security,Endpoint Security,Cloud Security,Data Security,Web Application Security
0,MICHELIN,Work from office,9.9,9,0,1,2,October,üïµüèªCyber Security,"Cisco Security Solutions,Juniper Networks Secu...","OpenID Connect,Advanced Encryption Standard (A...",NaN,"Active Directory,Amazon Web Services (AWS) Sec...","SHA-1,Blowfish","AppScan,Metasploit Framework,Burp Suite"
1,TAVISCA,Work from office,9.3,3,8,1,1,August,üïµüèªCyber Security,Snort,NaN,"Trend Micro Endpoint Security,McAfee Endpoint ...",NaN,"SHA-3,Blowfish,MD5,RSA,SHA-1,SHA-2,Data Encryp...","WebInspect,Acunetix,Metasploit Framework,AppSc..."
2,CREDIT SUISSE,Work from office,6.4,4,0,2,0,June,üïµüèªCyber Security,"Cisco Security Solutions,Juniper Networks Secu...",LDAP,"Trend Micro Endpoint Security,Symantec Endpoin...","Microsoft Azure Security Tools,Amazon Web Serv...","SHA-3,RSA,Data Encryption Standard (DES),Advan...","Nessus,McAfee Secure,Burp Suite,OWASP ZAP,Spri..."
3,REIANCE JIO MEDIA,Work from office,8.4,6,9,1,1,August,üïµüèªCyber Security,NaN,"MD5,SHA-1,Data Encryption Standard (DES),SHA-2...","Symantec Endpoint Protection,McAfee Endpoint S...","Google Cloud Platform (GCP) Security Tools,Mic...","SHA-3,RSA,SHA-2","Metasploit Framework,Burp Suite,WebInspect,McA..."
4,DESHAW,Work from office,6.7,3,5,1,2,June,üïµüèªCyber Security,"Cisco Security Solutions,Juniper Networks Secu...","Blowfish,OpenID Connect,OAuth,SAML",Symantec Endpoint Protection,"Amazon Web Services (AWS) Security Tools,Googl...",NaN,"Qualys,Spring Framework,Nessus,AppScan,WebInsp..."
5,MERCEDES BENZ,Work from office,9.2,9,2,0,1,July,üïµüèªCyber Security,NaN,NaN,"Symantec Endpoint Protection,Trend Micro Endpo...",Active Directory,"Blowfish,RSA,SHA-1,Data Encryption Standard (D...","Spring Framework,Acunetix,OWASP ZAP,WebInspect..."
6,FAURECIA,Work from Home,8.9,0,1,1,0,July,üïµüèªCyber Security,NaN,"Advanced Encryption Standard (AES),SHA-1,OAuth...",Symantec Endpoint Protection,"Google Cloud Platform (GCP) Security Tools,Mic...","Blowfish,SHA-3,Data Encryption Standard (DES),...","WebInspect,McAfee Secure,Metasploit Framework,..."
7,HELLA,Work from office,6.0,1,6,1,1,August,üïµüèªCyber Security,NaN,"Data Encryption Standard (DES),Blowfish,MD5,Op...","Symantec Endpoint Protection,Trend Micro Endpo...","Microsoft Azure Security Tools,Amazon Web Serv...",RSA,"Burp Suite,Spring Framework,Acunetix,AppScan,O..."
8,VODAFONE,Work from Home,7.4,2,6,1,0,October,üïµüèªCyber Security,"Snort,Juniper Networks Security Solutions,Cisc...","SHA-3,SAML,SHA-1,MD5,Blowfish",Trend Micro Endpoint Security,Microsoft Azure Security Tools,"MD5,Blowfish,RSA,SHA-3","OWASP ZAP,AppScan,Nessus,Acunetix,Burp Suite,M..."
9,GOOGLE,Work from Home,6.3,6,4,1,1,October,üïµüèªCyber Security,NaN,"LDAP,OAuth,OpenID Connect,Blowfish,SHA-3,MD5,S...","McAfee Endpoint Security,Trend Micro Endpoint ...","Active Directory,Microsoft Azure Security Tools","SHA-2,Data Encryption Standard (DES),MD5,SHA-3...","Spring Framework,AppScan,Nessus,WebInspect,Bur..."
10,TEXAS INSTRUMENTS,Work from Home,8.7,3,10,0,2,December,üïµüèªCyber Security,Juniper Networks Security Solutions,"SHA-1,Blowfish,SAML,SHA-2,Advanced Encryption ...",Trend Micro Endpoint Security,NaN,"SHA-3,MD5,SHA-1","Acunetix,Nessus,Spring Framework,OWASP ZAP,Bur..."
11,MICROLAND LTD,Work from office,6.3,8,1,2,2,August,üïµüèªCyber Security,NaN,NaN,"McAfee Endpoint Security,Trend Micro Endpoint ...","Active Directory,Google Cloud Platform (GCP) S...","Data Encryption Standard (DES),SHA-1,Blowfish,...",NaN
12,GOOGLE,Work from Home,8.3,1,10,0,2,August,üïµüèªCyber Security,"Cisco Security Solutions,Juniper Networks Secu...",NaN,"Trend Micro Endpoint Security,McAfee Endpoint ...",NaN,"Blowfish,SHA-2,RSA,SHA-1,MD5","OWASP ZAP,AppScan,Metasploit Framework,McAfee ..."
13,VODAFONE,Work from office,7.5,1,6,0,1,June,üïµüèªCyber Security,Juniper Networks Security Solutions,SHA-3,"Trend Micro Endpoint Security,Symantec Endpoin...",NaN,"SHA-2,MD5,Blowfish,Data Encryption Standard (DES)","Acunetix,AppScan,Burp Suite,Spring Framework,M..."
14,GODREJ & BOYCE,Work from Home,7.0,2,4,0,2,October,üïµüèªCyber Security,"Cisco Security Solutions,Juniper Networks Secu...","SHA-1,Blowfish,LDAP,SAML,OpenID Connect,RSA,MD...",NaN,"Amazon Web Services (AWS) Security Tools,Micro...","RSA,Data Encryption Standard (DES),SHA-3,SHA-2...",OWASP ZAP
15,DEUTSCHE BANK,Work from Home,8.6,2,9,2,0,December,üïµüèªCyber Security,NaN,"MD5,LDAP,Blowfish,RSA,OAuth,OpenID Connect,SAM...",Symantec Endpoint Protection,NaN,"RSA,Data Encryption Standard (DES),SHA-3,SHA-1...","Acunetix,Metasploit Framework,Qualys,Nessus,We..."
16,BETSOL,Work from Home,7.5,2,8,0,1,Novermber,üïµüèªCyber Security,"Cisco Security Solutions,Snort","SAML,Blowfish,Data Encryption Standard (DES),A...","Symantec Endpoint Protection,McAfee Endpoint S...",NaN,"Advanced Encryption Standard (AES),Data Encryp...","Metasploit Framework,WebInspect,Nessus,Qualys,..."
17,ALIGNED AUTOMATION,Work from office,7.7,7,0,0,0,Novermber,üïµüèªCyber Security,NaN,NaN,McAfee Endpoint Security,"Google Cloud Platform (GCP) Security Tools,Act...","Blowfish,MD5,Advanced Encryption Standard (AES...","AppScan,Acunetix,Qualys,WebInspect,Spring Fram..."
18,TALLY SOLUTIONS,Work from office,7.3,10,10,2,0,December,üïµüèªCyber Security,NaN,NaN,"McAfee Endpoint Security,Symantec Endpoint Pro...",NaN,"Blowfish,Advanced Encryption Standard (AES),Da...","Metasploit Framework,Burp Suite,AppScan,Nessus"
19,TALLY SOLUTIONS,Work from Home,7.4,0,4,1,0,August,üïµüèªCyber Security,NaN,"Advanced Encryption Standard (AES),SHA-3,OpenI...",McAfee Endpoint Security,"Active Directory,Microsoft Azure Security Tool...","SHA-3,RSA,SHA-1,Data Encryption Standard (DES)","AppScan,Qualys,Nessus,OWASP ZAP,Burp Suite"
20,SIEMENS LIMITED COBRA,Work from Home,8.9,4,4,0,2,December,üïµüèªCyber Security,"Juniper Networks Security Solutions,Snort,Cisc...","RSA,OAuth,Data Encryption Standard (DES)","Symantec Endpoint Protection,McAfee Endpoint S...","Active Directory,Google Cloud Platform (GCP) S...","SHA-2,Blowfish,Advanced Encryption Standard (A...","Metasploit Framework,AppScan,Nessus"
21,MERCEDES BENZ,Work from office,7.0,4,7,0,0,July,üïµüèªCyber Security,"Juniper Networks Security Solutions,Cisco Secu...","LDAP,Advanced Encryption Standard (AES),SHA-3,...","Trend Micro Endpoint Security,Symantec Endpoin...",Amazon Web Services (AWS) Security Tools,"SHA-1,MD5","Nessus,AppScan"
22,FAMITECH TECHNOLOGY,Work from Home,7.0,9,8,2,1,December,üïµüèªCyber Security,NaN,"Blowfish,MD5,OpenID Connect,LDAP,SHA-2,Data En...",NaN,Amazon Web Services (AWS) Security Tools,Advanced Encryption Standard (AES),"Nessus,Acunetix,Spring Framework,WebInspect,OW..."
23,WINJIT TECHNOLOGIES,Work from Home,9.0,1,8,2,2,June,üïµüèªCyber Security,Cisco Security Solutions,"SHA-1,RSA,OpenID Connect,SHA-2,LDAP,SAML,Blowf...",McAfee Endpoint Security,NaN,"MD5,SHA-2","Spring Framework,Nessus,WebInspect,Metasploit ..."
24,ALIGNED AUTOMATION,Work from office,8.9,3,4,1,0,August,üïµüèªCyber Security,"Cisco Security Solutions,Snort,Juniper Network...","SHA-3,RSA",NaN,"Active Directory,Microsoft Azure Security Tool...",RSA,"OWASP ZAP,Burp Suite,McAfee Secure,Qualys,WebI..."
25,FEV INDIA,Work from Home,8.9,7,6,1,0,October,üïµüèªCyber Security,NaN,"SHA-3,OAuth,RSA,SHA-1,Data Encryption Standard...",NaN,"Active Directory,Google Cloud Platform (GCP) S...","Blowfish,MD5,RSA,Data Encryption Standard (DES...","AppScan,Burp Suite,Qualys,McAfee Secure"
26,HYUNDAI MOTORS,Work from Home,7.6,4,3,1,0,July,üïµüèªCyber Security,"Snort,Cisco Security Solutions",NaN,"McAfee Endpoint Security,Symantec Endpoint Pro...","Microsoft Azure Security Tools,Active Director...","Blowfish,RSA,MD5,SHA-1,Data Encryption Standar...","Nessus,McAfee Secure,OWASP ZAP,Qualys,AppScan,..."
27,RELIANCE JIO,Work from office,6.2,0,0,0,2,September,üïµüèªCyber Security,NaN,"Data Encryption Standard (DES),SAML,OpenID Con...","Trend Micro Endpoint Security,Symantec Endpoin...",NaN,RSA,"AppScan,Qualys,McAfee Secure,Metasploit Framew..."
28,NEOSYM,Work from Home,10.0,5,10,0,2,December,üïµüèªCyber Security,"Juniper Networks Security Solutions,Cisco Secu...","SHA-2,RSA,SHA-1",NaN,Amazon Web Services (AWS) Security Tools,RSA,"OWASP ZAP,Qualys,Burp Suite,Acunetix,Nessus,Sp..."
29,TORRENT GAS,Work from Home,7.4,4,2,0,1,Novermber,üïµüèªCyber Security,Juniper Networks Security Solutions,"MD5,LDAP,OpenID Connect,SHA-2,Data Encryption ...",Symantec Endpoint Protection,"Google Cloud Platform (GCP) Security Tools,Mic...","Blowfish,SHA-2,MD5","Metasploit Framework,Spring Framework,Nessus,A..."
30,ASSYSTEM STUP,Work from office,8.4,8,10,2,2,June,üïµüèªCyber Security,"Juniper Networks Security Solutions,Snort","SHA-1,LDAP,SHA-2,SHA-3,Data Encryption Standar...",Symantec Endpoint Protection,"Amazon Web Services (AWS) Security Tools,Googl...","SHA-3,SHA-1,SHA-2,RSA","Metasploit Framework,Qualys,Spring Framework,A..."
31,ATOMBERG,Work from office,6.6,10,5,0,2,August,üïµüèªCyber Security,NaN,SHA-2,"Trend Micro Endpoint Security,Symantec Endpoin...","Google Cloud Platform (GCP) Security Tools,Mic...","Blowfish,RSA,MD5,Advanced Encryption Standard ...","Acunetix,WebInspect,OWASP ZAP,Spring Framework..."
32,L&T LIMITED,Work from Home,6.3,6,6,2,0,September,üïµüèªCyber Security,"Cisco Security Solutions,Snort","MD5,SHA-3,SHA-2,RSA,OAuth,Blowfish,OpenID Conn...","McAfee Endpoint Security,Symantec Endpoint Pro...","Active Directory,Amazon Web Services (AWS) Sec...","Blowfish,MD5,SHA-2,SHA-1,Data Encryption Stand...","Acunetix,Qualys,Burp Suite,OWASP ZAP"
33,SOC GEN,Work from Home,6.1,4,10,0,1,June,üïµüèªCyber Security,"Juniper Networks Security Solutions,Snort","OpenID Connect,SHA-1","McAfee Endpoint Security,Trend Micro Endpoint ...","Active Directory,Google Cloud Platform (GCP) S...",SHA-3,WebInspect
34,SIEMENS ENERGY,Work from Home,7.9,10,3,2,2,August,üïµüèªCyber Security,"Juniper Networks Security Solutions,Cisco Secu...","SHA-2,OAuth","Symantec Endpoint Protection,Trend Micro Endpo...","Active Directory,Google Cloud Platform (GCP) S...","Data Encryption Standard (DES),MD5,Advanced En...","Nessus,Spring Framework,Acunetix"
35,JSW GROUP,Work from Home,9.0,5,9,0,1,June,üïµüèªCyber Security,"Juniper Networks Security Solutions,Snort","Data Encryption Standard (DES),SAML,SHA-1,RSA,...",Trend Micro Endpoint Security,"Google Cloud Platform (GCP) Security Tools,Act...","RSA,SHA-1,SHA-3,Blowfish","Burp Suite,Metasploit Framework,OWASP ZAP,WebI..."
36,PIRAMAL,Work from Home,8.9,3,10,1,2,July,üïµüèªCyber Security,Cisco Security Solutions,"SHA-1,OpenID Connect,Advanced Encryption Stand...",NaN,NaN,"Data Encryption Standard (DES),SHA-1,MD5,Advan...","OWASP ZAP,Qualys,Burp Suite"
37,ADM,Work from Home,6.4,8,5,0,2,Novermber,üïµüèªCyber Security,"Snort,Juniper Networks Security Solutions,Cisc...","RSA,SHA-1,OpenID Connect,LDAP,MD5,SHA-2,SHA-3",NaN,NaN,SHA-1,"Qualys,Burp Suite,McAfee Secure"
38,AMURA MARKETING TECHNOLOGIES,Work from Home,9.5,7,6,2,2,December,üïµüèªCyber Security,"Snort,Cisco Security Solutions,Juniper Network...","Blowfish,LDAP,MD5,Data Encryption Standard (DE...",NaN,NaN,"SHA-2,SHA-1,MD5","McAfee Secure,Burp Suite,AppScan,Metasploit Fr..."
39,CATERPILLAR,Work from office,8.5,10,10,0,2,December,üïµüèªCyber Security,"Juniper Networks Security Solutions,Cisco Secu...",OAuth,McAfee Endpoint Security,NaN,"Data Encryption Standard (DES),SHA-1,RSA,Advan...","Burp Suite,Spring Framework,OWASP ZAP,Metasplo..."
40,ION GROUP,Work from Home,6.2,6,1,1,2,Novermber,üïµüèªCyber Security,NaN,"OpenID Connect,OAuth,LDAP,SHA-1,Advanced Encry...","Symantec Endpoint Protection,Trend Micro Endpo...",Active Directory,"SHA-3,Advanced Encryption Standard (AES),SHA-2...","Acunetix,AppScan,OWASP ZAP,Nessus,Qualys,Sprin..."
41,BAIN CAPABILITY NETWORKS,Work from Home,8.4,8,8,2,2,Novermber,üïµüèªCyber Security,"Cisco Security Solutions,Juniper Networks Secu...","SHA-3,OAuth,OpenID Connect,Blowfish,SAML,MD5,D...","McAfee Endpoint Security,Trend Micro Endpoint ...",NaN,"Advanced Encryption Standard (AES),RSA,SHA-1",NaN
42,WHIRLPOOL INDIA,Work from Home,8.2,5,8,1,1,July,üïµüèªCyber Security,NaN,"SHA-3,OAuth,OpenID Connect,LDAP,Advanced Encry...",NaN,"Active Directory,Google Cloud Platform (GCP) S...","MD5,SHA-1,SHA-3,RSA","Burp Suite,AppScan,Qualys,McAfee Secure,WebIns..."
43,REBEL FOODS,Work from Home,9.7,1,7,0,2,December,üïµüèªCyber Security,NaN,"MD5,Advanced Encryption Standard (AES),SHA-2,D...",McAfee Endpoint Security,Amazon Web Services (AWS) Security Tools,"SHA-3,SHA-2,Advanced Encryption Standard (AES)...","AppScan,Spring Framework,Nessus,WebInspect,OWA..."
44,SHAH TECHNICAL CONSULTANTS PVT.LTD,Work from Home,6.6,6,9,2,1,July,üïµüèªCyber Security,Juniper Networks Security Solutions,"SHA-3,RSA",NaN,"Microsoft Azure Security Tools,Amazon Web Serv...","SHA-3,SHA-1,RSA,Advanced Encryption Standard (...","OWASP ZAP,Acunetix,Spring Framework,Metasploit..."
45,ION GROUP,Work from Home,9.0,8,9,1,0,Novermber,üïµüèªCyber Security,"Cisco Security Solutions,Juniper Networks Secu...","Advanced Encryption Standard (AES),RSA,SHA-1,D...","Symantec Endpoint Protection,Trend Micro Endpo...",NaN,"Blowfish,Data Encryption Standard (DES),RSA,SH...","Nessus,WebInspect,OWASP ZAP,Metasploit Framewo..."
46,ACCENTURE,Work from Home,8.0,1,10,1,1,June,üïµüèªCyber Security,NaN,"LDAP,RSA,OAuth,SHA-2,SAML",Trend Micro Endpoint Security,NaN,"Blowfish,SHA-1","Metasploit Framework,Burp Suite,Nessus,Qualys,..."
47,SKF ENGINEERING AND LUBRICATION INDIA,Work from office,7.4,1,8,1,0,October,üïµüèªCyber Security,"Cisco Security Solutions,Juniper Networks Secu...","SAML,RSA,LDAP,MD5,OpenID Connect,Blowfish",McAfee Endpoint Security,"Active Directory,Amazon Web Services (AWS) Sec...","Data Encryption Standard (DES),RSA,SHA-1,SHA-2...","Burp Suite,WebInspect,Qualys,McAfee Secure,Spr..."
48,MASTERCARD,Work from office,9.4,2,6,2,2,October,üïµüèªCyber Security,"Juniper Networks Security Solutions,Cisco Secu...",Advanced Encryption Standard (AES),"Symantec Endpoint Protection,Trend Micro Endpo...","Amazon Web Services (AWS) Security Tools,Googl...","Advanced Encryption Standard (AES),MD5,SHA-3","AppScan,WebInspect,McAfee Secure,Acunetix,Meta..."

In [30]:
modified_cs_df.to_csv("~\Desktop\RPOOPS\Mini Project\Part_B\Final_Data\Final_cs_data.csv")